### ISSUE TITLE
npm ERR! "You cannot publish over the previously published version 1.1.0." 

### ISSUE THREAD

**Issue by dsslimshaddy** [semantic-release/semantic-release#406] opened 2017-07-30 16:03 UTC
Im running this. when i commit `"fix: some msg"` it always publishes the version specified in `package.json` and does not automatically changes version.

```
$ semantic-release pre && npm publish ./build && semantic-release post 

```

**Comment by vanduynslagerp** [comment] 2017-09-17 03:59
Could you provide a link to your `package.json`, `travis.yml` and the log of your CI that fail to publish ?

**Comment by yoitsro** [comment] 2017-10-18 16:53
I'm also getting this, but using Codeship. I also get the same even when running locally. Here's my setup:

package.json
```
{
  "name": "hops",
  "description": "Hops",
  "main": "index.js",
  "dependencies": {
    "google-protobuf": "^3.4.0"
  },
  "scripts": {
    "test": "exit 0",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/private-org/hops.git"
  },
  "author": "Ro Ramtohul",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/private-org/hops/issues"
  },
  "homepage": "https://github.com/private-org/hops#readme",
  "publishConfig": {
    "access": "restricted"
  },
  "engines": {
    "node": "> 8.4.0"
  },
  "version": "0.0.1",
  "devDependencies": {
    "@semantic-release/condition-codeship": "^1.1.0",
    "semantic-release": "^8.2.0"
  },
  "release": {
    "verifyConditions": [
      "@semantic-release/condition-codeship"
    ]
  }
}
```

I have the following Codeship environment variables set: `CI=true`, `GH_TOKEN` and `NPM_TOKEN`.

In the custom deployment script:
```
npm run semantic-release
```

**Comment by pvdlg** [comment] 2017-10-18 17:25
The problem happen when the next release determined by `semantic-release` already exists on the npm registry or has existed and has been unpublished.

In order to find a solution we need to figure out:
- The next release determined by `semantic-release`
- The release currently present on the npm registry
- Find out why the next release is already present on the npm registry

So ideally we need:
- The `semantic-release` logs for the build that failed
- The commit history of the project
- The metadata of the package on the npm registry (obtained with `npm view <package-name>`)

**Comment by yoitsro** [comment] 2017-10-18 17:31
So I'm doing some more digging and it looks like the `@semantic-release/condition-codeship` isn't working properly. Rather than bailing out like `@semantic-release/condition-travis` does, I get this warning:

```
(node:10647) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: semantic-release didn’t run on Codeship and therefore a new version won’t be published.
You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
(node:10647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I *think* this could have happened during a dry run when I ran it locally, but rather than bailing, it published the version in the package.json without bumping the version number.

**Comment by pvdlg** [comment] 2017-10-18 19:14
Looking at that `@semantic-release/condition-codeship` works properly and throw an error in it doesn't run on codeship.
The problem was in `semantic-release` itself, due to a bug I introduced and fixed in this commit:https://github.com/semantic-release/semantic-release/commit/90417c6ffe35c6ba479121a60085f0cfd35c6d1e

This fix was released in [8.1.1](https://github.com/semantic-release/semantic-release/releases/tag/v8.1.1). So with a version `>= 8.1.1`, if you run `semantic-release` locally it will fail as it should instead.

That said, I'm not sure it explains the problem you are facing.
If you had make an involuntary release on npm during a dry run, `semantic-release` would have detected this release as the last release, incremented this number and release a version.

The problem would happen if you unpublish this involuntary release.
NPM return this error when we try to publish a version that was unpublished.
Currently [last-release-npm](semantic-release/last-release-npm) doesn't detect unpublished version. We are looking at a solution to handle this edge case.

**Comment by yoitsro** [comment] 2017-10-18 19:16
More digging:

When `release.verifyConditions` in `package.json` is an array, rejected promises aren't caught properly...

When it's just a string, the error is caught and the rest of the flow happens as expected.

**Comment by pvdlg** [comment] 2017-10-18 19:34
This case is tested here: [plugins.test.js#L47](https://github.com/semantic-release/semantic-release/blob/caribou/test/plugins.test.js#L47). Maybe there is a problem somewhere else that cause this behavior.

Can you share the configuration and the reproduction steps?

**Comment by yoitsro** [comment] 2017-10-18 19:37
Try this using the default `condition-travis` plugin, but explicitly placed inside an array:
```
{
  "name": "hops",
  "description": "Hops",
  "main": "index.js",
  "dependencies": {
    "google-protobuf": "^3.4.0"
  },
  "scripts": {
    "test": "exit 0",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/private-org/hops.git"
  },
  "author": "Ro Ramtohul",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/private-org/hops/issues"
  },
  "homepage": "https://github.com/private-org/hops#readme",
  "publishConfig": {
    "access": "restricted"
  },
  "engines": {
    "node": "> 8.4.0"
  },
  "version": "0.0.1",
  "devDependencies": {
    "@semantic-release/condition-codeship": "^1.1.0",
    "semantic-release": "^8.2.0"
  },
  "release": {
    "verifyConditions": [
      "@semantic-release/condition-travis"
    ]
  }
}
```

Now, try the same without it being placed inside an array:

```
{
  "name": "hops",
  "description": "Hops",
  "main": "index.js",
  "dependencies": {
    "google-protobuf": "^3.4.0"
  },
  "scripts": {
    "test": "exit 0",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/private-org/hops.git"
  },
  "author": "Ro Ramtohul",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/private-org/hops/issues"
  },
  "homepage": "https://github.com/private-org/hops#readme",
  "publishConfig": {
    "access": "restricted"
  },
  "engines": {
    "node": "> 8.4.0"
  },
  "version": "0.0.1",
  "devDependencies": {
    "@semantic-release/condition-codeship": "^1.1.0",
    "semantic-release": "^8.2.0"
  },
  "release": {
    "verifyConditions": "@semantic-release/condition-travis"
  }
}
```

**Comment by pvdlg** [comment] 2017-10-18 20:09
Indeed I can reproduce. I will push a fix tonight !

**Comment by yoitsro** [comment] 2017-10-18 20:10
Good work 💪 Thank you!

**Comment by gr2m** [comment] 2017-10-18 21:07
@yoitsro can you please test with `semantic-release@8.2.1`? It has been released with the `@next` dist-tag, so you have to set that version explicitely. `npm install semantic-release` will still give you 8.2.0

**Comment by yoitsro** [comment] 2017-10-18 21:15
@gr2m This works 👌 Nice one!

**Comment by pvdlg** [comment] 2017-10-18 21:21
So `8.2.1` solves @yoitsro issue.
But I'm not sure about @dsslimshaddy issue.

@dsslimshaddy could you provide the information requested in this [comment](https://github.com/semantic-release/semantic-release/issues/406#issuecomment-330017446)

**Closed** 2017-11-21 05:39 UTC
