### ISSUE TITLE
Cannot finding repo id of organization repo?

### ISSUE THREAD

**Issue by IniZio** [semantic-release/semantic-release#542] opened 2017-12-02 04:55 UTC
I attempted `semantic-release-cli setup` on a organization repo, and filled the npm account and github account with my personal username. However it returns error that the repo id is not found. But if i try the setup on a personal repo it works fine.

**Comment by pvdlg** [comment] 2017-12-02 05:00
Does your user have write access to the repo?

**Comment by IniZio** [comment] 2017-12-02 05:13
Yes, I was the creator of the organizaion.

**Comment by pvdlg** [comment] 2017-12-02 05:14
Do you have more details about the error ? Could you copy and paste the output of the CLI.

**Comment by IniZio** [comment] 2017-12-03 02:59
My [package.json](https://github.com/clippedjs/clipped/blob/develop/package.json).

**Comment by pvdlg** [comment] 2017-12-03 03:12
What is the error you get from the CLI ?

**Comment by pvdlg** [comment] 2017-12-06 15:43
Duplicate of #380

**Closed by pvdlg** 2017-12-06 15:43 UTC
Labels: Awaiting response, CLI

**Comment by IniZio** [comment] 2017-12-08 15:20
Resolved by revoking and granting access github oauth for Travis. Thanks for the help :pray:
