### ISSUE TITLE
Unable to release when removing branches from configuration

### ISSUE THREAD

**Issue by priyajeet** [semantic-release/semantic-release#1355] opened 2019-11-14 02:43 UTC
Semantic release breaks with the following error if you change the branches configuration to remove some branches which may have been used prior for a release.

```
[6:09:08 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].
```

For example, if your release.config.js had something like
```
{
    branches: ['+([1-9])?(.{+([1-9]),x}).x', 'release', 'master', 'fubar'],
    ...
}
```
Say you release from the `fubar` branch. Next, if you change the config to get rid of that fubar branch:

```
{
    branches: ['+([1-9])?(.{+([1-9]),x}).x', 'release', 'master'],
    ...
}
```
and then try to release from say the `master` branch, then semantic release just breaks with the above error.

I am guessing it gets the git tags like `{ gitTag: 'SOMETAG', version: 'SOMEVERSION', channel: 'fubar' }`, and then tries to match the `channel` value to one of the values within the branches section of the config. A missing match causes a failure?

## Environment

- **semantic-release** version: 16.0.0-beta.31
- CI environment: Tried locally using --no-ci --dry-run
- Plugins used: Default ones, in the log below
- **semantic-release** configuration: https://github.com/box/box-ui-elements/blob/master/release.config.js
- CI logs:

```
$ node_modules/.bin/semantic-release --dry-run --no-ci --debug
[6:33:21 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.31
  semantic-release:config load config from: /Users/phora/buie/release.config.js +0ms
  semantic-release:config options values: { branches:
  semantic-release:config    [ '+([1-9])?(.{+([1-9]),x}).x',
  semantic-release:config      { name: 'master', prerelease: 'beta' } ],
  semantic-release:config   repositoryUrl: 'git@github.com:box/box-ui-elements.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins:
  semantic-release:config    [ '@semantic-release/release-notes-generator',
  semantic-release:config      [ '@semantic-release/commit-analyzer', [Object] ],
  semantic-release:config      [ '@semantic-release/npm', [Object] ],
  semantic-release:config      [ '@semantic-release/github', [Object] ] ],
  semantic-release:config   _: [],
  semantic-release:config   'dry-run': true,
  semantic-release:config   d: true,
  semantic-release:config   dryRun: true,
  semantic-release:config   ci: false,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': '/Users/phora/buie/node_modules/.bin/semantic-release',
  semantic-release:config   noCi: true } +3ms
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/verifyConditions: { failComment: false,
  semantic-release:plugins   failTitle: false,
  semantic-release:plugins   labels: false,
  semantic-release:plugins   releasedLabels: false,
  semantic-release:plugins   successComment: false } +2ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular',
  semantic-release:plugins   releaseRules: [ { type: 'chore', scope: 'i18n', release: 'patch' } ] } +1ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false } +6ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/publish: { failComment: false,
  semantic-release:plugins   failTitle: false,
  semantic-release:plugins   labels: false,
  semantic-release:plugins   releasedLabels: false,
  semantic-release:plugins   successComment: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/addChannel: { failComment: false,
  semantic-release:plugins   failTitle: false,
  semantic-release:plugins   labels: false,
  semantic-release:plugins   releasedLabels: false,
  semantic-release:plugins   successComment: false } +1ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/success: { failComment: false,
  semantic-release:plugins   failTitle: false,
  semantic-release:plugins   labels: false,
  semantic-release:plugins   releasedLabels: false,
  semantic-release:plugins   successComment: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/fail: { failComment: false,
  semantic-release:plugins   failTitle: false,
  semantic-release:plugins   labels: false,
  semantic-release:plugins   releasedLabels: false,
  semantic-release:plugins   successComment: false } +0ms
[6:33:22 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
  semantic-release:get-tags found tags for branch master: [ { gitTag: 'v0.38.0', version: '0.38.0', channel: undefined }, { gitTag: 'v0.39.0', version: '0.39.0', channel: undefined }, { gitTag: 'v0.40.0', version: '0.40.0', channel: undefined }, { gitTag: 'v0.41.0', version: '0.41.0', channel: undefined }, { gitTag: 'v0.42.0', version: '0.42.0', channel: undefined }, { gitTag: 'v0.43.0', version: '0.43.0', channel: undefined }, { gitTag: 'v0.44.0', version: '0.44.0', channel: undefined }, { gitTag: 'v0.45.0', version: '0.45.0', channel: undefined }, { gitTag: 'v1.0.0', version: '1.0.0', channel: undefined }, { gitTag: 'v1.0.1', version: '1.0.1', channel: undefined }, { gitTag: 'v1.0.2', version: '1.0.2', channel: undefined }, { gitTag: 'v1.1.0', version: '1.1.0', channel: undefined }, { gitTag: 'v1.2.0', version: '1.2.0', channel: undefined }, { gitTag: 'v1.2.1', version: '1.2.1', channel: undefined }, { gitTag: 'v1.2.2', version: '1.2.2', channel: undefined }, { gitTag: 'v1.3.0', version: '1.3.0', channel: undefined }, { gitTag: 'v1.3.1', version: '1.3.1', channel: undefined }, { gitTag: 'v1.4.0', version: '1.4.0', channel: undefined }, { gitTag: 'v1.4.1', version: '1.4.1', channel: undefined }, { gitTag: 'v1.5.0', version: '1.5.0', channel: undefined }, { gitTag: 'v1.5.1', version: '1.5.1', channel: undefined }, { gitTag: 'v1.5.2', version: '1.5.2', channel: undefined }, { gitTag: 'v1.6.0', version: '1.6.0', channel: undefined }, { gitTag: 'v1.6.1', version: '1.6.1', channel: undefined }, { gitTag: 'v10.0.0', version: '10.0.0', channel: undefined }, { gitTag: 'v10.0.0-beta.10@master', version: '10.0.0-beta.10', channel: 'master' }, { gitTag: 'v10.0.0-beta.11@master', version: '10.0.0-beta.11', channel: 'master' }, { gitTag: 'v10.0.0-beta.12@master', version: '10.0.0-beta.12', channel: 'master' }, { gitTag: 'v10.0.0-beta.13@master', version: '10.0.0-beta.13', channel: 'master' }, { gitTag: 'v10.0.0-beta.14@master', version: '10.0.0-beta.14', channel: 'master' }, { gitTag: 'v10.0.0-beta.15@master', version: '10.0.0-beta.15', channel: 'master' }, { gitTag: 'v10.0.0-beta.16@master', version: '10.0.0-beta.16', channel: 'master' }, { gitTag: 'v10.0.0-beta.17@master', version: '10.0.0-beta.17', channel: 'master' }, { gitTag: 'v10.0.0-beta.18@master', version: '10.0.0-beta.18', channel: 'master' }, { gitTag: 'v10.0.0-beta.19@master', version: '10.0.0-beta.19', channel: 'master' }, { gitTag: 'v10.0.0-beta.1@master', version: '10.0.0-beta.1', channel: 'master' }, { gitTag: 'v10.0.0-beta.20@master', version: '10.0.0-beta.20', channel: 'master' }, { gitTag: 'v10.0.0-beta.21@master', version: '10.0.0-beta.21', channel: 'master' }, { gitTag: 'v10.0.0-beta.22@master', version: '10.0.0-beta.22', channel: 'master' }, { gitTag: 'v10.0.0-beta.23@master', version: '10.0.0-beta.23', channel: 'master' }, { gitTag: 'v10.0.0-beta.24@master', version: '10.0.0-beta.24', channel: 'master' }, { gitTag: 'v10.0.0-beta.25@master', version: '10.0.0-beta.25', channel: 'master' }, { gitTag: 'v10.0.0-beta.2@master', version: '10.0.0-beta.2', channel: 'master' }, { gitTag: 'v10.0.0-beta.3@master', version: '10.0.0-beta.3', channel: 'master' }, { gitTag: 'v10.0.0-beta.4@master', version: '10.0.0-beta.4', channel: 'master' }, { gitTag: 'v10.0.0-beta.5@master', version: '10.0.0-beta.5', channel: 'master' }, { gitTag: 'v10.0.0-beta.6@master', version: '10.0.0-beta.6', channel: 'master' }, { gitTag: 'v10.0.0-beta.7@master', version: '10.0.0-beta.7', channel: 'master' }, { gitTag: 'v10.0.0-beta.8@master', version: '10.0.0-beta.8', channel: 'master' }, { gitTag: 'v10.0.0-beta.9@master', version: '10.0.0-beta.9', channel: 'master' }, { gitTag: 'v10.1.0', version: '10.1.0', channel: undefined }, { gitTag: 'v10.1.0-beta.1@master', version: '10.1.0-beta.1', channel: 'master' }, { gitTag: 'v10.1.0-beta.2@master', version: '10.1.0-beta.2', channel: 'master' }, { gitTag: 'v10.2.0', version: '10.2.0', channel: undefined }, { gitTag: 'v10.2.0-beta.1@master', version: '10.2.0-beta.1', channel: 'master' }, { gitTag: 'v10.2.0-beta.2@master', version: '10.2.0-beta.2', channel: 'master' }, { gitTag: 'v10.2.0-beta.3@master', version: '10.2.0-beta.3', channel: 'master' }, { gitTag: 'v10.2.0-beta.4@master', version: '10.2.0-beta.4', channel: 'master' }, { gitTag: 'v10.2.0-beta.5@master', version: '10.2.0-beta.5', channel: 'master' }, { gitTag: 'v10.2.0-beta.6@master', version: '10.2.0-beta.6', channel: 'master' }, { gitTag: 'v10.2.0-beta.7@master', version: '10.2.0-beta.7', channel: 'master' }, { gitTag: 'v11.0.0', version: '11.0.0', channel: undefined }, { gitTag: 'v11.0.0-beta.100@master', version: '11.0.0-beta.100', channel: 'master' }, { gitTag: 'v11.0.0-beta.101@master', version: '11.0.0-beta.101', channel: 'master' }, { gitTag: 'v11.0.0-beta.102@master', version: '11.0.0-beta.102', channel: 'master' }, { gitTag: 'v11.0.0-beta.103@master', version: '11.0.0-beta.103', channel: 'master' }, { gitTag: 'v11.0.0-beta.104@master', version: '11.0.0-beta.104', channel: 'master' }, { gitTag: 'v11.0.0-beta.10@master', version: '11.0.0-beta.10', channel: 'master' }, { gitTag: 'v11.0.0-beta.11@master', version: '11.0.0-beta.11', channel: 'master' }, { gitTag: 'v11.0.0-beta.12@master', version: '11.0.0-beta.12', channel: 'master' }, { gitTag: 'v11.0.0-beta.13@master', version: '11.0.0-beta.13', channel: 'master' }, { gitTag: 'v11.0.0-beta.14@master', version: '11.0.0-beta.14', channel: 'master' }, { gitTag: 'v11.0.0-beta.15@master', version: '11.0.0-beta.15', channel: 'master' }, { gitTag: 'v11.0.0-beta.16@master', version: '11.0.0-beta.16', channel: 'master' }, { gitTag: 'v11.0.0-beta.17@master', version: '11.0.0-beta.17', channel: 'master' }, { gitTag: 'v11.0.0-beta.18@master', version: '11.0.0-beta.18', channel: 'master' }, { gitTag: 'v11.0.0-beta.19@master', version: '11.0.0-beta.19', channel: 'master' }, { gitTag: 'v11.0.0-beta.1@master', version: '11.0.0-beta.1', channel: 'master' }, { gitTag: 'v11.0.0-beta.20@master', version: '11.0.0-beta.20', channel: 'master' }, { gitTag: 'v11.0.0-beta.21@master', version: '11.0.0-beta.21', channel: 'master' }, { gitTag: 'v11.0.0-beta.22@master', version: '11.0.0-beta.22', channel: 'master' }, { gitTag: 'v11.0.0-beta.23@master', version: '11.0.0-beta.23', channel: 'master' }, { gitTag: 'v11.0.0-beta.24@master', version: '11.0.0-beta.24', channel: 'master' }, { gitTag: 'v11.0.0-beta.25@master', version: '11.0.0-beta.25', channel: 'master' }, { gitTag: 'v11.0.0-beta.26@master', version: '11.0.0-beta.26', channel: 'master' }, { gitTag: 'v11.0.0-beta.27@master', version: '11.0.0-beta.27', channel: 'master' }, { gitTag: 'v11.0.0-beta.28@master', version: '11.0.0-beta.28', channel: 'master' }, { gitTag: 'v11.0.0-beta.29@master', version: '11.0.0-beta.29', channel: 'master' }, { gitTag: 'v11.0.0-beta.2@master', version: '11.0.0-beta.2', channel: 'master' }, { gitTag: 'v11.0.0-beta.30@master', version: '11.0.0-beta.30', channel: 'master' }, { gitTag: 'v11.0.0-beta.31@master', version: '11.0.0-beta.31', channel: 'master' }, { gitTag: 'v11.0.0-beta.32@master', version: '11.0.0-beta.32', channel: 'master' }, { gitTag: 'v11.0.0-beta.33@master', version: '11.0.0-beta.33', channel: 'master' }, { gitTag: 'v11.0.0-beta.34@master', version: '11.0.0-beta.34', channel: 'master' }, { gitTag: 'v11.0.0-beta.35@master', version: '11.0.0-beta.35', channel: 'master' }, { gitTag: 'v11.0.0-beta.36@master', version: '11.0.0-beta.36', channel: 'master' }, { gitTag: 'v11.0.0-beta.37@master', version: '11.0.0-beta.37', channel: 'master' }, { gitTag: 'v11.0.0-beta.38@master', version: '11.0.0-beta.38', channel: 'master' }, { gitTag: 'v11.0.0-beta.39@master', version: '11.0.0-beta.39', channel: 'master' }, { gitTag: 'v11.0.0-beta.3@master', version: '11.0.0-beta.3', channel: 'master' }, ... 155 more items ] +0ms
[6:33:23 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[6:33:23 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

{ AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Users/phora/buie/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (/Users/phora/buie/node_modules/semantic-release/lib/branches/index.js:42:19)
        at Array.reduce (<anonymous>)
        at module.exports (/Users/phora/buie/node_modules/semantic-release/lib/branches/index.js:32:46)
    at module.exports (/Users/phora/buie/node_modules/semantic-release/lib/branches/index.js:64:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pvdlg** [comment] 2019-11-14 16:53
The logs provided do not match with what you described.
In your issue description you say the error happens with the config `branches: ['+([1-9])?(.{+([1-9]),x}).x', 'release', 'master']` however in the logs your config is `branches: [ '+([1-9])?(.{+([1-9]),x}).x', { name: 'master', prerelease: 'beta' } ]`.

The config `branches: [ '+([1-9])?(.{+([1-9]),x}).x', { name: 'master', prerelease: 'beta' } ]` (the one from the logs) defines maintenances branches (`+([1-9])?(.{+([1-9]),x}).x`) and a prerelease branch (`prerelease: 'beta'`) but no release branch. Therefore the error you see is expected and accurately describe the problem in your config.

If you actually experience an issue with the config you described (`branches: ['+([1-9])?(.{+([1-9]),x}).x', 'release', 'master']`) please provide the logs and step to reproduce.

**Comment by pvdlg** [comment] 2019-11-14 16:58
> I am guessing it gets the git tags like { gitTag: 'SOMETAG', version: 'SOMEVERSION', channel: 'fubar' }, and then tries to match the channel value to one of the values within the branches section of the config. A missing match causes a failure?

No. The error `ERELEASEBRANCHES ` happens because your configuration is invalid. No tags involved here.

**Comment by priyajeet** [comment] 2019-11-14 23:32
My mistake of using fubar above as an example. This is what I tried

Starting off with

```
{
    branches: ['+([1-9])?(.{+([1-9]),x}).x', 'release', { name: 'master', prerelease: 'beta' }],
    ...
}
```

I did a release using the `release` branch. I then changed the config to be

```
{
    branches: ['+([1-9])?(.{+([1-9]),x}).x', { name: 'master', prerelease: false }],
    ...
}
```

because I had no need of the release branch. I now tried a release using master branch and it failed with the above error.

**Comment by pvdlg** [comment] 2019-11-15 17:08
You removed the release branch and ends up with only maintenance branches (`+([1-9])?(.{+([1-9]),x}).x`) and a prerelease branch (`{ name: 'master', prerelease: false }`). So the system tell you it's an invalid config and give you an error message explaining that.

What is the problem you are reporting? That semantic-release should work without a release branch? Or that the error is thrown incorrectly?
Because according to the information you provided the error is thrown appropriately and accurately describe the misconfiguration...

**Comment by pvdlg** [comment] 2019-11-20 21:12
There was an issue with `prerelease: false` that was fixed in https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0-beta.32%40beta

I assume this is what was causing your issue.

**Closed by pvdlg** 2019-11-20 21:12 UTC
Labels: info requested
