### ISSUE TITLE
If the repository referenced in package.json is a git@ URL, semantic-release creates an incorrect URL

### ISSUE THREAD

**Issue by tmcw** [semantic-release/semantic-release#404] opened 2017-07-27 17:20 UTC
From my package.json:

```json
"repository": {
    "type": "git",
    "url": "git@github.com:documentationjs/documentation.git"
  },
```

Setup output:

```
~/src/documentation〉semantic-release-cli setup
? Is the GitHub repository private? No
ERR! semantic-release Error: Could not access GitHub repository
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:98:13
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:191)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:361
ERR! semantic-release  { Error: Could not access GitHub repository
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:98:13
ERR! semantic-release     at Generator.next (<anonymous>)
ERR! semantic-release     at step (/usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:191)
ERR! semantic-release     at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:361
ERR! semantic-release   stack: 'Error: Could not access GitHub repository\n    at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:98:13\n    at Generator.next (<anonymous>)\n    at step (/usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:191)\n    at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/repository.js:27:361' }
```

After digging around and console.log'ing, what I see is that repository.js gets the URL `git@github.com:documentationjs/documentation.git` and then does `parsed.protocol = 'https';`, assigning it a https protocol, which creates the URL `https:git@github.com:documentationjs/documentation.git`, which isn't valid, which causes this crash.

Changing the URL in package.json to an HTTPS URL fixes the issue.

**Comment by pvdlg** [comment] 2017-12-16 22:25
Duplicate of semantic-release/cli#105

**Closed by pvdlg** 2017-12-16 22:25 UTC
Labels: bug, cli, help wanted
