### ISSUE TITLE
How to release backports of bug fixes?

### ISSUE THREAD

**Issue by sanderploegsma** [semantic-release/semantic-release#403] opened 2017-07-20 14:21 UTC
If I understand correctly, semantic-release will only ever work on a single branch (`master` mostly). But that leaves me wondering: how would you auto-release bugfixes in earlier releases? 

Let's say I have a package with two major versions: 1.x.x and 2.x.x. If I discover a bug in my code that was already present in the 1.x.x version, I would normally branch off of the latest 1.x.x tag, fix the bug and release a new 1.x.x version. As far as I can tell, semantic-release will only release a new 2.x.x version.

**Comment by gurpreetatwal** [comment] 2017-07-25 04:09
Check out this gist: https://gist.github.com/boennemann/54042374e49c7ade8910

**Comment by pvdlg** [comment] 2017-12-15 17:39
Duplicate of #563.

Feedback welcome in #563. Thanks !

**Comment by pvdlg** [comment] 2017-12-15 17:41
Feedback welcome in #563. Thanks !

**Closed by pvdlg** 2017-12-15 17:41 UTC
