### ISSUE TITLE
how to maintain two major versions at the same time?

### ISSUE THREAD

**Issue by faceyspacey** [semantic-release/semantic-release#371] opened 2017-03-16 17:50 UTC
For example, you have a `next` branch and you want to start publishing it to npm with the `dist-tag` `next` while still being able to publish minor/patch releases on your `latest` `dist-tag`.

Another example: you want to publish minor/patch releases to previous versions on NPM.

Is the recommended way to checkout a new `next` branch or create a branch from a previous tag, make the changes, and then publish to NPM ***directly***? Or is there a built-in mechanism? It seems, it won't be able to deploy from Travis if you push these changes to a separate remote branch as *semantic-release* only operates on one branch (typically `master`). So I can only conclude that *semantic-release* doesn't support this and you have to do it on your own. 

What's the idiomatic way to handle maintaining multiple concurrent "tracks"?

ps. If within Travis, semantic-release could operate on more than one branch, a nice feature would be that new versions are incremented from the tag you branched, and it notifies you if the new version exists already (thereby requiring you to checkout a previous tag with the highest patch number if, for example, you're making a `fix`).

**Comment by faceyspacey** [comment] 2017-03-16 17:53
This package itself seems to do this here:

https://github.com/semantic-release/semantic-release/releases?after=v6.2.0

where it goes back and forth from releases for the **4.0** track and the **6.0** track.

**Comment by faceyspacey** [comment] 2017-03-16 18:06
It seems I was correct about manually having to perform the publishes in these cases:

http://stackoverflow.com/questions/24691314/npm-publish-patch-for-earlier-major-version

But, taking, the `next` example, what happens when you eventually merge back into `master`? The `next` branch may have already bumped several patches and minor versions ahead when it registers as a breaking change--will *semantic-release* know to create its version major version incremented from there rather than at, e.g. *2.0.0*?

**Comment by gr2m** [comment] 2017-06-12 11:47
I think it would be great if semantic release could be configured to release new versions for previous major releases. Say my last version is 3.0.0. What I would do now is to branch out `v2.x` with the last version in the 2x release and in that branch configure `v2x` to be the branch from which it should release. But when I push a `feat: ...` commit, semantic-release does nothing because it is looking for the last commit of the last version which is `3.0.0` instead of the last commit in the current branch.

Another limitation would be that I would not want to allow to do breaking changes from this. I wonder if we could another option like `baseVersion` which would achieve both things – forbidding breaking changes and checking for the last commit in the right place?

**Comment by jedwards1211** [comment] 2017-09-15 19:10
To fix this `semantic-release` would just need to `git fetch` and then find last version tag in the history of the current branch, instead of the last release published to npm, right?

**Comment by jedwards1211** [comment] 2017-09-15 19:13
I think in addition to this, `semantic-release` should publish on the `vX` (where `X` is a past major version) branches by default as well.

**Comment by pvdlg** [comment] 2017-10-06 06:46
The scenario described in this [comment](https://github.com/semantic-release/semantic-release/issues/371#issuecomment-307766529) currently works, with the exception that we do not enforce the type of release allowed on a given branch/dist-tag.
 
Here in a configuration to support this scenario:
- git `2x` branch with code of version `2.0.0`, release on `2x` dist-tag
- git `master` branch, with code of version `3.0.0`, release on `latest` dist-tag
- git `next` branch with code of version `4.0.0`, release on `next` dist-tag

The `package.json` on branch `2x`:
```json
"release": {
  "branch": "2x"
},
"publishConfig": {
  "tag": "2x"
}
```
The `package.json` on branch `master`:
```json
"release": {
  "branch": "master"
},
"publishConfig": {
  "tag": "latest"
}
```
The `package.json` on branch `next`:
```json
"release": {
  "branch": "next"
},
"publishConfig": {
  "tag": "next"
}
```
With this config:
- A `fix` commit on `2x` branch would trigger the release `2.0.1` on dist-tag `2x`
- A `fix` commit on `master` branch would trigger the release `3.0.1` on dist-tag `latest`
- A `fix` commit on `next` branch would trigger the release `4.0.1` on dist-tag `next`

The scenario works, but there is still a few issues:
1. A breaking change commit on `2x` would trigger the release `3.0.0` on dist-tag `2x` and  fails as `3.0.0` already exist (not on the `2x` dist-tag but still npm would refuse the release)
2. Making `4.x.x` the new `latest` and `5.x.x` the new `next` is a manual process:
  - Create branch `3x` from `master`
  - Change the `package.json` on branch `3x` to `"publishConfig": {"tag": "3x"}"`
  - Run `npm dist-tag add <package>@<latest 3.x.x version> 3x` to move the last 3.x.x to the `3x` dist-tag
  - Run `npm dist-tag add <package>@<latest 4.x.x version> latest` to move the last 4.x.x to the `latest` dist-tag
  - Merge the `next` branch into `master` and change the `package.json` on branch `master` to `"publishConfig: {"tag": "latest"}, "release": {"branch": "master"}`

In order to solve 1 we could allow a new "branches" configuration that would define a list of branches and the version range we allow to release from them. With the initial example it would be:
```json
"release": {
  "branches": {
    "2x":  "2.x.x",
    "master":  "3.x.x",
    "next": "x.x.x"
  }
}
```
If a breaking change is pushed on the branch `2x` we would not do a release (because `3.0.0` is not in range `2.x.x`) and report an error to the user. We can even imagine doing that on a PR before it get merged.
We might even be able to do something a bit smarter for `master`, by allowing only releases that are inferior to the earliest version released on next not present on `latest` yet. That would require to configure somewhere that `master` < `next`.

Regarding 2, it's fairly complex and I'm sure everybody has some specificities in their workflow, so it will be hard to automate. Plus this process shouldn't have to be done too frequently as we can assume that a project maintaining old major version is probably not doing too many breaking changes. So maybe some documentation would be enough?

**Comment by pvdlg** [comment] 2017-12-15 17:42
Duplicate of #563

**Comment by pvdlg** [comment] 2017-12-15 17:42
Feedback welcome in #563. Thanks !

**Closed by pvdlg** 2017-12-15 17:42 UTC
