### ISSUE TITLE
Add a PR mode option for dry runs

### ISSUE THREAD

**Issue by darcy-rayner** [semantic-release/semantic-release#1091] opened 2019-01-31 22:16 UTC
## New feature motivation

Hi 👋, I'm currently trying to develop a plugin for [danger.js](https://danger.systems/js/) that outputs semantic-release changelog/version info directly to your PR. The issue I'm running into is that semantic-release requires you to have git push access during a dry run. I think for most CI/CD systems running PRs on open source projects, having write access at that point should be avoided, because it means anyone could modify the repository directly.

## New feature description

Add a new option to the Javascript API that disables the git push check steps, similar to the CI flag. Eg
```javascript
semanticRelease({
    dryRun: true,
    pr: true
});
```
This would disable any git push access checking steps and should only run when dryRun is true. The other thing the flag might need to do is change the current branch check, because PRs are usually run on headless commits.

If no one wants to take this on and you agree it's a good idea, I'm happy to implement this feature and submit a PR.

**Comment by pvdlg** [comment] 2019-02-01 20:54
Adding information to a PR about what semantic-release would release if that PR were merged is something we would like to implement. However, so far there is no good solution to do so. See #585.

As you mentioned the problem is that you have very limited access when running in PR build, in order to prevent someone to open a PR from a forked repo and leak sensitive info.

That mean you will have access to the GitHub token, so you won't be able to add a comment to the PR. So it seems what you are trying to achieve will not works.

At best it will be limited to PR opened from the same repo (as CI would provide the token via environment variable in that case) or for public repo only (adding a comment to the PR without a token). At that point, we don't make changes to support such feature with so many limitations. If we support it we would like to have no limitation (it should work for private repo and for PR coming from a fork). The solution that comes with the least compromises seems to be a GitHub app.

**Comment by darcy-rayner** [comment] 2019-02-01 21:41
I guess my assumption is the pull request is coming from within the same repository. I know a lot of CIs won't expose secrets to PRs coming from forked repositories, like Travis for example. Other CI systems let you lock secrets so they are only exposed during builds against certain branches, or not exposed to PRs. 

The setup I normally use is to have two github tokens. One token is locked down to just the public_repo scope on GitHub, which can't push to the repository at all but can leave comments on PRs, (which is what danger.js recommends). Then I typically have another github token with push access for semantic-release that is only exposed to builds running on master. On a closed source project, you can use just a single token with the full repo scope. https://danger.systems/js/guides/getting_started.html#setting-up-an-access-token .

**Comment by pvdlg** [comment] 2019-02-04 22:18
Having PRs coming from forked repo is extremely common. This is the large majority of PRs on many open source projects.
We won't make changes to support commenting on PRs if we can can't do it for all PRs, including ones that come from a forked repo. That would be extremely confusing for users to have a feature that "sometimes" works.

I'm gonna close this and invite you to comment further on #585 if you have a solution that would work for every cases we want to support.

**Closed by pvdlg** 2019-02-04 22:18 UTC

**Comment by rodoabad** [comment] 2019-08-08 00:18
@darcy-rayner where you at with your Danger plugin for semantic release?
