### ISSUE TITLE
Clean install throws deprecated errors

### ISSUE THREAD

**Issue by davemachado** [semantic-release/semantic-release#233] opened 2016-06-09 17:46 UTC
Trying to install with   `sudo npm install -g semantic-release-cli`throws errors:

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> keytar@3.0.2 install /usr/lib/node_modules/semantic-release-cli/node_modules/keytar
> node-gyp rebuild

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: /home/dmachado/.node-gyp/4.4.5/common.gypi not found (cwd: /usr/lib/node_modules/semantic-release-cli/node_modules/keytar) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/semantic-release-cli/node_modules/keytar
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "semantic-release-cli"
npm ERR! node v4.4.5
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

```

**Comment by davemachado** [comment] 2016-06-09 17:48
Could be similar to issue #229

**Comment by krysalead** [comment] 2016-09-05 15:04
Hi,

got the same running on Ubuntu 14.04.

**Comment by jhabdas** [comment] 2017-05-29 07:50
Dupe of #176. Please close this and be sure to search through closed issues in repos before opening new ones. Thanks!

**Comment by vanduynslagerp** [comment] 2017-10-01 17:33
Duplicate of #176

**Closed by vanduynslagerp** 2017-10-01 17:33 UTC
