### ISSUE TITLE
does debug option work through the API?

### ISSUE THREAD

**Issue by Aghassi** [semantic-release/semantic-release#1053] opened 2018-12-28 21:59 UTC
## Current behavior

Currently I am passing `debug: true` via the API call as it is a "core option". However, it doesn't do anything. If I pass the `DEBUG=semantic-release:*` before the call, it does work though.

Calling semantic-release this way does nothing. Note that `options` is an object with property `debug` which is a boolean:
```
    const result = await semanticRelease({
      ...options,
      // Extends the default config provided here
      extends: path.resolve(__dirname, '../config/release.config'),
    });
```

In addition, I don't see it checked in `index.js` at all https://github.com/semantic-release/semantic-release/blob/master/index.js#L155

## Expected behavior

I'd expect I can pass the `debug` option as an option to the API. If this is not the case, can this be clarified in the docs?

## Environment

- **semantic-release** version: 15.3.2 
- CI environment: N/A, local 
- Plugins used: changelog, git, github 
- **semantic-release** configuration: 
```
module.exports = {
  verifyConditions: [
    '@semantic-release/changelog',
    '@semantic-release/git',
    '@semantic-release/github',
  ],
  prepare: [
    '@semantic-release/changelog',
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'CHANGELOG.md', 'README.md', 'docs'],
    },
  ],
  publish: [
    {
      path: '@semantic-release/github',
      assets: [['dist']],
    },
  ],
  success: ['@semantic-release/github'],
  fail: ['@semantic-release/github'],
};

```

- CI logs: N/A

**Comment by pvdlg** [comment] 2018-12-28 22:37
Please the note in https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#debug

**Comment by pvdlg** [comment] 2018-12-28 22:37
Duplicate of #1019

**Closed by pvdlg** 2018-12-28 22:37 UTC
Labels: support
