### ISSUE TITLE
Gitlab CI

### ISSUE THREAD

**Issue by kbrandwijk** [semantic-release/semantic-release#597] opened 2018-01-07 03:26 UTC
I've seen some issues and PR's about supporting Gitlab similar to how Github is supported, but I have been unable to find anything related to supporting Gitlab CI. Is that somewhere on the roadmap?

**Comment by pvdlg** [comment] 2018-01-07 05:26
We have:
- [GitLab plugin](https://github.com/semantic-release/gitlab)
- [GitLab shareable config](https://github.com/semantic-release/gitlab-config)
- [GitLab CI recipe](https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/gitlab-ci.md)

There is 2 things here, GitLab the Git hosted repository (supported with the plugin and shareable config) and the GitLab CI.

The plugin make the release on GitLab (the Git hosted repo) similarly to what we do with GitHub.

Regarding CI support, there is nothing we have to do in semantic-release to support additional CI.

The only CI related stuff we do is:
- Check we are running on a CI
- Check it's not a PR build
- Check if we are on the proper branch

All that is done with [env-ci](https://github.com/pvdlg/env-ci).

**Comment by pvdlg** [comment] 2018-01-07 05:32
Do you mean support for the CLI?
Nothing is the roadmap. There is no much roadmap other than:
- Issue with the `design` label will be implemented once we agreed on the design
- Issues with `help wanted` are considered valid on ok to fix/implement

But that would be great if the CLI could generate something similar to what's in the [GitLab CI recipe](https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/gitlab-ci.md)

**Comment by pvdlg** [comment] 2018-01-08 04:59
Since semantic-release/cli#172 is open should we close this issue?

**Closed** 2018-01-08 15:12 UTC
Labels: cli

**Comment by cdaringe** [comment] 2018-05-07 21:41
@pvdlg, thx!  the `recipe` link doesn't specify the minimal set of configuration required in `package.json`.  im not 100% sure what it should be either.  any tips?

**Comment by cdaringe** [comment] 2018-05-07 21:51
ah, i dev installed `@semantic-release/gitlab-config` then added:

```json
  "release": {
    "extends": "@semantic-release/gitlab-config"
  }
```
to my `package.json` and blamo!  in business.  the issue is probably worth closing too, as aforementioned by @pvdlg

**Comment by pvdlg** [comment] 2018-05-08 02:52
This issue is related to the setup CLI (https://github.com/semantic-release/cli) and is already closed.

The `@semantic-release/gitlab-config` shareable config is also mentioned here: https://github.com/semantic-release/semantic-release/blob/caribou/docs/extending/shareable-configurations-list.md and in a FAQ: https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-use-semantic-release-with-gitlab.

The documentation of `@semantic-release/gitlab-config` contains the info related to its usage and configuration.
