### ISSUE TITLE
Script does not find the latest release

### ISSUE THREAD

**Issue by adrianschmidt** [semantic-release/semantic-release#833] opened 2018-06-27 13:57 UTC
## Current behavior

When fetching the latest release by tag from Github, semantic-release keeps finding the v1.0.0 tag, even though there are later releases (all made by semantic-release).

Since I am currently in the process of setting up the project, and don't have anyone using my releases yet, I've tried deleting the releases, as well as the tags from Github, but I keep getting the same behaviour. The first time I run the release script, it creates a tag `v1.0.0` on the commit that was the last commit when I first got semantic-release to work correctly with Github. Then it correctly makes a new release based on the commits since that one. But the next time I run the release script, it finds `v1.0.0` again, instead of the latest release that it just created (currently `v1.1.0`). Then it parses all the commits since `v1.0.0` and concludes that it should bump the minor version, bumps it to `v1.1.0` and then promptly fails when trying to push this new release to Github, since that tag already exists.

## Expected behavior

It should find the release of `v1.1.0`, and bump the version to `v1.2.0`.

## Environment

- **semantic-release** version: 15.6.1
- CI environment: Jenkins
- Plugins used: None, except for the built in `npm` and `github`, that are used by default.
- **semantic-release** configuration: In package.json: `"release": { "branch": "master", "debug": true }`
- CI logs:

```
[lime_lime-elements_master-BNNHCDJPBPTMZM3URF6ONQSA4FS6PQOTS4D4CWAKBMXFMHC7YKNA] Running shell script
+ make release
docker run --rm -e CI -e GH_TOKEN -e NPM_TOKEN -w /lime lime-elements npx semantic-release
[Semantic release]: Running semantic-release version 15.6.1
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/github
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/github
[Semantic release]: Load plugin "success" from @semantic-release/github
[Semantic release]: Load plugin "fail" from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry http://npm.lundalogik.com:4873/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Found git tag v1.0.0 associated with version 1.0.0
[Semantic release]: Found 15 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: feat(CI): dummy minor bump
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: chore(CI): try to get semantic-release to work correctly
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update access token used
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update Dockerfile
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update semantic-release
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: docs(README): Fix bad link formatting
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat(README): Improve readme

Also use the `feat` type to bump the minor version, to fix an
issue with semantic-release, probably caused by force-pushing to
master.
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: docs(README): Add commit message guidelines
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore: Uppercase readme file
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: fix(CI): Debug flag removed
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: CHANGELOG.md no longer needed

Changelog is now found on each release in Github.
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: The docker build no longer runs the npm build
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: fix(semantic-release): Pass env-vars to container
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: fix(semantic-release): Fixes bug in Makefile
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: fix(semantic-release): Fixes for npm publish

Run `npm publish` in the correct environment when releasing.
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analysis of 15 commits complete: minor release
[Semantic release]: The next release version is 1.1.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 1.1.0 to package.json
[Semantic release]: Wrote version 1.1.0 to package-lock.json
[Semantic release]: Create tag v1.1.0
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master
To https://[secure]@github.com/Lundalogik/lime-elements.git
 ! [rejected]        v1.1.0 -> v1.1.0 (already exists)
error: failed to push some refs to 'https://[secure]@github.com/Lundalogik/lime-elements.git'
hint: Updates were rejected because the tag already exists in the remote.


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://[secure]@github.com/Lundalogik/lime-elements.git\n ! [rejected]        v1.1.0 -> v1.1.0 (already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/Lundalogik/lime-elements.git\'\nhint: Updates were rejected because the tag already exists in the remote.\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master',
  timedOut: false,
  killed: false }
{ Error: Command failed: git push --tags https://****@github.com/Lundalogik/lime-elements.git HEAD:master
To https://****@github.com/Lundalogik/lime-elements.git
 ! [rejected]        v1.1.0 -> v1.1.0 (already exists)
error: failed to push some refs to 'https://****@github.com/Lundalogik/lime-elements.git'
hint: Updates were rejected because the tag already exists in the remote.


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://****@github.com/Lundalogik/lime-elements.git\n ! [rejected]        v1.1.0 -> v1.1.0 (already exists)\nerror: failed to push some refs to \'https://****@github.com/Lundalogik/lime-elements.git\'\nhint: Updates were rejected because the tag already exists in the remote.\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://****@github.com/Lundalogik/lime-elements.git HEAD:master',
  timedOut: false,
  killed: false }
Makefile:15: recipe for target 'release' failed
make: *** [release] Error 1
```

I assume this is probably not a bug, but something I'm doing wrong, but I haven't been able to find what, so any ideas are highly appreciated.

**Comment by adrianschmidt** [comment] 2018-06-27 14:01
The CI log above doesn't match the description of expected behaviour perfectly, since the only new commit since `v1.1.0` is actually a `chore`. But I'm adding a dummy `feat` commit now, and will be updating with the new output.

**Comment by pvdlg** [comment] 2018-06-27 14:22
semantic-release look only for tags that reference a commit in the history of the current branch. Maybe those tags were created on a different branch?

What is the output of `git tag --merged master`?

Can you run semantic-release with the `--debug` option? Or set the environment variable `DEBUG` to `semantic-release:*`?

**Comment by adrianschmidt** [comment] 2018-06-27 14:33
```
$ git tag --merged master
v1.0.0
v1.1.0
```

I had set the debug flag in package.json, but perhaps that didn't work. I'll add it as a command line flag instead.

Could the issue be caused by doing rebase-commits in GitHub? I can't see how, since it doesn't change what's on the master branch, but I thought I'd ask…

**Comment by pvdlg** [comment] 2018-06-27 14:37
What do you get with `git merge-base --is-ancestor v1.1.0 HEAD`? I would the console output if there is one and the exit code? You can get the exit code of the last command with `echo $?`.

**Comment by adrianschmidt** [comment] 2018-06-27 14:42
That doesn't seem to output anything…

```
╭16:40:28 ~/src/lime-elements [master]
╰$ git tag
v1.0.0
v1.1.0

╭16:40:30 ~/src/lime-elements [master]
╰$ git merge-base --is-ancestor v1.1.0 HEAD

╭16:40:34 ~/src/lime-elements [master]
╰$ echo $?
0

╭16:40:37 ~/src/lime-elements [master]
╰$ git merge-base --is-ancestor v1.0.0 HEAD

╭16:40:44 ~/src/lime-elements [master]
╰$ echo $?
0
```

I'll get you the debug-log soon. I just need to double-check that there are no access tokens or any other accidents in it :)

**Comment by adrianschmidt** [comment] 2018-06-27 14:43
Debug log:

```
npm build', gitTags: '', committerDate: 2018-06-27T08:24:38.000Z }, { commit: { long: '9343c360d160b4b457e7c1074206a1d84a51a161', short: '9343c36' }, tree: { long: '37227e18decabe4eb5f85c1e97e4ccae677c52eb', short: '37227e1' }, author: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T08:03:36.000Z }, committer: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T08:18:29.000Z }, subject: 'fix(semantic-release): Pass env-vars to container', body: '', hash: '9343c360d160b4b457e7c1074206a1d84a51a161', message: 'fix(semantic-release): Pass env-vars to container', gitTags: '', committerDate: 2018-06-27T08:18:29.000Z }, { commit: { long: '4faf38a139ad82042d659a4c5be52ec547599558', short: '4faf38a' }, tree: { long: '7dfac8bcaf5174335f80289a3d1d6c67f559b97e', short: '7dfac8b' }, author: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T07:44:04.000Z }, committer: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T07:44:04.000Z }, subject: 'fix(semantic-release): Fixes bug in Makefile', body: '', hash: '4faf38a139ad82042d659a4c5be52ec547599558', message: 'fix(semantic-release): Fixes bug in Makefile', gitTags: '', committerDate: 2018-06-27T07:44:04.000Z }, { commit: { long: 'feaca628147a40bde2bade552d3dee01467b678e', short: 'feaca62' }, tree: { long: 'a192174daaa8e1fa51b67fc13cc778314af6df4e', short: 'a192174' }, author: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T07:36:56.000Z }, committer: { name: 'Adrian Schmidt', email: 'adrian.schmidt@lime.tech', date: 2018-06-27T07:41:17.000Z }, subject: 'fix(semantic-release): Fixes for npm publish', body: 'Run `npm publish` in the correct environment when releasing.\n', hash: 'feaca628147a40bde2bade552d3dee01467b678e', message: 'fix(semantic-release): Fixes for npm publish\n\nRun `npm publish` in the correct environment when releasing.', gitTags: '', committerDate: 2018-06-27T07:41:17.000Z } ]
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: feat(CI): dummy minor bump plus debug flag
2018-06-27T14:40:12.653Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.654Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: feat(CI): dummy minor bump
2018-06-27T14:40:12.654Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.656Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: chore(CI): try to get semantic-release to work correctly
2018-06-27T14:40:12.657Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update access token used
2018-06-27T14:40:12.657Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update Dockerfile
2018-06-27T14:40:12.657Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(CI): update semantic-release
2018-06-27T14:40:12.658Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: docs(README): Fix bad link formatting
2018-06-27T14:40:12.658Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat(README): Improve readme

Also use the `feat` type to bump the minor version, to fix an
issue with semantic-release, probably caused by force-pushing to
master.
2018-06-27T14:40:12.659Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.659Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: docs(README): Add commit message guidelines
2018-06-27T14:40:12.660Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore: Uppercase readme file
2018-06-27T14:40:12.660Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: fix(CI): Debug flag removed
2018-06-27T14:40:12.661Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.661Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: CHANGELOG.md no longer needed

Changelog is now found on each release in Github.
2018-06-27T14:40:12.661Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: The docker build no longer runs the npm build
2018-06-27T14:40:12.662Z semantic-release:commit-analyzer Analyzing with default rules
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: fix(semantic-release): Pass env-vars to container
2018-06-27T14:40:12.662Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.662Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: fix(semantic-release): Fixes bug in Makefile
2018-06-27T14:40:12.662Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.663Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analyzing commit: fix(semantic-release): Fixes for npm publish

Run `npm publish` in the correct environment when releasing.
2018-06-27T14:40:12.663Z semantic-release:commit-analyzer Analyzing with default rules
2018-06-27T14:40:12.663Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analysis of 16 commits complete: minor release
[Semantic release]: The next release version is 1.1.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator version: '1.1.0'
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator host: 'github.com'
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator owner: 'Lundalogik'
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator repository: 'lime-elements'
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator previousTag: 'v1.0.0'
2018-06-27T14:40:12.673Z semantic-release:release-notes-generator currentTag: 'v1.1.0'
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 1.1.0 to package.json
[Semantic release]: Wrote version 1.1.0 to package-lock.json
[Semantic release]: Create tag v1.1.0
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master
To https://[secure]@github.com/Lundalogik/lime-elements.git
 ! [rejected]        v1.1.0 -> v1.1.0 (already exists)
error: failed to push some refs to 'https://[secure]@github.com/Lundalogik/lime-elements.git'
hint: Updates were rejected because the tag already exists in the remote.


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://[secure]@github.com/Lundalogik/lime-elements.git\n ! [rejected]        v1.1.0 -> v1.1.0 (already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/Lundalogik/lime-elements.git\'\nhint: Updates were rejected because the tag already exists in the remote.\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master',
  timedOut: false,
  killed: false }
{ Error: Command failed: git push --tags https://****@github.com/Lundalogik/lime-elements.git HEAD:master
To https://****@github.com/Lundalogik/lime-elements.git
 ! [rejected]        v1.1.0 -> v1.1.0 (already exists)
error: failed to push some refs to 'https://****@github.com/Lundalogik/lime-elements.git'
hint: Updates were rejected because the tag already exists in the remote.


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://****@github.com/Lundalogik/lime-elements.git\n ! [rejected]        v1.1.0 -> v1.1.0 (already exists)\nerror: failed to push some refs to \'https://****@github.com/Lundalogik/lime-elements.git\'\nhint: Updates were rejected because the tag already exists in the remote.\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://****@github.com/Lundalogik/lime-elements.git HEAD:master',
  timedOut: false,
  killed: false }
Makefile:15: recipe for target 'release' failed
make: *** [release] Error 1
```

**Comment by adrianschmidt** [comment] 2018-06-27 14:52
Here's a screenshot of the releases in Github, in case that is of any help:

![screenshot](https://user-images.githubusercontent.com/154725/41981950-762bd4fa-7a2a-11e8-8f71-65a3a07e52d3.png)

**Comment by pvdlg** [comment] 2018-06-27 14:54
Can you provide the beginning of the logs? That's the useful part to troubleshoot this issue.

**Comment by adrianschmidt** [comment] 2018-06-27 15:02
Updated the debug-log in my comment above. Apparently Jenkins had cut a part when I checked the logs for just the relevant build step. I found the rest when I looked at the complete console output.

**Comment by pvdlg** [comment] 2018-06-27 15:04
From the logs:
> semantic-release:get-last-release found tags: [ { gitTag: 'v1.0.0', version: '1.0.0' } ]

This is the result of the `git tag` command.
That means the tag `v1.1.0` is not present in your local clone on your CI.

**Comment by adrianschmidt** [comment] 2018-06-27 15:08
Ah, ok! I think that might have something to do with us running this in docker. I'm sure the image is being cached or something. I'll try adding a fetch somewhere in the pipe. Thanks!

**Closed** 2018-06-27 15:08 UTC

**Comment by pvdlg** [comment] 2018-06-27 15:30
For info semantic-release runs `git fetch --unshallow --tags` before running `git tag`.
So it seems a fetch is not enough and the problem is somewhere else.

**Comment by adrianschmidt** [comment] 2018-06-28 07:58
Ah. I found out Jenkins doesn't check out tags by default.

To fix the issue, I had to add an "Advanced Clone Behaviours" entry in the "Behaviours" in the Project Configuration, and have the "Fetch tags" option checked.

Now releases work just fine! Thanks for creating this awesome tool!

**Comment by Nargonath** [comment] 2019-03-14 16:30
For anyone coming from Google I had the same problem with GitLab. If you go in your CI/CD settings of your repository you can switch to using `git clone` from `git fetch` for cloning the repo in your pipelines and it just fixed the problem for us.
