### ISSUE TITLE
Missing tags on repo cloned by GitLab CI

### ISSUE THREAD

**Issue by joelnet** [semantic-release/semantic-release#1410] opened 2020-01-14 01:40 UTC
I'm running this from gitlab ci/cd and having problems with a repo. The odd thing is other repos with the same .gitlab-ci.yml settings are running just fine.

semantic-release deployed a few versions successfully and then broke. semantic-release appears to be attempting write over an existing tag.

Some things about the repo:

- all tags have been created by semantic-release
- tags have not been added or removed
- there are no branches, only master
- there are some empty commits
- no rebase or rewriting of history

package.json settings:

```javascript
{
  "repository": {
    "type": "ssh",
    "url": "git@gitlabdev.paciolan.info:development/library/javascript/react/remote-components/evenue-v2-hello-world-component.git"
  },
  "release": {
    "branch": "master",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/exec",
        {
          "publishCmd": "./scripts/publish.sh ${nextRelease.version}"
        }
      ]
    ]
  }
}
```

```
$ git tag
v1.0.0
v1.0.1
v1.0.2
v1.1.0
$ git rev-list -1 v1.1.0
0f97f330745e6067dacf8908184ea8c5f2742fc0
$ echo $?
0
```

Running with the command:

```
npx semantic-release
```

Then I see this log from semantic-release:

```
[1:15:30 AM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch master
```

and finally this:

```
fatal: tag 'v1.1.0' already exists
```

I'm a little lost as to what to check next.

**Comment by pvdlg** [comment] 2020-01-14 16:25
@lgaticaq please provide the information I requested in https://github.com/semantic-release/semantic-release/issues/1410#issuecomment-573965569 otherwise I can't troubleshoot.

**Comment by lgaticaq** [comment] 2020-01-14 17:52
In master branch
```bash
git branch --contains v17.13.0
  build/xxxx
  ci/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
* master
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
```
```bash
git branch --contains v17.12.0
  build/xxxx
  ci/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
  feature/xxxx
* master
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
  renovate/xxxx
```

**Comment by pvdlg** [comment] 2020-01-14 17:54
What's your complete semantic-release configuration?
Did you use any v16.0.0-beta version on this repo?
Can you run semantic-release with --debug and provide the output?

**Comment by lgaticaq** [comment] 2020-01-14 18:02
What's your complete semantic-release configuration?
```js
{
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/gitlab',
    'semantic-release-gitlab-registry',
    'semantic-release-rancher'
  ]
}
```
Did you use any v16.0.0-beta version on this repo?
Packages with errors:
- @semantic-release/changelog v3.0.4
- @semantic-release/git v8.0.0
- @semantic-release/gitlab v4.0.0
- semantic-release v16.0.1
- semantic-release-gitlab-registry v2.2.1
- semantic-release-rancher v2.0.2

Packages without errors:
- @semantic-release/changelog v3.0.4
- @semantic-release/git v7.0.16
- @semantic-release/gitlab v4.0.0
- semantic-release v15.14.0
- semantic-release-gitlab-registry v2.2.1
- semantic-release-rancher v2.0.2

Can you run semantic-release with --debug and provide the output?
I can't. I rollback semantic-release dependencies to trigger mi new release, sorry

**Comment by pvdlg** [comment] 2020-01-14 18:42
v16.0.0 uses the command `git tag --merged <branch>` to find the version tag. For some reason your tags `v17.12.0` and `v17.13.0` seems to not be retrieved by this command. I guess they must have something specific. Any idea what? Are they retrieved by `git tag --merged <branch>` on your CI?

**Comment by joelnet** [comment] 2020-01-14 18:46
> Is the tag in the history of the branch? You can verify that with `git branch --contains v1.1.0`.

```
$ git branch --contains v1.1.0
* (HEAD detached at 023a136)
```
also

```
$ git rev-list -1 v1.1.0
0f97f330745e6067dacf8908184ea8c5f2742fc0
$ echo $?
0
```

```bash
$ npx semantic-release --debug
npx: installed 870 in 22.581s
[6:42:45 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.1
2020-01-14T18:42:45.320Z semantic-release:config load config from: /builds/development/library/javascript/react/remote-components/evenue-v2-hello-world-component/package.json
2020-01-14T18:42:45.326Z semantic-release:config options values: { branches:
   [ '+([0-9])?(.{+([0-9]),x}).x',
     'master',
     'next',
     'next-major',
     { name: 'beta', prerelease: true },
     { name: 'alpha', prerelease: true } ],
  repositoryUrl:
   'git@gitlabdev.paciolan.info:development/library/javascript/react/remote-components/evenue-v2-hello-world-component.git',
  tagFormat: 'v${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     [ '@semantic-release/exec', [Object] ] ],
  branch: 'master',
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/66/bin/semantic-release' }
2020-01-14T18:42:45.626Z semantic-release:plugins options for @semantic-release/exec/verifyConditions: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
2020-01-14T18:42:45.628Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-01-14T18:42:45.628Z semantic-release:plugins options for @semantic-release/exec/analyzeCommits: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
2020-01-14T18:42:45.629Z semantic-release:plugins options for @semantic-release/exec/verifyRelease: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
2020-01-14T18:42:45.629Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-01-14T18:42:45.630Z semantic-release:plugins options for @semantic-release/exec/generateNotes: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
2020-01-14T18:42:45.630Z semantic-release:plugins options for @semantic-release/exec/prepare: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
2020-01-14T18:42:45.630Z semantic-release:plugins options for @semantic-release/exec/publish: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
2020-01-14T18:42:45.631Z semantic-release:plugins options for @semantic-release/exec/addChannel: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
2020-01-14T18:42:45.631Z semantic-release:plugins options for @semantic-release/exec/success: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
2020-01-14T18:42:45.631Z semantic-release:plugins options for @semantic-release/exec/fail: { publishCmd: './scripts/publish.sh ${nextRelease.version}' }
[6:42:45 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
2020-01-14T18:42:48.183Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] } ]
[6:42:48 PM] [semantic-release] › ✔  Run automated release from branch master
[6:42:48 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:42:48 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[6:42:48 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[6:42:48 PM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch master
2020-01-14T18:42:48.998Z semantic-release:get-commits Use from: 1eafe7df9a8f7aa07eb759baeeb9d0e0f49fe881
[6:42:49 PM] [semantic-release] › ℹ  Found 8 commits since last release
2020-01-14T18:42:49.028Z semantic-release:get-commits Parsed commits: [ { commit: { long: '8c0bdbe9e6dba31eddf215958119dead06e64651', short: '8c0bdbe' }, tree: { long: '84a2f52c1dc1b9dcc93a95d6b6b7ef62f0745f5a', short: '84a2f52' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T18:39:23.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T18:39:23.000Z }, subject: 'fix: 🐛 add semantic-release debug', body: '', hash: '8c0bdbe9e6dba31eddf215958119dead06e64651', committerDate: 2020-01-14T18:39:23.000Z, message: 'fix: 🐛 add semantic-release debug', gitTags: '(HEAD, origin/master)' }, { commit: { long: '023a136fa68a570d3a7bdac2d7ebf067d995715f', short: '023a136' }, tree: { long: '45665905f4968a823fc8a3fefdcdabd3158c7b86', short: '4566590' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T18:24:35.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T18:24:35.000Z }, subject: 'fix: 🐛 debugging for semantic-release', body: '', hash: '023a136fa68a570d3a7bdac2d7ebf067d995715f', committerDate: 2020-01-14T18:24:35.000Z, message: 'fix: 🐛 debugging for semantic-release', gitTags: '' }, { commit: { long: '23c4f6296041a64a2f46ef81fe61624efbee81f2', short: '23c4f62' }, tree: { long: '862f68cf6b1a805e39ae7fed29e59dd451219472', short: '862f68c' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:13:14.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:13:14.000Z }, subject: 'fix: 🐛 add debug code', body: '', hash: '23c4f6296041a64a2f46ef81fe61624efbee81f2', committerDate: 2020-01-14T01:13:14.000Z, message: 'fix: 🐛 add debug code', gitTags: '' }, { commit: { long: 'b52ce64d22f3ed09fab034049dabce887b1e034c', short: 'b52ce64' }, tree: { long: '8f9b7e59d942e28b1932419ae7126d175fecace4', short: '8f9b7e5' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:09:40.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:09:40.000Z }, subject: 'fix: 🐛 bump version', body: '', hash: 'b52ce64d22f3ed09fab034049dabce887b1e034c', committerDate: 2020-01-14T01:09:40.000Z, message: 'fix: 🐛 bump version', gitTags: '' }, { commit: { long: '0f97f330745e6067dacf8908184ea8c5f2742fc0', short: '0f97f33' }, tree: { long: 'ee317eaab47abdbe2463720d9bb529b08528ae12', short: 'ee317ea' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:03:48.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T01:03:48.000Z }, subject: 'feat: ✨ semantic-release sucks', body: '', hash: '0f97f330745e6067dacf8908184ea8c5f2742fc0', committerDate: 2020-01-14T01:03:48.000Z, message: 'feat: ✨ semantic-release sucks', gitTags: '(tag: v1.1.0)' }, { commit: { long: '4e507e4acab4f49a436094bcde55dba2099e43c7', short: '4e507e4' }, tree: { long: '8f9b7e59d942e28b1932419ae7126d175fecace4', short: '8f9b7e5' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:55:01.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:55:01.000Z }, subject: 'fix: 🐛 attempt to bump', body: '', hash: '4e507e4acab4f49a436094bcde55dba2099e43c7', committerDate: 2020-01-14T00:55:01.000Z, message: 'fix: 🐛 attempt to bump', gitTags: '' }, { commit: { long: 'd64875ebd3a9b2a9cdef2a7a0bf670cd6080d9a3', short: 'd64875e' }, tree: { long: '3e2ee24c4cf3f24dbb9cd5644fe823d56c7ba1b1', short: '3e2ee24' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:47:46.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:47:46.000Z }, subject: 'fix: 🐛 delete junk files', body: '', hash: 'd64875ebd3a9b2a9cdef2a7a0bf670cd6080d9a3', committerDate: 2020-01-14T00:47:46.000Z, message: 'fix: 🐛 delete junk files', gitTags: '' }, { commit: { long: 'e8f118d87ee510f11d9d739b723d0ded24dcf62a', short: 'e8f118d' }, tree: { long: '8f9b7e59d942e28b1932419ae7126d175fecace4', short: '8f9b7e5' }, author: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:44:56.000Z }, committer: { name: 'Joel Thoms', email: 'jthoms@paciolan.com', date: 2020-01-14T00:44:56.000Z }, subject: 'fix: 🐛 update .gitlab-ci.yml', body: '', hash: 'e8f118d87ee510f11d9d739b723d0ded24dcf62a', committerDate: 2020-01-14T00:44:56.000Z, message: 'fix: 🐛 update .gitlab-ci.yml', gitTags: '(tag: v1.0.2)' } ]
[6:42:49 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 add semantic-release debug
2020-01-14T18:42:49.049Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.052Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 debugging for semantic-release
2020-01-14T18:42:49.052Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.053Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 add debug code
2020-01-14T18:42:49.053Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.053Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 bump version
2020-01-14T18:42:49.054Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.054Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: ✨ semantic-release sucks
2020-01-14T18:42:49.054Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.055Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 attempt to bump
2020-01-14T18:42:49.055Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.055Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 delete junk files
2020-01-14T18:42:49.056Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.056Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: 🐛 update .gitlab-ci.yml
2020-01-14T18:42:49.057Z semantic-release:commit-analyzer Analyzing with default rules
2020-01-14T18:42:49.057Z semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch'
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:42:49 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 8 commits complete: minor release
[6:42:49 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:42:49 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ℹ  The next release version is 1.1.0
[6:42:49 PM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator version: '1.1.0'
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator host: undefined
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator owner: 'development'
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator repository: 'library/javascript/react/remote-components/evenue-v2-hello-world-component'
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator previousTag: 'v1.0.1'
2020-01-14T18:42:49.087Z semantic-release:release-notes-generator currentTag: 'v1.1.0'
2020-01-14T18:42:49.088Z semantic-release:release-notes-generator host: 'https://gitlabdev.paciolan.info'
2020-01-14T18:42:49.088Z semantic-release:release-notes-generator host: 'https://gitlabdev.paciolan.info'
2020-01-14T18:42:49.088Z semantic-release:release-notes-generator linkReferences: undefined
2020-01-14T18:42:49.088Z semantic-release:release-notes-generator issue: 'issues'
2020-01-14T18:42:49.088Z semantic-release:release-notes-generator commit: 'commit'
[6:42:49 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:42:49 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/exec"
[6:42:49 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed with exit code 128: git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651
fatal: tag 'v1.1.0' already exists
    at makeError (/root/.npm/_npx/66/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/root/.npm/_npx/66/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 128: git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651',
  command: 'git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: tag \'v1.1.0\' already exists',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
{ Error: Command failed with exit code 128: git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651
fatal: tag 'v1.1.0' already exists
    at makeError (/root/.npm/_npx/66/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/root/.npm/_npx/66/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 128: git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651',
  command: 'git tag v1.1.0 8c0bdbe9e6dba31eddf215958119dead06e64651',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: tag \'v1.1.0\' already exists',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
ERROR: Job failed: exit code 1
```

**Comment by joelnet** [comment] 2020-01-14 19:00
local:

```
$ git --version
git version 2.17.1

$ git tag --merged master
v1.0.0
v1.0.1
v1.0.2
v1.1.0
```

local:

```
$ git --version
git version 2.15.3

$ git tag --merged master
v1.0.0
v1.0.1
```

**Comment by joelnet** [comment] 2020-01-14 19:37
After downgrading to semantic-release 15, the pipeline ran successfully.

```
npx semantic-release@15
```

There seems to be some kind of bug with `git tag --merged master`. I can't seem to track down the cause because even running that same docker image locally works just fine.

**Comment by pvdlg** [comment] 2020-01-14 19:42
I don't think so. The problem is related to the way your CI clone the repo. It seems it create a detached head and don't clone other branches.
That's why we call the following code in semantic-release:
https://github.com/semantic-release/semantic-release/blob/3739ab5f34454321aad2bf36f3a5ec03da004d33/lib/git.js#L95

But it seems this code fails to retrieve all the tags in all the branches.

What CI are you using? Can you try to find out what exact `git` command the CI runs to clone the repo and create the detached head?

**Comment by joelnet** [comment] 2020-01-14 19:58
I also tried checking out the repo with a detached head locally and everything still worked for me.

I'm using Gitlab Pipelines. I don't see what command is being run, but these are the logs from the top of the run:

```
Running with gitlab-runner 11.9.0 (692ae235)
  on Shared Runner 36445d86
Using Docker executor with image paciolanhub/alpine-node-dev:10.15.4 ...
Pulling docker image paciolanhub/alpine-node-dev:10.15.4 ...
Using docker image sha256:2b54f214125e38f6a77a7998893b8eb8850d33a6420f406de9a00da6b823fe9e for paciolanhub/alpine-node-dev:10.15.4 ...
Running on runner-36445d86-project-1370-concurrent-0 via gitlab06...
Reinitialized existing Git repository in /builds/development/library/javascript/react/remote-components/evenue-v2-hello-world-component/.git/
Fetching changes with git depth set to 50...
fatal: remote origin already exists.
Removing coverage/
Removing dist/
Removing node_modules/
Clean repository
Checking out 7ea6df8f as master...

Skipping Git submodules setup
```

**Comment by joelnet** [comment] 2020-01-14 20:34
> It seems it create a detached head and don't clone other branches.

So it does look like it creates a detached head, but there are no other branches. The commit history has been linear.

**Comment by pvdlg** [comment] 2020-01-14 20:34
Can you give the output of the following commands on your CI, **after** the git cloning and **before** semantic-release runs?

- `git rev-parse master`
- `echo $GITLAB_CI`
- `echo $CI_COMMIT_REF_NAME`

**Comment by pvdlg** [comment] 2020-01-14 20:52
As an additional test can you run the following on your CI and provide the output, still after the git clone and before semantic-release:
- `git fetch --tags --update-head-ok origin +refs/heads/master:refs/heads/master}`
- `git tag --merged master`

**Comment by joelnet** [comment] 2020-01-14 21:04
```
$ git rev-parse master
1eafe7df9a8f7aa07eb759baeeb9d0e0f49fe881
$ echo $GITLAB_CI
true
$ echo $CI_COMMIT_REF_NAME
master
```

**Comment by joelnet** [comment] 2020-01-14 22:18
```bash
$ git fetch --tags --update-head-ok origin +refs/heads/master:refs/heads/master
From https://gitlabdev.paciolan.info/development/library/javascript/react/remote-components/evenue-v2-hello-world-component
   695e08e..c60a4e3  master     -> master
$ git tag --merged master
v1.0.0
v1.0.1
v1.0.2
v1.1.0
v1.1.1
```

**Comment by pvdlg** [comment] 2020-01-14 22:29
Ok I see. GitLab CI has a very weird way to handle to cloning of the repo. It seems it creates a detached head, but it also keep a cache of the repo.
So the following happens:
- On first run:
  - GitLab init a new repo, set the origin, fetch and then checkout the commit that is being built
  - semantic-release runs, find out `master` doesn't exist locally and runs `git fetch --tags origin` to creates it
  - All the tags are there and everything works fine
- More commit are added
- On second run:
  - GitLab re-use the repo in cache (with a now outdated `master`)
  -  semantic-release runs, find out `master`  exist locally and assumes the CI did it cloned it and it's up to date
  - semantic-release missed the last changes

Not really sure how to handle that. We could simply run always `git fetch --tags --update-head-ok origin +refs/heads/master:refs/heads/master` so it would update the outdated cache. However just updating the branch like that could have impact in other situation....I have to take time to think about it more....

In the meantime maybe there is aa way for you to disable that behavior in GitLab CI and to not re-use the outdated cached repo...

**Comment by joelnet** [comment] 2020-01-14 23:31
Okay, I have changed the `GIT_STRATEGY` to `clone`. The pipeline is continuing to work. 

I don't know if it will get into that broken state again, or if it's "fixed fixed".

I also do not know how to recreate that broken state.

**Comment by lgaticaq** [comment] 2020-01-15 14:26
Fixed pipelines with semantic-release v16. I set `GIT_STRATEGY: clone` in `.gitlab-ci.yml` :tada:. Thanks @joelnet and @pvdlg :clap:

**Closed** 2020-01-15 18:43 UTC
Labels: bug, third-party

**Comment by joelnet** [comment] 2020-01-16 00:32
@pvdlg, Thanks for taking the time to look at this issue. I really do appreciate the work you've done. Thanks again!

**Comment by ekson73** [comment] 2021-01-13 00:28
Hi,

changing the "Shallow Clone" to zero (0), solved the problem.

https://docs.gitlab.com/ee/ci/pipelines/settings.html#git-strategy
