### ISSUE TITLE
Minor releases after 15.4.4 are incompatible with Git v1

### ISSUE THREAD

**Issue by domwashburn** [semantic-release/semantic-release#1003] opened 2018-11-28 16:14 UTC
## Current behavior

Upgrading from 15.4.4 to 15.12.2 breaks Travis builds due to Git version incompatibility. 

In Travis log:
``` bash
[22:06:32] [semantic-release] › ℹ  Running semantic-release version 15.12.2
[semantic-release]: Git version 2.0.0 is required. Found 1.8.5.
```

## Expected behavior
To avoid issues with builds in Travis environments, minor releases should maintain backwards compatibility for older versions of Git.

If that is not an option, a Git incompatibility may need to be released as a major version.

## Environment

- **semantic-release** version: 15.12.2 
- CI environment: Travis (Enterprise) 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs: Can't Post logs, running in an enterprise environment

**Comment by domwashburn** [comment] 2018-11-28 16:15
possibly related to #720

**Comment by pvdlg** [comment] 2018-11-28 16:52
Actually semantic-release (at least since version `15.0.0`) was never really compatible with Git < 2.0.0. But before `15.4.4` we were not explicitly checking the Git version.

Only a few Git commands we are using are not compatible with Git < 2.0.0, So it could give the "impression" that it was working but in reality it was working only under certain circumstances where those incompatible command were not called.

**Comment by domwashburn** [comment] 2018-11-28 17:12
Got it, I guess I'm still a little confused as to why I've been able to successfully build in a Travis environment before then.

Is there a version I can use that is compatible with Git < 2.0.0?

**Comment by pvdlg** [comment] 2018-11-28 17:18
I don't remember exactly which command is not compatible with Git < 2.0.0, but I remember that the general case works.
I can't guarantee there is any version fully compatible with Git < 2.0.0.

The problem is that there is no way to know command is supported in which version of Git below 2.0.0.
In the [git documentation](https://git-scm.com/docs/git-fetch) you can select the version on the top of the page to figure which command/option are available in which versions. But it never goes beyond 2.0.0.

You are probably better off upgrading to a more recent version as it's really and safe easy to do.
Using an old version semantic-release is not recommended as you will experience bugs for sure.

**Comment by domwashburn** [comment] 2018-11-28 17:44
Thanks @pvdlg

After a little investigation, a colleague recommended that I add `dist: xenial` to `.travis.yml`... seems like an esoteric solution considering that Git v2.0.0 was released over 4 years ago ([2014-05-28](https://en.wikipedia.org/wiki/Git))

For anyone else that encounters this issue, here's a link to the doc that helped me out.

https://docs.travis-ci.com/user/reference/xenial/

**Comment by pvdlg** [comment] 2018-11-28 18:09
I don't think you have to define a specific image on Travis. We are using the default one and the git version is > 2.0.0.

**Comment by pvdlg** [comment] 2018-11-28 18:10
I'll close this issue as it seems it's resolved.

**Closed by pvdlg** 2018-11-28 18:10 UTC
