### ISSUE TITLE
Can't create a 2.x release

### ISSUE THREAD

**Issue by jakobrosenberg** [semantic-release/semantic-release#1606] opened 2020-07-29 08:30 UTC
## Current behavior

Creating a `feat: ...` commit and pushing it to branch `2.x` produces an 
```
EINVALIDNEXTVERSION The release `1.10.0` on branch `2.x` cannot be published as it is out of range.
```

Creating a `feat: ...` commit and pushing it to branch `next-major` bumps release to next minor.

## Expected behavior
Either method should create a tagged 2.x release

## Environment

- **semantic-release** version: 17.1.1
- CI environment: Github actions
- Plugins used: defaults
- **semantic-release** configuration: None, using defaults.
- CI logs: https://pastebin.com/U2q6bxFS

**Comment by jakobrosenberg** [comment] 2020-08-11 15:30
Tried `Breaking change`, but that didn't help either. Seems like there's nothing I can do to release a new major.

**Comment by gr2m** [comment] 2020-08-11 16:08
> 2020-07-29T07:48:35.0127447Z [7:48:35 AM] [semantic-release] › ℹ  Found git tag v1.9.7 associated with version 1.9.7 on branch 2.x

Sounds like the the 2.x branch does not include any 2.x release tags?

**Comment by jakobrosenberg** [comment] 2020-08-11 16:16
Thanks for your reply @gr2m. What would be the correct way to handle this, If I'm looking to release a tagged release? Doesn't matter if it's `next`, `next-master`, `beta`, `2.x` etc.

**Comment by jakobrosenberg** [comment] 2020-08-11 16:22
Getting closer. I think :/

```
This test run was triggered on the branch refs/tags/2.x, while semantic-release is configured to only publish from 2.x, master, therefore a new version won’t be published.
```

**Comment by jakobrosenberg** [comment] 2020-08-11 16:31
"Progress" can be seen here. https://github.com/roxiness/routify/issues/243#issuecomment-672072385

**Comment by gr2m** [comment] 2020-08-11 16:59
I'm sorry my comment was unclear. You shoudln't have a tag with the name `2.x`, that should be the branch name. But when you checkout the `2.x` branch.

Try this:

```
git checkout 2.x
git tag --merged HEAD
```

Now check the output, I think it doesn't include any tags such as `v2.0.0`, `v2.1.0`, etc. But it should

To fix the problem, create a backup of the current `v2.x` branch locally, so you don't loose any of your work

```
git checkout 2.x
git checkout -b 2.x-backup
```

Now delete the `2.x` branch locally, then recreated it based on the latest `v2.**` tag you have, e.g. if it is `v2.3.4`, do the following

```
git checkout -b 2.x v2.3.4
```

Now rebase your new `2.x` branch on top of `2.x-backup`

```
git rebase 2.x-backup
```

Then overwrite the current `2.x` branch on github with your local one

**Comment by jakobrosenberg** [comment] 2020-08-11 17:51
I'm a little confused. As you suspected, there's no `v2.**` tag, so how will I recreate `2.x` based on the latest tag `v2.**`? My latest tags are `v1.9.7` and the `2.x` I created earlier.

At the moment I have `master` and `2.x-backup` branches.

**Comment by gr2m** [comment] 2020-08-11 18:18
Ah I see. You shouldn't create a 2.x at all then. These branches are meant for maintenance realeses. So when your current release is 3.0.0 but you want to fix a bug in your 2.x.x release, you create a `2.x` branch and make the fix there

I'll close the issue as semantic-release is working as intended, but feel free to continue to comment if you have more questions

**Closed by gr2m** 2020-08-11 18:18 UTC

**Comment by jakobrosenberg** [comment] 2020-08-11 18:56
Thanks for the clarification @gr2m 

Is the only way to bump the major version to introduce a breaking change?

I tried a `next-major` branch, but it just bumped the minor, so I wasn't sure what the difference is between `next-major` and `next`.

**Comment by gr2m** [comment] 2020-08-11 19:01
> Is the only way to bump the major version to introduce a breaking change?

Yes, that is the point :) Why would you want to introduce a breaking version otherwise?
