### ISSUE TITLE
semantic-release takes a very long time to complete

### ISSUE THREAD

**Issue by bryanlarsen** [semantic-release/semantic-release#1345] opened 2019-11-01 14:18 UTC
## Current behavior

Semantic-release works, but it takes a long time.   (>35 minutes, currently).

We've got a cronjob set up to delete old branches and tags, which helps a lot, but it's not enough.   We currently have 65 branches and 460 tags on the repository.   That doesn't seem particularly excessive given that we have a dozen developers pushing multiple times per day.

## Expected behavior

Semantic-release should complete in a reasonable period of time.

## Environment

- **semantic-release** version: 16.0.0-beta.27
- CI environment: gitlab
- Plugins used:  `npm install -g @semantic-release/changelog@3.0.5 @semantic-release/git@7.1.0-beta.7 @semantic-release/gitlab@4.0.3 semantic-release@16.0.0-beta.27 @semantic-release/release-notes-generator@7.3.2 @semantic-release/commit-analyzer@7.0.0-beta.4`
- configuration:

```
{
  "branches": [
    "+([0-9])?(.{+([0-9]),x}).x",
    "master",
    { "name": "!(master)[a-z]*([a-z0-9-])", "prerelease": "${name.replace(/@.*/, '')}" }
  ],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "angular",
        "releaseRules": [
          { "breaking": true, "release": "major" },
          { "revert": true, "release": "patch" },
          { "type": "feat", "release": "minor" },
          { "type": "fix", "release": "patch" },
          { "type": "perf", "release": "patch" },
          { "type": "chore", "release": "patch" }
        ]
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/npm", { "npmPublish": false }],
    "@semantic-release/gitlab"
  ]
}
```

semantic-release --debug:

```
[8:49:17 AM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.27
  semantic-release:config load config from: /work/threekit/app/.releaserc.json +0ms
  semantic-release:config options values: { branches:
  semantic-release:config    [ '+([0-9])?(.{+([0-9]),x}).x',
  semantic-release:config      'master',
  semantic-release:config      { name: '!(master)[a-z]*([a-z0-9-])', prerelease: true } ],
  semantic-release:config   repositoryUrl: 'git+ssh://gitlab.com/threekit/app',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins:
  semantic-release:config    [ [ '@semantic-release/commit-analyzer', [Object] ],
  semantic-release:config      '@semantic-release/release-notes-generator',
  semantic-release:config      '@semantic-release/changelog',
  semantic-release:config      [ '@semantic-release/npm', [Object] ],
  semantic-release:config      '@semantic-release/gitlab' ],
  semantic-release:config   _: [],
  semantic-release:config   debug: true,
  semantic-release:config   '$0': 'semantic-release' } +3ms
  semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {} +0ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false } +2ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {} +0ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular',
  semantic-release:plugins   releaseRules:
  semantic-release:plugins    [ { breaking: true, release: 'major' },
  semantic-release:plugins      { revert: true, release: 'patch' },
  semantic-release:plugins      { type: 'feat', release: 'minor' },
  semantic-release:plugins      { type: 'fix', release: 'patch' },
  semantic-release:plugins      { type: 'perf', release: 'patch' },
  semantic-release:plugins      { type: 'chore', release: 'patch' } ] } +1ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +1ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/changelog/prepare: {} +0ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false } +1ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false } +0ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/gitlab/publish: {} +1ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
  semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false } +0ms
[8:49:17 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[8:49:17 AM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
  semantic-release:get-tags found tags: [ { gitTag: 'v1.0.0', version: '1.0.0', channel: undefined }, ...
 657 more items ] +40s
  semantic-release:get-tags found tags for branch access-tokens-service-v2: [ { , ... 66 more items ] +59s
  semantic-release:get-tags found tags for branch add-script: [ { ... } ] +1m
...
```

**Comment by pvdlg** [comment] 2019-11-01 15:23
Could you provide the full log? I would like to try to figure out which steps take so much time.

We have to unshallow the repo (downloading all the branches, tags and commits) in order to figure out what commits were added where. This might be what's take time.
We also have to find the tags and figure out which one is in the release branch history. That might take time as well, even though those operation are done locally.

If we have more info about which of those step takes time we might be able to make some optimisations or at least make some recommendations.

**Comment by bryanlarsen** [comment] 2019-11-01 15:28
There are 65 lines like the last two in my log, and they all have timestamps between "+30s" and "2m"

**Comment by pvdlg** [comment] 2019-11-01 15:29
You mean the lines like `semantic-release:get-tags found tags for branch access-tokens-service-v2` each 30s to 2m?

**Comment by bryanlarsen** [comment] 2019-11-01 15:29
I'll start another run to get you a full log, but it'll take several hours to complete.  It takes 35 minutes to run in our CI system, but that doesn't have '--debug'.   Running locally takes about 4 hours.

**Comment by bryanlarsen** [comment] 2019-11-01 15:29
> You mean the lines like semantic-release:get-tags found tags for branch access-tokens-service-v2 each 30s to 2m?

yes

**Comment by pvdlg** [comment] 2019-11-01 15:35
Did you experienced the same slowness with version 15? Or is it related only to the beta?

**Comment by bryanlarsen** [comment] 2019-11-01 15:38
We never used 15.   The preview capabilities of 16 are a big part of the reason why we adopted semantic-release.

**Comment by bryanlarsen** [comment] 2019-11-01 15:38
And we adopted it on an almost-empty repo: it was fast then.  :)

**Comment by pvdlg** [comment] 2019-11-01 15:40
Why configuring the branches with `!(master)[a-z]*([a-z0-9-])`?
That seems to match a a lot of branches....actually all of them....
That's the main reason why it so slow because for each branch that match that pattern we hate to look at all the tags and filter out the tags not in the branch history.

**Comment by bryanlarsen** [comment] 2019-11-01 16:27
Review apps.   https://about.gitlab.com/blog/2019/04/19/progressive-delivery-using-review-apps/

**Comment by pvdlg** [comment] 2019-11-01 16:42
We didn't really design v16 with something like that in mind. The goal was to have a limited number of branches....something like `master`, `next`, `beta` and maybe `alpha`...

Why keeping all the branches once they are merged? The problem is that each branch that match your glob will add to the load of work to do because we need to know the exact state of each release branches....When you have 65 branches that mean figuring out which tags are in the history of each one of those branches....

Currently we retrieve all the tags and for each one we check if they are in the branch history. We might be able to do that with `git tag --merged <branch>` but I think we had to move away from that as certain version of git were not compatible. I'd have to do more research on that.

I also don't know what the performance of `git tag --merged <branch>` are.
Can you run `git tag --merged <branch>` on one of your branch and let me know how long it takes?

In any case, even if we can make performance improvements, I would recommend to not keep that many branches that match the release branch glob...

**Comment by bryanlarsen** [comment] 2019-11-01 16:46
We are deleting all fully merged branches daily in a cronjob.

**Comment by bryanlarsen** [comment] 2019-11-01 16:47
$ time git tag --merged master > /dev/null

real	0m0.046s
user	0m0.029s
sys	0m0.016s

**Comment by pvdlg** [comment] 2019-11-01 16:47
So we moved away from in `git tag --merged <branch>` https://github.com/semantic-release/git/commit/ddaf44c48259fd561c05b4c373ec71bcb23ae118 becsaue it's not supported until Git 2.7.0.

We might have to bump the minimum version of Git we require for other reason anyway...So I guess that's possible to go back to `git tag --merged <branch>`.

**Comment by pvdlg** [comment] 2019-11-01 16:51
That seems pretty fast.

Can you also time `git merge-base --is-ancestor <release_tag> <release_branch>`?
Can you try it with a tag that is in the history of the branch and with a tag that exist but that is not in the history of that branch?

**Comment by bryanlarsen** [comment] 2019-11-01 16:56
blarsen@boom:/work/threekit/app$ time git merge-base --is-ancestor v1.10.0-draggable-upgrade.7@draggable-upgrade draggable-upgrade ; echo $? 

real	0m0.004s
user	0m0.004s
sys	0m0.000s
0
blarsen@boom:/work/threekit/app$ time git merge-base --is-ancestor v1.10.0-draggable-upgrade.7@draggable-upgrade master ; echo $?

real	0m0.013s
user	0m0.013s
sys	0m0.001s
1

**Comment by bryanlarsen** [comment] 2019-11-01 17:00
worst case:  $ time git merge-base --is-ancestor v1.0.0 draggable-upgrade ; echo $?

real	0m0.028s
user	0m0.028s
sys	0m0.001s
0

**Comment by pvdlg** [comment] 2019-11-01 17:38
So at worst it's going to be 0.028s * 460 per branch.
I guess we can use `git tag --merged <branch>` again and require Git `>=2.7.0`. That would help solve https://github.com/semantic-release/git/issues/155 as well. @gr2m what do you think?

In any case I would still recommend to not keep that many branches that match a release branch glob.

**Comment by gr2m** [comment] 2019-11-01 17:43
I'm always in favor of bumping required versions if it makes maintaining the project easier, it's hard enough already. We can release a breaking version and if anyone wants to keep maintaining the older versions because they depend on an outdated git, they are welcome to. In most cases these are enterprises anyway :)

**Comment by pvdlg** [comment] 2019-11-01 17:44
Well we would do that in v16 only as it's not really impactful in v15.

**Comment by gr2m** [comment] 2019-11-01 18:19
I'd suggest we do it then, and add the required git version bump to the list of breaking changes

**Comment by pvdlg** [comment] 2019-11-01 20:53
This will be implemented in #1347.

As mentioned before I still recommend to cut down on the number of branches you keep in your repo that match a release branch glob. Having so many branches to go through will slow down semantic-release even with the perf improvement in #1347.

**Closed** 2019-11-01 20:59 UTC

**Comment by pvdlg** [comment] 2019-11-01 21:00
Closing as it's probably the best we can to improve the situation.

Please report back here to let us know if there was improvement and how long does it takes now to run semantic-release. Thanks!

**Comment by bryanlarsen** [comment] 2019-11-02 14:56
```
[2:10:52 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:12:34 PM] [semantic-release] › ✔  Run automated release from branch epic-test-1@epic-test`
```

was >30 minutes, now  102 seconds.    Thanks greatly!
