### ISSUE TITLE
Trailing .git in release and changelog URLs causes 404

### ISSUE THREAD

**Issue by ethanneff** [semantic-release/semantic-release#970] opened 2018-11-02 05:33 UTC
## Current behavior

The URLs in the Changelog and Release recently broke. They now have `.git` prepended in the URL. I have no idea what caused them to break.

URL examples in these files redirect to a 404:
https://github.com/ethanneff/accomplish/blob/master/CHANGELOG.md
https://github.com/ethanneff/accomplish/releases

You can see the URLs were working before:
https://github.com/ethanneff/accomplish/blame/master/CHANGELOG.md#L36

Then, they stopped working once `.git` was added to them:
https://github.com/ethanneff/accomplish/blame/master/CHANGELOG.md#L29

## Expected behavior

URLs to not 404.

## Environment

- **semantic-release** version: 15.10.6
- CI environment: Travis CI
- Plugins used: git, github, changelog
- **semantic-release** configuration: https://github.com/ethanneff/accomplish/blob/master/package.json#L33-L48

**Comment by pvdlg** [comment] 2018-11-02 17:38
This bug is already fixed in [release-notes-generator@7.1.3](https://github.com/semantic-release/release-notes-generator/releases/tag/v7.1.3).

**Comment by pvdlg** [comment] 2018-11-02 17:38
Duplicate of #969

**Closed by pvdlg** 2018-11-02 17:38 UTC
