### ISSUE TITLE
This test run is not the build leader and therefore a new version won’t be published.

### ISSUE THREAD

**Issue by cacothi** [semantic-release/semantic-release#347] opened 2016-12-21 22:33 UTC
Hey Guys,

I'm getting the following message when push it to trevis:

This test run is not the build leader and therefore a new version won’t be published.

What does it means? the test is running successfully

**Comment by armand1m** [comment] 2017-02-04 01:59
i'm getting this same issue on travis ci, this job shows it better for further details: https://travis-ci.org/armand1m/generate-random-points/jobs/198233123

**Comment by Khaledgarbaya** [comment] 2017-02-27 10:27
I am having the same issue. I did publish the package manually but still failing in the next pushes

**Comment by armand1m** [comment] 2017-02-27 23:28
Apparently it just seems like the library will wait until the master build leader resolves the CI cycle, so when it is done, it does publish the package. Probably this feature is implemented in order to avoid publish the package more than once. Would be nice to see it in docs. (I did not has searched but never has seen before either so, if it exists, someone post the link here please.)

**Comment by Khaledgarbaya** [comment] 2017-02-28 10:06
Yeah, that was the issue thanks a lot. But what if I want to release a specific version that is not the leader like currently I am testing using node 6 and 7 and I want to release only in v6 because it is.

**Comment by jy95** [comment] 2017-08-23 19:16
Still the case .. Any news about this ?

I am using semantic-release 7.0.2 and Travis CI.

my .travis.yml
```yml
language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```

**Comment by vanduynslagerp** [comment] 2017-09-17 04:45
`semantic-release` `8.0.0` requires Node > 8 so you need to have at least 1 of your job running on node 8. The node 8 job will always be considered the build leader.

For example with this `travis.yml`:
```yaml
node_js:
  - '8'
  - '6'
  - '4'
```
- The node 8 job will be the build leader, run `semantic-release`, wait for the other jobs to be successful and publish on NPM
- On the Node 4 and 6 jobs `semantic-release` just output the message `This test run is not the build leader and therefore a new version won’t be published` and do nothing else.

This is the intended behavior as we want to publish only once.

For information, publishing with node 4, 6 or 8 doesn't make any difference. Your npm package is published all the same.
`semantic-release` enforce using node 8 to publish as it allows to use the latest node 8 feature in `semantic-release` source code without having to transpile.

**Comment by calebeby** [comment] 2017-09-17 15:21
My node 8 build was not set as build leader: https://travis-ci.org/calebeby/transform-pkg/jobs/276423918

**Comment by vanduynslagerp** [comment] 2017-09-17 15:46
@calebeby, I think this is because you are using old version of `condition-travis` and `travis-deploy-once`. See [here](https://github.com/calebeby/transform-pkg/blob/master/yarn.lock#L4057) in your `yarn.lock`.

This is because you updated your `package.json` without updating your `yarn.lock`.
Either remove `yarn.lock` from your repo, or install/update dependencies with the `yarn` cli and commit the changes in `yan.lock`.

**Comment by calebeby** [comment] 2017-09-17 16:27
I regenerated the `yarn.lock` and the problem persists: https://travis-ci.org/calebeby/transform-pkg/jobs/276549917

**Comment by jy95** [comment] 2017-09-17 16:40
@calebeby Check my .travis.yml on my repository https://github.com/jy95/torrent-files-library

Maybe do a npm i -g npm@latest ?

**Comment by vanduynslagerp** [comment] 2017-09-17 16:47
@calebeby, everything seems ok in your config, and I don't understand the problem yet.
I will try to fork your repo, reproduce and add more logs to figure out.
Before that, could you try to run `semantic-release` with `npm` instead of `yarn`, just to be sure it's not a `yarn` specific issue.

**Comment by calebeby** [comment] 2017-09-17 16:52
Hm. None of them are being set as build leader: https://travis-ci.org/calebeby/transform-pkg/builds/276554973

**Comment by gr2m** [comment] 2017-09-17 17:16
thank you all for helping figuring this out 👍 
@calebeby could you try to replace `npx -p node@8 npm run semantic-release` with just `npm run semantic-release`? I’ve run into a different problem with npx myself the other day: https://github.com/semantic-release/semantic-release/pull/414#issuecomment-330004885 I don’t know how `npx` works exactly and if it screws with `process.env` which could cause both problems

**Comment by calebeby** [comment] 2017-09-17 19:55
https://travis-ci.org/calebeby/transform-pkg/builds/276596249

**Comment by gr2m** [comment] 2017-09-17 20:00
could you add this to your travis file?

```
after_install:
  - npm ls
```

so we can see what exact versions have been installed?

Another problem could also be the caching of `node_modules`. The npm folks themselves don’t recommend to do that anymore, and instead cache  `$HOME/.npm`. I know our CLI is currently setting up `.travis.yml` to cache `node_modules`, something we should change asap :)

**Comment by calebeby** [comment] 2017-09-17 20:20
https://travis-ci.org/calebeby/transform-pkg/jobs/276604452

**Comment by gr2m** [comment] 2017-09-17 20:26
All right thanks Caleb, we’ll need to investigate this some more. Your build is using the latest version of [travis-deploy-once](https://github.com/semantic-release/travis-deploy-once) so there must be  a bug in it. If you could help us finding the cause of the problem, that’d be great 🙏

**Comment by calebeby** [comment] 2017-09-17 21:11
I switched to using build stages, and that worked. I think I'll stick to that.

**Comment by gr2m** [comment] 2017-09-18 03:19
I’ve just run into this problem myself, this is very weird, because I’m quite sure it worked before :( I’ll try to reproduce it on a minimal test setup

**Comment by vanduynslagerp** [comment] 2017-09-18 03:20
The Travis API might have change? Or respond differently ?

**Comment by gr2m** [comment] 2017-09-18 03:22
I don’t know, but I'm pretty sure it’s a problem is related to https://github.com/semantic-release/travis-deploy-once/releases#2.0.0

**Comment by ahmadnassri** [comment] 2017-09-20 15:03
seeing the same issue here: https://travis-ci.org/ahmadnassri/nightwatch-accessibility/jobs/277788548#L517

**Comment by gr2m** [comment] 2017-09-21 02:14
fixed via https://github.com/semantic-release/travis-deploy-once/pull/12, released as [`travis-deploy-once@2.0.2`](https://github.com/semantic-release/travis-deploy-once/releases/tag/v2.0.2). Make sure to update your lock files if you have them in your repositories.

All @vanduynslagerp work 👏 Please give it a try and let us know if it fixes your problems

**Comment by vanduynslagerp** [comment] 2017-09-21 02:15
It should be fixed by https://github.com/semantic-release/travis-deploy-once/pull/12

The issue was happening if the node version is specified as `number` rather than a `string`.
For example `node_js: '8'` and `node_js: 8` was not.

Now that the fix is published it will work no matter is the version is defined as a string or a number.
As FYI, the node version can also be defined like this `node_js: node` which indicate to Travis to use the latest stable version.

Could test again and let us if everything works ?

**Comment by calebeby** [comment] 2017-09-21 02:37
https://travis-ci.org/calebeby/transform-pkg

Thanks, this worked for me! Good work!

**Closed** 2017-09-30 18:10 UTC
