### ISSUE TITLE
Semantic Release no longer writing git notes

### ISSUE THREAD

**Issue by wkaskie** [semantic-release/semantic-release#3009] opened 2023-10-12 16:15 UTC
### Current behavior

During the release process, the prior notes are read, the new version is determined, but the notes are not created. Therefore, the next release throws an error given the prior version has no notes.

### Expected behavior

When creating a new version, git notes are updated with the { chanells: [] } information.

### `semantic-release` version

19.0.0

### CI environment

GitLab

### Plugins used

    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/commit-analyzer": "^9.0.2",
    "@semantic-release/exec": "^6.0.3",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/gitlab": "^9.3.2",
    "@semantic-release/npm": "^9.0.1",
    "@semantic-release/release-notes-generator": "^10.0.3",
    "semantic-release-plus": "^20.0.0",

### `semantic-release` configuration

```js
const name = '<hidden>';
const path = `apps/${name}`;
const artifactName = name;

module.exports = {
  branches: [
    { name: `ga/${name}` },
    { name: `release/${name}`, prerelease: 'rc' },
    { name: 'main', prerelease: 'beta' },
  ],
  name: name,
  dryRun: false,
  pkgRoot: `dist/${path}`,
  tagFormat: artifactName + '-v${version}',
  commitPaths: [
    'force-release.md',
    `${path}/*`,
    ...require('../../tools/semantic-release/get-dependent-paths.js').getDependentPaths(
      name
    ),
  ],
  assets: [`${path}/README.md`, `${path}/CHANGELOG.md`],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogFile: `${path}/CHANGELOG.md`,
      },
    ],
    [
      '@semantic-release/exec',
      {
        prepareCmd: `yarn nx format --all`,
        // this will be used by the deployment job for uploading assets to s3
        verifyReleaseCmd:
          'mkdir -p versions && echo v${nextRelease.version} > versions/${appName}.version.txt',
      },
    ],
    [
      '@semantic-release/gitlab',
      {
        successComment:
          '🎉 This issue has been resolved in version ${nextRelease.version} of ${appname} 🎉\n\nThe release is available on GitLab release',
      },
    ],
    [
      '@semantic-release/git',
      {
        assets: [`${path}/CHANGELOG.md`],
        message:
          `chore(release): ${artifactName}` +
          '-v${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
  ],
  releaseRules: [
    { type: 'ga', release: 'minor' }, // tag ga releases in order to trigger bump in minor version eg. 3.10.2 => 3.11.0
    { type: 'chore', release: 'patch' },
    { type: 'feat', release: 'patch' },
    { type: 'refactor', release: 'patch' },
    { type: 'fix', release: 'patch' },
    { type: 'ci', release: 'patch' },
  ],
};
```

### CI logs

TRUNCATED

```
, { gitTag: 'our-app-v1.6.6', version: '1.6.6', channels: [ null ] }, { gitTag: 'our-app-v1.6.7', version: '1.6.7', channels: [ null ] }, { gitTag: 'our-app-v1.7.0', version: '1.7.0', channels: [ null ] }, { gitTag: 'our-app-v1.7.1', version: '1.7.1', channels: [ null ] }, { gitTag: 'our-app-v1.7.2', version: '1.7.2', channels: [ null ] }, { gitTag: 'our-app-v1.8.0', version: '1.8.0', channels: [ null ] }, { gitTag: 'our-app-v1.8.1', version: '1.8.1', channels: [ null ] }, { gitTag: 'our-app-v1.8.2', version: '1.8.2', channels: [ null ] }, { gitTag: 'our-app-v1.8.3', version: '1.8.3', channels: [ null ] }, { gitTag: 'our-app-v1.8.4', version: '1.8.4', channels: [ null ] }, { gitTag: 'our-app-v1.9.0', version: '1.9.0', channels: [ null ] }, { gitTag: 'our-app-v1.9.1', version: '1.9.1', channels: [ null ] }, { gitTag: 'our-app-v3.10.0', version: '3.10.0', channels: [ null ] }, { gitTag: 'our-app-v3.11.0', version: '3.11.0', channels: [ null ] }, { gitTag: 'our-app-v3.11.0-beta.1', version: '3.11.0-beta.1', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.10', version: '3.11.0-beta.10', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.11', version: '3.11.0-beta.11', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.12', version: '3.11.0-beta.12', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.13', version: '3.11.0-beta.13', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.14', version: '3.11.0-beta.14', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.15', version: '3.11.0-beta.15', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.2', version: '3.11.0-beta.2', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.3', version: '3.11.0-beta.3', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.4', version: '3.11.0-beta.4', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.5', version: '3.11.0-beta.5', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.6', version: '3.11.0-beta.6', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.7', version: '3.11.0-beta.7', channels: [ 'main' ] }, { gitTag: 'our-app-v3.11.0-beta.8', version: '3.11.0-beta.8', channels: [ 'main' ] }, ... 375 more items ]
[6:08:33 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://gitlab-ci-token:[secure]@gitlab.our-company.net/our-company/monorepo.git
[6:08:34 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:08:34 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:08:34 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:08:34 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2023-10-11T18:08:34.027Z semantic-release:gitlab apiUrl: 'https://gitlab.our-company.net/api/v4'
2023-10-11T18:08:34.027Z semantic-release:gitlab repoId: 'our-company/monorepo'
[6:08:34 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.our-company.net/api/v4)
[6:08:34 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:08:34 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[6:08:34 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[6:08:34 PM] [semantic-release] › ℹ  Found git tag our-app-v3.16.0-beta.13 associated with version 3.16.0-beta.13 on branch main
2023-10-11T18:08:34.267Z semantic-release:get-commits Use from: 3abcb40d387794829bb3b9aeb77c9161afc959ed
[6:08:34 PM] [semantic-release] › ℹ  Commits are being filtered by the commitPaths property: force-release.md apps/our-app/* libs/design-system/src libs/our-app/api-models/src libs/our-app/data-access-configuration/src libs/our-app/data-access-policies/src libs/our-app/api-constants/src libs/our-app/feat-sitemap/src libs/our-app/mp-feat-document-center/src src libs/our-app/feat-message-center/src libs/our-app/feat-notifications/src libs/our-app/feat-external-resource/src libs/our-app/feat-feedback/src libs/our-app/api-enums/src libs/our-app/util-configuration/src libs/shared/design-system/util-modal/src src libs/our-app/feat-alerts/src libs/our-app/data-access-mtm/src libs/shared/cms/shared-data-access-squidex/src libs/web-services/src libs/web-utils/src libs/our-app/feat-theme/src libs/our-app/util-mtm/src libs/our-app/util-profile/src libs/our-app/feat-language-switcher/src libs/shared/ui-auth/src libs/shared/design-system/util-navigation/src libs/our-app/api-mocks/src libs/shared/design-system/util-footer/src libs/shared/design-system/util-form/src libs/shared/design-system/util-messages/src libs/our-app/feat-footer/src libs/our-app/api-web-services/src libs/shared/util-common/src libs/shared/design-system/util-button/src libs/shared/design-system/util-configuration/src libs/our-app/util-admin/src libs/our-app/api-utils/src libs/our-app/util-auth/src libs/our-app/util-interfaces/src libs/shared/design-system/util-datagrid/src libs/shared/pipes/src libs/shared/design-system/util-status/src libs/our-app/feat-coverage/src libs/shared/design-system/util-format/src libs/our-app/util-modal/src libs/our-app/pipes/src libs/our-app/util-message-center/src libs/our-app/feat-payment-methods/src libs/shared/design-system/util-care-card/src libs/shared/api-models/src libs/our-app/util-dashboard/src libs/our-app/util-tutorial/src libs/our-app/util-payments/src libs/our-app/ui-eob-grid/src libs/our-app/ui-reconcile-html-link/src libs/our-app/util-id-card/src libs/our-app/ui-unbound-html/src libs/our-app/feat-snack-bar/src
[6:08:34 PM] [semantic-release] › ℹ  Found 1 commits since last release
2023-10-11T18:08:34.304Z semantic-release:get-commits Parsed commits: [ { commit: { long: 'd464b45800d4983f0d91f146f2d0ac3c57bc1f64', short: 'd464b4580' }, tree: { long: 'a846826793c03ed354ff991e1f6bdb969694c83f', short: 'a84682679' }, author: { name: 'rgupta', email: 'rgupta@our-company.com', date: 2023-10-10T12:39:50.000Z }, committer: { name: 'rgupta', email: 'rgupta@our-company.com', date: 2023-10-11T15:12:16.000Z }, subject: 'feat(design-system): add fit content and white space property flag in status component', body: '', hash: 'd464b45800d4983f0d91f146f2d0ac3c57bc1f64', committerDate: 2023-10-11T15:12:16.000Z, message: 'feat(design-system): add fit content and white space property flag in status component', gitTags: '' } ]
[6:08:34 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:08:34 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(design-system): add fit content and white space property flag in status component
2023-10-11T18:08:34.312Z semantic-release:commit-analyzer Analyzing with custom rules
2023-10-11T18:08:34.313Z semantic-release:commit-analyzer The rule { type: 'feat', release: 'patch' } match commit with release type 'patch'
[6:08:34 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:08:34 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: patch release
[6:08:34 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:08:34 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ℹ  The next release version is 3.16.0-beta.14
[6:08:34 PM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script mkdir -p versions && echo v3.16.0-beta.14 > versions/our-app.version.txt
[6:08:34 PM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator version: '3.16.0-beta.14'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator host: undefined
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator owner: 'our-company'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator repository: 'monorepo'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator previousTag: 'our-app-v3.16.0-beta.13'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator currentTag: 'our-app-v3.16.0-beta.14'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator host: 'https://gitlab.our-company.net'
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator linkReferences: undefined
2023-10-11T18:08:34.357Z semantic-release:release-notes-generator issue: 'issues'
2023-10-11T18:08:34.358Z semantic-release:release-notes-generator commit: 'commit'
[6:08:34 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:08:34 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[6:08:34 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/our-company/monorepo/apps/our-app/CHANGELOG.md
[6:08:34 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[6:08:34 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/exec"
[6:08:34 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script yarn nx format --all
$ /builds/our-company/monorepo/node_modules/.bin/nx format --all
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
apps/our-app/CHANGELOG.md
nx.json
tsconfig.base.json
[6:09:24 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/exec"
[6:09:24 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[6:09:25 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
2023-10-11T18:09:25.550Z semantic-release:git add file to git index {
  command: 'git add --force --ignore-errors apps/our-app/CHANGELOG.md',
  escapedCommand: 'git add --force --ignore-errors "apps/our-app/CHANGELOG.md"',
  exitCode: 0,
  stdout: '',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
2023-10-11T18:09:25.550Z semantic-release:git commited files: [ 'apps/our-app/CHANGELOG.md' ]
[6:09:26 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: our-app-v3.16.0-beta.14
[6:09:26 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[6:09:26 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator version: '3.16.0-beta.14'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator host: undefined
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator owner: 'our-company'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator repository: 'monorepo'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator previousTag: 'our-app-v3.16.0-beta.13'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator currentTag: 'our-app-v3.16.0-beta.14'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator host: 'https://gitlab.our-company.net'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator linkReferences: undefined
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator issue: 'issues'
2023-10-11T18:09:26.401Z semantic-release:release-notes-generator commit: 'commit'
[6:09:26 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:09:26 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[6:09:26 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[6:09:27 PM] [semantic-release] › ✔  Created tag our-app-v3.16.0-beta.14
[6:09:27 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[6:09:27 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[6:09:27 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
2023-10-11T18:09:27.875Z semantic-release:gitlab repoId: 'our-company/monorepo'
2023-10-11T18:09:27.875Z semantic-release:gitlab release name: 'our-app-v3.16.0-beta.14'
2023-10-11T18:09:27.875Z semantic-release:gitlab release ref: '318abfffa0e1873226ad05d54de124dc15af9f94'
2023-10-11T18:09:27.875Z semantic-release:gitlab milestones: undefined
2023-10-11T18:09:27.875Z semantic-release:gitlab url assets: []
2023-10-11T18:09:27.882Z semantic-release:gitlab globbed assets: [ 'apps/our-app/README.md', 'apps/our-app/CHANGELOG.md' ]
2023-10-11T18:09:27.882Z semantic-release:gitlab all assets: [ 'apps/our-app/README.md', 'apps/our-app/CHANGELOG.md' ]
2023-10-11T18:09:27.882Z semantic-release:gitlab file path: 'apps/our-app/README.md'
2023-10-11T18:09:27.882Z semantic-release:gitlab file label: undefined
2023-10-11T18:09:27.882Z semantic-release:gitlab file type: undefined
2023-10-11T18:09:27.882Z semantic-release:gitlab file filepath: undefined
2023-10-11T18:09:27.883Z semantic-release:gitlab POST-ing the file /builds/our-company/monorepo/apps/our-app/README.md to https://gitlab.our-company.net/api/v4/projects/our-company%2Fmonorepo/uploads
2023-10-11T18:09:27.886Z semantic-release:gitlab file path: 'apps/our-app/CHANGELOG.md'
2023-10-11T18:09:27.886Z semantic-release:gitlab file label: undefined
2023-10-11T18:09:27.886Z semantic-release:gitlab file type: undefined
2023-10-11T18:09:27.886Z semantic-release:gitlab file filepath: undefined
2023-10-11T18:09:27.886Z semantic-release:gitlab POST-ing the file /builds/our-company/monorepo/apps/our-app/CHANGELOG.md to https://gitlab.our-company.net/api/v4/projects/our-company%2Fmonorepo/uploads
[6:09:28 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/6604eca490f6992e39fb04251445d65d/README.md
[6:09:28 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: /uploads/ce1932f5313028ffa40ebf3f634d1f95/CHANGELOG.md
2023-10-11T18:09:28.721Z semantic-release:gitlab Create a release for git tag 'our-app-v3.16.0-beta.14' with commit '318abfffa0e1873226ad05d54de124dc15af9f94'
2023-10-11T18:09:28.722Z semantic-release:gitlab POST-ing the following JSON to https://gitlab.our-company.net/api/v4/projects/our-company%2Fmonorepo/releases:
{
  "tag_name": "our-app-v3.16.0-beta.14",
  "description": "# [3.16.0-beta.14](https://gitlab.our-company.net/our-company/monorepo/compare/our-app-v3.16.0-beta.13...our-app-v3.16.0-beta.14) (2023-10-11)\n\n\n### Features\n\n* **design-system:** add fit content and white space property flag in status component ([d464b45](https://gitlab.our-company.net/our-company/monorepo/commit/d464b45800d4983f0d91f146f2d0ac3c57bc1f64))\n\n\n\n",
  "assets": {
    "links": [
      {
        "name": "README.md",
        "url": "https://gitlab.our-company.net/our-company/monorepo/uploads/6604eca490f6992e39fb04251445d65d/README.md"
      },
      {
        "name": "CHANGELOG.md",
        "url": "https://gitlab.our-company.net/our-company/monorepo/uploads/ce1932f5313028ffa40ebf3f634d1f95/CHANGELOG.md"
      }
    ]
  }
}
[6:09:28 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Published GitLab release: our-app-v3.16.0-beta.14
[6:09:28 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/gitlab"
[6:09:28 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[6:09:28 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[6:09:28 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/gitlab"
2023-10-11T18:09:28.987Z semantic-release:gitlab Getting MRs from https://gitlab.our-company.net/api/v4/projects/our-company%2Fmonorepo/repository/commits/d464b45800d4983f0d91f146f2d0ac3c57bc1f64/merge_requests
2023-10-11T18:09:29.255Z semantic-release:gitlab Getting related issues from https://gitlab.our-company.net/api/v4/projects/1009/merge_requests/978/closes_issues
2023-10-11T18:09:29.352Z semantic-release:gitlab Posting MR note to https://gitlab.our-company.net/api/v4/projects/1009/merge_requests/978/notes
[6:09:29 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/gitlab"
[6:09:29 PM] [semantic-release] › ✔  Published release 3.16.0-beta.14 on main channel
```

**Comment by travi** [comment] 2023-10-12 23:31
there are too many variables here that are outside supported approach to effectively help you.

first, you are multiple major versions behind our current releases. even if there is a bug in that old of a version, we have no plans to backport bug fixes that far. 

second, it looks like you are using semantic-release in the context of a monorepo. the core of semantic-release does not officially support monorepos. we dont prevent it, and we encourage community members to build monorepo support on top of our core, but we do not provide support for their solutions. 

if you want support for this problem in the context of a monorepo, you need to start with the tool you are using to add the support for monorepos. if you think this is a problem with semantic-release itself, we need you to provide a reproduction of the problem in a public repo that is not a monorepo.

i'm closing this as out of scope for now, but if you decide to provide a reproduction using the latest version and without the complication of the monorepo, feel free to reopen or create a new issue.

**Closed by travi** 2023-10-12 23:31 UTC

**Comment by wkaskie** [comment] 2023-10-17 20:18
I see that it's closed, but I can add that semantic-release is working for several other apps in the monorepo. It's also been working for over a year. Suddenty, git notes are not being written. I have no insight into why the tool may no longer be writing the notes. All tags are missing the {channels: ["channel", "channel"} information as of about 2 weeks ago.

**Comment by sheerlox** [comment] 2023-11-25 14:20
While looking at the issue, I noticed you provided a `semantic-release` version but then mentioned `semantic-release-plus` in your "plugins". The latter states that it is a "drop in replacement for semantic release", meaning you're either running one or the other.

If you're running on `semantic-release-plus`, please note the package is a fork of this repository, and therefore we cannot provide support for it. You should also note it hasn't received any update for more than two years (since April 2022).

I hope this information helps, and am sorry you feel your issue has been dismissed, but please understand we cannot provide support for forks and community plugins on this repository.
