### ISSUE TITLE
Support using esm shareable configurations

### ISSUE THREAD

**Issue by bryanjtc** [semantic-release/semantic-release#3040] opened 2023-11-01 03:39 UTC
### Current behavior

When I try to use `index.mjs` or `index.js` in the extends key of the semantic release config with a package.json using `type: module`, this error shows up:
```shell
[10:36:36 PM] [semantic-release] » ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Projects\semantic-release-monorepo\index.js from C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js not supported.
Instead change the require of index.js in C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js to a dynamic import() which is available in all CommonJS modules.
    at file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:38:32
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:36:11)
    at async Module.default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/index.js:271:34)
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/cli.js:55:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Expected behavior

No error

### `semantic-release` version

22.0.6

### CI environment

Github

### `semantic-release` configuration

{
    "extends": ["./index.js"]
}

### CI logs

```shell
 yarn semantic-release --debug --dry-run
[10:36:36 PM] [semantic-release] » ℹ  Running semantic-release version 22.0.6
  semantic-release:config load config from: C:\Projects\semantic-release-monorepo\.releaserc.json +0ms
[10:36:36 PM] [semantic-release] » ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Projects\semantic-release-monorepo\index.js from C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js not supported.
Instead change the require of index.js in C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js to a dynamic import() which is available in all CommonJS modules.
    at file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:38:32
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:36:11)
    at async Module.default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/index.js:271:34)
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/cli.js:55:5) {
  code: 'ERR_REQUIRE_ESM'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Projects\semantic-release-monorepo\index.js from C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js not supported.
Instead change the require of index.js in C:\Projects\semantic-release-monorepo\node_modules\semantic-release\lib\get-config.js to a dynamic import() which is available in all CommonJS modules.
    at file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:38:32
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/lib/get-config.js:36:11)
    at async Module.default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/index.js:271:34)
    at async default (file:///C:/Projects/semantic-release-monorepo/node_modules/semantic-release/cli.js:55:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by bryanjtc** [comment] 2023-11-01 04:36
Related #3036
Fixed by #3037

**Comment by travi** [comment] 2023-11-01 04:54
lets keep this contained within the existing issue. duplicate of #3036

**Closed by travi** 2023-11-01 04:54 UTC

**Comment by travi** [comment] 2023-11-01 05:49
also, note https://github.com/semantic-release/semantic-release/issues/3036#issuecomment-1788447980
