### ISSUE TITLE
Dry mode is always being triggered

### ISSUE THREAD

**Issue by lnmunhoz** [semantic-release/semantic-release#1316] opened 2019-10-12 08:46 UTC
## Current behavior
When I run `semantic-release` locally, it's always runs in `dry-mode`

## Expected behavior
Not to run in dry-mode if I don't pass the `dry-mode` flag or if I set `false` in my `.releaserc.js` config.

### .releaserc.js
```
module.exports = {
  dryRun: false,
  branch: 'master',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    [
      '@semantic-release/git',
      {
        message:
          'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
    '@semantic-release/gitlab',
  ],
};
```

## Environment
Running locally on Mac OSX
node: 10.16.3
semantic-release: 15.13.24

## Logs (local):
```
[3:44:27 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.24
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[3:44:27 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[3:44:27 PM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[3:44:27 PM] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
```

### Update
Eventually I passed `ci: false` to my config and worked. But it was difficult to troubleshoot. I think the logs should be more specific that is running on CI mode. For me the error message `This run was not triggered in a known CI environment, running in dry-run mode.` means that is not running on CI.

**Comment by pvdlg** [comment] 2019-10-14 15:02
That is the intended behavior, we want to force dry=run mode when not running on a CI to avoid unintentional publications.
What's not clear about the error message? It tells that you that you running in a non-CI environment and therefore it runs in dry-mode. What would you change to make it clearer?

**Comment by pvdlg** [comment] 2019-11-01 02:45
Closing as no answer provided

**Closed by pvdlg** 2019-11-01 02:45 UTC
Labels: info requested

**Comment by tamj0rd2** [comment] 2021-01-21 10:41
What if I am running inside of a CI environment but semantic-release doesn't recognise it? I'm running semantic-release inside a docker container on GithubActions

**Comment by gr2m** [comment] 2021-01-21 20:36
I'm not sure if such a feature exist, but if you would pass through all `GITHUB_*` environment variables then it should work.

**Comment by zioalex** [comment] 2021-05-12 07:43
I think this can be improved.
The fact that semantic-release doesn't know the CI used doesn't mean that you are not running it on another CI.
I had the same problem setting it up on Azure DevOps.
I just added the option `--no-ci` on the cli but this is counter intuitive to me.

**Comment by zioalex** [comment] 2021-05-12 15:53
I think this can be improved.
The fact that semantic-release doesn't know the CI used doesn't mean that you are not running it on another CI.
I had the same problem setting it up on Azure DevOps. 
I just added the option `--no-ci` on the cli but this is counter intuitive to me because I am using it in a CI.
