### ISSUE TITLE
Tag suffix @branch is unexpected

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/semantic-release#1191] opened 2019-05-28 20:41 UTC
## Current behavior

It seems like for prerelease support, semantic-release tags the released version with a git tag `version@branch`, e.g. `1.1.0-beta.1@beta`. 

The problem I met with this is that if a manual release was done somewhere in between with `npm version prerelease --preid beta`, which creates a tag without the branch suffix like `2.0.0-beta.1`, that release will not be recognized as the last release, and instead the previous automatic release will be used.

It doesn't make sense to me to use this prefix, because without the suffix the commit is already unambiguous. In npm, when you set a dist tag `beta` to a version, and then also set `latest` to that version, they will refer to the exact same package contents, it's impossible that they would be different. But the tag scheme suggest it's possible for them to be different.

It also doesn't fit into the git model - branches are mutable commit pointers, tags are immutable commit pointers. A version, once created, will always be that specific commit and never change. A branch like `beta` or `latest` however moves forward all the time and changes. And when you promote a commit tagged with a prerelease version from `beta` to `latest` (through `git merge beta`, `git merge beta --no-ff`, `git push origin beta:latest`, `git reset --hard beta`, a pull request with merge etc) the tag will still be the same version, just the other branch will now include it. So what's the point of including the suffix?

Other tools may also expect that the git tag matches the npm version name without a suffix.

It also seems like this is not possible to configure with `tagFormat`: https://semantic-release.gitbook.io/semantic-release/v/beta/usage/configuration#tagformat

## Expected behavior

I would expect it to just tag it with `1.0.0-beta.1`, and know the branch/dist-tag from the currently checked out branch name.

## Environment

- **semantic-release** version: 16.0.0-beta.18
- CI environment: Travis
- Plugins used: none
- **semantic-release** configuration: https://github.com/sourcegraph/lsp-client
- CI logs: https://travis-ci.org/sourcegraph/lsp-client/jobs/538334800

**Comment by ivandov** [comment] 2019-07-25 01:29
I also just ran into this. For a pre-release version, I was not expecting a suffix of `@beta` and do not see anywhere to modify the format with `tagFormat`.

**Comment by dominykas** [comment] 2019-07-25 05:34
Is this a duplicate of #1101

**Comment by ivandov** [comment] 2019-07-25 20:18
Yes, I believe it is. I found that one last night as well.

**Comment by pvdlg** [comment] 2019-12-03 05:06
Fixed by #1368

**Closed by pvdlg** 2019-12-03 05:06 UTC
Labels: released on @beta
