### ISSUE TITLE
Release incorrectly "fails" publishing when posting comments to GitHub

### ISSUE THREAD

**Issue by eventualbuddha** [semantic-release/semantic-release#694] opened 2018-03-10 00:12 UTC
# Bug report

## Current behavior

In multiple projects using semantic-release with Travis CI's build stages, semantic-release "fails" when doing a deploy. However, everything seems to go fine: the npm package is published, the tag is pushed, a release is made, and comments are made on GitHub PRs. The logs indicate that a response made to the GitHub API is returning a 404 Not Found–presumably for creating PR comments–but the comments do appear.

### [add-variable-declarations Travis CI build job](https://travis-ci.org/eventualbuddha/add-variable-declarations/jobs/351441479)

```
+ add-variable-declarations@3.1.3[Semantic release]: Published GitHub release: https://github.com/eventualbuddha/add-variable-declarations/releases/tag/v3.1.3
[Semantic release]: Added comment to issue #85: https://github.com/eventualbuddha/add-variable-declarations/pull/85#issuecomment-371909143
[Semantic release]: Added comment to issue #84: https://github.com/eventualbuddha/add-variable-declarations/pull/84#issuecomment-371909149
[Semantic release]: Added comment to issue #83: https://github.com/eventualbuddha/add-variable-declarations/pull/83#issuecomment-371909152
[Semantic release]: Added comment to issue #82: https://github.com/eventualbuddha/add-variable-declarations/pull/82#issuecomment-371909156
[Semantic release]: Added comment to issue #81: https://github.com/eventualbuddha/add-variable-declarations/pull/81#issuecomment-371909160
[Semantic release]: Added comment to issue #80: https://github.com/eventualbuddha/add-variable-declarations/pull/80#issuecomment-371909179
[Semantic release]: Failed to add a comment to the issue #3135.
[Semantic release]: Failed to add a comment to the issue #2352.
[Semantic release]: Failed to add a comment to the issue #3128.
[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"Not Found","[secure]cumentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}
    at response.text.then.message (/home/travis/.npm/_npx/5827/lib/node_modules/semantic-release/node_modules/@octokit/rest/lib/request/request.js:56:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 404,
  status: 'Not Found',
  headers: …
```

* [GitHub release v3.1.3 created successfully](https://github.com/eventualbuddha/add-variable-declarations/releases/tag/v3.1.3)
* [Comment on eventualbuddha/add-variable-declarations#85 submitted successfully](https://github.com/eventualbuddha/add-variable-declarations/pull/85#issuecomment-371909143)

## Expected behavior

The `semantic-release` command should exit successfully if the servers actually do respond with the right values. This feels like a potential GitHub issue, or perhaps a misuse of the GitHub API by semantic-release.

## Environment

- **semantic-release** version: latest (run via `npx semantic-release`, which was 15.0.2 at the time)
- CI environment: Travis CI (public)
- Plugins used: default set
- **semantic-release** configuration: https://github.com/eventualbuddha/add-variable-declarations/blob/b62beb5500c818428a66de75363d370c764659dd/.travis.yml
- CI logs: https://travis-ci.org/eventualbuddha/add-variable-declarations/jobs/351441479

**Comment by pvdlg** [comment] 2018-03-10 00:59
This issue was just reported on Gitter :) And I'm working on a fix :)

**Comment by pvdlg** [comment] 2018-03-10 01:37
So the problem is that we parse by mistake the issues referenced in Greekeeper Pull Request.
For example https://github.com/eventualbuddha/add-variable-declarations/pull/83
We end up parsing `#3135` from there but it's incorrect.

**Comment by pvdlg** [comment] 2018-03-10 03:29
Fixed in https://github.com/pvdlg/issue-parser/pull/6.

Just make sure to update the `issue-parser` dependency if you are using a lockfile.

**Closed by pvdlg** 2018-03-10 03:29 UTC
