### ISSUE TITLE
Remove Travis CI Plugin

### ISSUE THREAD

**Issue by destroyerofbuilds** [semantic-release/semantic-release#486] opened 2017-10-26 21:52 UTC
Travis CI now supports [Build Stages](https://docs.travis-ci.com/user/build-stages/).

Users of `semantic-release` can define a `release` stage and execute `semantic-release` only within that stage.

`semantic-release` would no longer need the Travis-CI plugin to ensure it's only executed on the _leader_ job.

This would make it easier for package maintainers using alternative CI providers to adopt `semantic-release`.

**Comment by destroyerofbuilds** [comment] 2017-10-26 21:53
I believe this would simply require writing documentation that encourages users to use _Build Stages_ if using Travis CI, and then remove the Travis-CI plugin from `semantic-release` (As part of a major version release).

**Comment by pvdlg** [comment] 2017-10-27 22:38
Build stage is indeed a better solution, and if we were starting `semantic-release` now we would probably rely only on that. But as we have a working plugin that allow to support configuration with and without Build stage there I' not sure to see a reason to remove it...

We can encourage users to use Build Stage with the `condition-travis` plugin by recommending this approach in the documentation. Contribution are welcome !

> This would make it easier for package maintainers using alternative CI providers to adopt semantic-release

`semantic-release` can be configured to use other plugins to support other CI. For example https://github.com/bahmutov/condition-circle or https://github.com/semantic-release/condition-codeship.
Could you explain why removing the plugin would help? What's problematic with the plugin approach?

**Comment by destroyerofbuilds** [comment] 2017-10-30 20:54
> allow to support configuration with and without Build stage there I' not sure to see a reason to remove it

If it's no longer needed, removing it would mean less code to upgrade as new JavaScript features are released. Less code to refactor as the plugin system evolves. Less code that could break one day.

> We can encourage users to use Build Stage with the condition-travis plugin by recommending this approach in the documentation.

Since `semantic-release` uses Travis CI, this could be a fun opportunity to demonstrate the power of build stages.

If I can get to it this week I'll submit a pull request to update `semantic-release` to use Travis build stages.

>  support other CI. For example https://github.com/bahmutov/condition-circle

I would actually like to use Circle CI for one of my projects, but I don't see the value in using the Circle CI plugin you listed.

It does two things: checks that you're running on Circle CI, and that you are running on the branch configured in your `semantic-release` configuration in `package.json`.

The first one, the one that checks that I'm running on Circle CI, does not add value to the developer experience, or quality of the product. If I want to run my project on Circle CI, I'll run my project on Circle CI. Nothing more to it.

As for checking whether `semantic-release` is running on a given branch, I would probably just use the `branches` option for a deployment `job` - https://circleci.com/docs/2.0/configuration-reference/#job_name

Therefore, to get `semantic-release` running on Circle CI I would just need to add configuration to my project's `package.json` to disable a Travis CI plugin, which seems a little silly if I am not even using Travis CI to begin with.

**Comment by pvdlg** [comment] 2017-10-30 21:49
> If it's no longer needed, removing it would mean less code to upgrade as new JavaScript features are released. Less code to refactor as the plugin system evolves. Less code that could break one day.

100s or probably 1000s of build depends on it. It might mean less code to maintain, but it also mean 
all those builds will fail or behave improperly in case a user doesn't read the release note mentioning that Build stages are now mandatory. It also means a lot of issues opened by users who do not want to or cannot use Build Stage x, y, z reasons.

It we realize the code doesn't work and the charge to fix it is important we might think about decommissioning it. It the code works and is used by most users, I don't see the point of removing the feature.

If the plugin doesn't cover a use case then we can update it.
Can you explain which workflow the plugin prevent you to achieve ?

> If I can get to it this week I'll submit a pull request to update semantic-release to use Travis build stages.

PR are always welcome. But I'm not sure what modification you are proposing here. `semantic-release` support Build stages with the current `conditions-travis`. See [comment](https://github.com/semantic-release/semantic-release/issues/390#issuecomment-330017166).
We need to document it though.

Could you elaborate a little bit on the modification you are proposing ?

> It does two things: checks that you're running on Circle CI, and that you are running on the branch configured in your semantic-release configuration in package.json.
The first one, the one that checks that I'm running on Circle CI, does not add value to the developer experience, or quality of the product. If I want to run my project on Circle CI, I'll run my project on Circle CI. Nothing more to it.

The `verify-conditions` plugin is responsible for more than that:
- Verify we are running on a CI env
- Verify we are running on the configured branch
- Verify we are not running on a PR build
- Guarantee that the test of the current job and all other job are successful (that part can be insured by Build Stage if you choose to)

> Therefore, to get semantic-release running on Circle CI I would just need to add configuration to my project's package.json to disable a Travis CI plugin, which seems a little silly if I am not even using Travis CI to begin with.

We have a plugin system to let users customize `semantic-release`. We choose to have the Travis one as the default because it's the most commonly used. Using another CI environment require using another plugin at the moment.
We could have make a plugin that works on all CI but at the time the plugin was created, it was made specific to Travis as making Api calls to Travis was the only way to guarantee we make a release only when other jobs a successful.

Another thing to consider with Build Stages is that we have no way in `semantic-release` to verify that the configuration of Build Stages is done properly. A misconfiguration in the build stages might trigger an unwanted release.
The amount of safety check we should put in the code to prevent problems due to misconfiguration is arguable, but a lot of issue we have are related to a misconfiguration that have created a release or a tag and the user struggles to recover from that. In other type of software, I'd say that failures due to misconfiguration are completely acceptable and expected. In the case of `semantic-release` it result in an unwanted release  which can have a lot of consequences:
- Some user might upgrade to the new release before you relaize the problem happened
- Tools like `greenkeeper` will be triggered, creating update PR, that might get merge
- Any other automated tool that listening to npm publishes will be triggered (blog posts, mails, tweet, confetis, etc...)
- Unpublishing the version on npm prevent to reuse the version later (if you release `2.0.0` and unpublish it, you won't be able to release `2.0.0` it again, ever.You'd have to take manual step to release `2.0.1` or `3.0.0`)

All that concerns mostly big projects. But still, it's important for `semantic-release` to take extra care in checking everything possible before making the release.

**Comment by pvdlg** [comment] 2017-11-21 07:00
I create a PR to add explanation on how to use Build Stage with an example: https://github.com/semantic-release/condition-travis/pull/91

Does that address the concerns raised in this issue ?

**Comment by pvdlg** [comment] 2017-12-20 01:15
Duplicate of semantic-release/condition-travis#96

**Comment by pvdlg** [comment] 2017-12-20 01:16
Closing in favor of semantic-release/condition-travis#96

Other CI can be supported via plugin, by configuring a different plugin in place of `condition-travis`.

**Closed by pvdlg** 2017-12-20 01:16 UTC
Labels: awaiting response, design, plugin:travis
