### ISSUE TITLE
Unable to login to npm

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#732] opened 2018-04-06 14:04 UTC
# Bug report

## Current behavior

Here's what I ran into for a library I wanted to publish today:

```
~/Developer/dom-testing-library (master)
🐑  $ npx semantic-release-cli setup
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v57-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/kdodds/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/kdodds/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/kdodds/.npm/_npx/19411/lib/node_modules/semantic-release-cli/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /Users/kdodds/.npm/_npx/19411/lib/node_modules/semantic-release-cli/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
? What is your npm registry? http://registry.npmjs.org/
? Which authentication method is this npm registry using? Token based
? What is your npm username? kentcdodds
ERR! semantic-release Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/Users/kdodds/.npm/_npx/19411/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release  { Error: Could not login to npm.
ERR! semantic-release     at getNpmToken (/Users/kdodds/.npm/_npx/19411/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release   stack: 'Error: Could not login to npm.\n    at getNpmToken (/Users/kdodds/.npm/_npx/19411/lib/node_modules/semantic-release-cli/src/lib/npm.js:51:21)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }

~/Developer/dom-testing-library (master)
🐑  $ npm whoami
kentcdodds
```

## Expected behavior

I expected this to work as it always has. I've never seen this failure before.

## Environment

- **semantic-release-cli** version: latest (via `npx`). At the time of this writing that's `3.6.4`
- CI environment: N/A
- Plugins used: N/A
- **semantic-release** configuration: N/A
- CI logs: N/A

Due to this bug, I attempted to do the setup manually by generating my npm and github tokens myself, setting up the travis build, and adding those tokens as environment variables. I was unsuccessful, and I'll file a new issue for what's going on there.

**Comment by pvdlg** [comment] 2018-04-06 16:05
It seems to be an exact duplicate of semantic-release/cli#190 so I'm going to close this one.
Feel free to re-open if you disagree.

**Comment by pvdlg** [comment] 2018-04-06 16:05
Duplicate of semantic-release/cli#190

**Closed by pvdlg** 2018-04-06 16:05 UTC

**Comment by kentcdodds** [comment] 2018-04-07 13:42
Thanks! It looks like things were resolved when I actually installed `semantic-release-cli` globally rather than using `npx`.
