### ISSUE TITLE
Set first version

### ISSUE THREAD

**Issue by jormot** [semantic-release/semantic-release#837] opened 2018-06-28 04:38 UTC
## New feature motivation

[Semver indicates](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) that first version should be `0.1.0`, but it's hardcoded to `1.0.0` [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/definitions/constants.js#L3).

## New feature description

Provide a `firstVersion` option to change the initial version. If that option is not found, use the one defined at `constants.js`.

**Comment by pvdlg** [comment] 2018-06-28 04:48
Please see this FAQ [Can I set the initial release version of my package to 0.0.1?](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-set-the-initial-release-version-of-my-package-to-001) explaining why semantic-release start the releases at `1.0.0`.

Please also see #532 with an similar request and several explanations.
In addition #563 will allow to use pre-release version that would fulfill the need of publishing beta versions.

**Comment by pvdlg** [comment] 2018-06-28 04:48
Duplicate of #532

**Closed by pvdlg** 2018-06-28 04:48 UTC

**Comment by jormot** [comment] 2018-06-28 05:10
Didn't catch the issues, searched for _first version_ but nothing appeared. Thanks for the links.

**Comment by ckemmler** [comment] 2019-10-14 13:42
I want to start the release cycle at 3.0.0, which is legit, but that, too, seems to be impossible. And I don't think that's right.
Is there really no way to override the `FIRST_RELEASE` value?

**Comment by travi** [comment] 2019-10-14 18:22
@ckemmler would i be correct to assume that you are wanting to start at v3.0.0 because the package already has existing versions in the 2.x.x range? if so, just make sure that the most recent version has a tag that [conforms to the proper format](https://semantic-release.gitbook.io/semantic-release/usage/configuration#existing-version-tags) and make a commit that will trigger a major version bump. that should be enough for semantic-release to take over from there.

**Comment by trallnag** [comment] 2022-06-26 16:04
The link provided by @pvdlg is dead as of today. Here is the correct link (for now): https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0.0.1

**Comment by tukusejssirs** [comment] 2023-10-13 15:48
> @ckemmler would i be correct to assume that you are wanting to start at v3.0.0 because the package already has existing versions in the 2.x.x range? if so, just make sure that the most recent version has a tag that [conforms to the proper format](https://semantic-release.gitbook.io/semantic-release/usage/configuration#existing-version-tags) and make a commit that will trigger a major version bump. that should be enough for semantic-release to take over from there.

I don’t want `semantic-release` to _assume_ the initial release version, I (just like the OP) want to _configure it_ for the _first run_ only.

I have even tried to create an arbitrary tag (using `git tag 2.0.0-dev.1 $commit`), but `semantic-release` still logs that `No git tag version found on branch dev`, as `semantic-release` first check for the _stable_ version. Therefore, I have create a tag for `2.0.0`, which gets recognised by `semantic-release`, but I need to use a `BREAKING CHANGE` in a commit since the tag, however, it might not be the case when re-writing an app from scratch.

Therefore, in these cases, we need an option to define the initial version.

The only workaround I see is to temporarily modify the code of `semantic-release`:

```bash
# Change the initial version to `2.0.0`
sed -i 's/\( FIRST_RELEASE\) = "1.0.0"/\1 = "2.0.0"/' node_modules/semantic-release/lib/definitions/constants.js

# Do the release
pnpm semantic-release

# Revert the initial version
sed -i 's/\( FIRST_RELEASE\) = "2.0.0"/\1 = "1.0.0"/' node_modules/semantic-release/lib/definitions/constants.js
```

**Comment by leoslf** [comment] 2023-11-28 00:06
> > @ckemmler would i be correct to assume that you are wanting to start at v3.0.0 because the package already has existing versions in the 2.x.x range? if so, just make sure that the most recent version has a tag that [conforms to the proper format](https://semantic-release.gitbook.io/semantic-release/usage/configuration#existing-version-tags) and make a commit that will trigger a major version bump. that should be enough for semantic-release to take over from there.
> 
> I don’t want `semantic-release` to _assume_ the initial release version, I (just like the OP) want to _configure it_ for the _first run_ only.
> 
> I have even tried to create an arbitrary tag (using `git tag 2.0.0-dev.1 $commit`), but `semantic-release` still logs that `No git tag version found on branch dev`, as `semantic-release` first check for the _stable_ version. Therefore, I have create a tag for `2.0.0`, which gets recognised by `semantic-release`, but I need to use a `BREAKING CHANGE` in a commit since the tag, however, it might not be the case when re-writing an app from scratch.
> 
> Therefore, in these cases, we need an option to define the initial version.
> 
> The only workaround I see is to temporarily modify the code of `semantic-release`:
> 
> ```shell
> # Change the initial version to `2.0.0`
> sed -i 's/\( FIRST_RELEASE\) = "1.0.0"/\1 = "2.0.0"/' node_modules/semantic-release/lib/definitions/constants.js
> sed -i 's/\( FIRSTPRERELEASE\) = "1"/\1 = "2"/' node_modules/semantic-release/lib/definitions/constants.js
> 
> # Do the release
> pnpm semantic-release
> # Stable version example: 2.0.0
> # Dev version example: 2.0.0-dev.2
> 
> # Revert the initial version
> sed -i 's/\( FIRST_RELEASE\) = "2.0.0"/\1 = "1.0.0"/' node_modules/semantic-release/lib/definitions/constants.js
> sed -i 's/\( FIRSTPRERELEASE\) = "2"/\1 = "1"/' node_modules/semantic-release/lib/definitions/constants.js
> ```

This is where [patch-package](https://www.npmjs.com/package/patch-package) shines
