### ISSUE TITLE
Semantic-release using http instead of https

### ISSUE THREAD

**Issue by jwalton** [semantic-release/semantic-release#979] opened 2018-11-08 03:02 UTC
This looks like a slightly different version of https://github.com/semantic-release/semantic-release/issues/965.

## Current behavior

```
[7:32:21 PM] [semantic-release] › ✖  The command "git push --dry-run http://[secure]@github.com/benbria/loop-location-picker.git HEAD:master" failed with the error message remote: Repository not found.
fatal: repository 'http://[secure]@github.com/benbria/loop-location-picker.git/' not found
```

## Expected behavior

Semantic-release should use the https URL, not the http URL.  This is the same as #965, except I'm using semantic-release@15.10.8 (latest).  The suggested fix in that issue is to use an `https` URL in your repository, but I already am:

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/benbria/loop-contact-prompt.git"
  },
```

## Environment

- **semantic-release** version: 15.10.8
- CI environment: Travis

**Comment by pvdlg** [comment] 2018-11-08 18:09
I can't reproduce. For me with the URL `https://github.com/benbria/loop-contact-prompt.git`, `https` is used.
Can you provide the log output with `--debug`?

**Comment by pvdlg** [comment] 2018-11-17 19:52
Closing as this problem doesn't seems to affect anyone else (so not likely to be a bug) and no answer was provided here.

**Closed by pvdlg** 2018-11-17 19:52 UTC
Labels: core, info requested

**Comment by jwalton** [comment] 2018-11-17 19:58
Sorry, it magically started working.  I was hoping to spend some time
debugging it, but I've been busy.  Closing is fine.  :)

**Comment by pvdlg** [comment] 2018-11-17 19:59
Maybe you add an older version due to a lockfile?
Anyway feel free to re-open if the problem happens again.
