### ISSUE TITLE
Should fail with exit code in absence of new release

### ISSUE THREAD

**Issue by hugeps** [semantic-release/semantic-release#3402] opened 2024-07-22 16:11 UTC
### Current behavior

[3:08:23 PM] [semantic-release] › ℹ  Found 1 commits since last release
...
[3:08:23 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:08:23 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.

then it exits with code 0, CI continues, but no effective release due to minor problem in the commit comment

### Expected behavior

As there was a meaningful commit with loads of code changes and the only problem was commit title,
such pipeline should really be failing and not completing, as now we have code on master, 
CI complete, but no new release on GH.

### `semantic-release` version

21.0.2

### CI environment

Tekton

### Plugins used

Installing semantic-release@21.0.2
@semantic-release/commit-analyzer is installed by default with semantic-release
@semantic-release/release-notes-generator is installed by default with semantic-release
Installing @semantic-release/changelog@6.0.3
@semantic-release/github is installed by default with semantic-release
semantic-release run command is: semantic-release --branches master --extends ./.releaserc-github.json --no-ci 

### `semantic-release` configuration

```
{
  "tagFormat": "v${version}",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/github",{
      "assets": [
        {"path": "dist/*.tar.gz", "label": "iac-sample-module distribution"},
        {"path": "dist/*.signature.asc", "label": "iac-sample-module signature"}
      ]
    }]
  ]
}
```

### CI logs

Installing semantic-release@21.0.2
@semantic-release/commit-analyzer is installed by default with semantic-release
@semantic-release/release-notes-generator is installed by default with semantic-release
Installing @semantic-release/changelog@6.0.3
@semantic-release/github is installed by default with semantic-release
semantic-release run command is: semantic-release --branches master --extends ./.releaserc-github.json --no-ci 
[3:08:06 PM] [semantic-release] › ℹ  Running semantic-release version 21.0.2
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[3:08:14 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[3:08:20 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://x-oauth-basic/:[secure]@github.ibm.com/SOSTeam/cpp-ocp-module
[3:08:20 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[3:08:20 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[3:08:20 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[3:08:20 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[3:08:20 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.ibm.com/api/v3)
[3:08:23 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[3:08:23 PM] [semantic-release] › ℹ  Found git tag v3.1.0 associated with version 3.1.0 on branch master
[3:08:23 PM] [semantic-release] › ℹ  Found 1 commits since last release
[3:08:23 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:08:23 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat() ticket test (#146)
[3:08:23 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:08:23 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: no release
[3:08:23 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:08:23 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
Semantic Release logs existing version as 3.1.0

**Comment by travi** [comment] 2024-07-22 16:30
Validating that you follow the proper convention is out of scope for semantic-release. It is intended behavior that commits can be made that do not result in a release. If you need a reminder to follow the convention, please consider using commitlint

**Closed** 2024-07-22 16:30 UTC
