### ISSUE TITLE
ERELEASEBRANCHES The release branches are invalid in the `branches` configuration. when I use object

### ISSUE THREAD

**Issue by Ridermansb** [semantic-release/semantic-release#1587] opened 2020-06-25 21:20 UTC
## Current behavior

> [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

> This may occur if your repository does not have a release branch, such as master.
> Your configuration for the problematic branches is [].

> { AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Users/ridermansb/Projects/meve.ai/web/node_modules/semantic-release/lib/get-error.js:6:10)

## Expected behavior

Generate pre release

## Environment

- **semantic-release** version:  "semantic-release": "^17.1.1",
- CI environment: macOS
- Plugins used: "@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/github",

- **semantic-release** configuration: 
```
{
    "branches": [
        {"name": "master", "prerelease": true}
    ],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/github",
            {
                "assets": [
                    {
                        "path": "dist.zip",
                        "label": "PWA App"
                    }
                ]
            }
        ]
    ]
}
```

- CI logs: 

> [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

> This may occur if your repository does not have a release branch, such as master.
> Your configuration for the problematic branches is [].

> { AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Users/ridermansb/Projects/meve.ai/web/node_modules/semantic-release/lib/get-error.js:6:10)

**Comment by Ridermansb** [comment] 2020-06-27 12:54
Created public repo to demonstrate this problem...

https://github.com/Ridermansb/react-firebase-ssr/runs/813996442?check_suite_focus=true

**Comment by admir86** [comment] 2020-09-23 07:07
@Ridermansb have you found a solution?
I have the same problem. Looks like you need to have a release branch that is not a prerelease branch. And the name must not be a version, such as 1.0.

With this configuration I have the same error:
```
"branches": [
      "1.0",
      {
        "name": "master",
        "channel": "rc",
        "prerelease": "rc"
      }
    ],
```

Can anyone confirm this? Is this by design? Or is it an error? Maybe @pvdlg ? :)

**Comment by nk2580** [comment] 2020-10-29 06:39
i have the same issue, regardless of the remote presence or existing release branch config. all object config is not applied

**Comment by nk2580** [comment] 2020-11-06 02:26
This turned out to be an issue with using Node 15 in Gitlab CI , using node 12 everything worked

**Comment by dominykas** [comment] 2023-10-31 16:08
Seems #2503 is a duplicate of this?

**Comment by travi** [comment] 2023-11-03 18:35
> Seems #2503 is a duplicate of this?

yes, appears so. lets consolidate the conversation in #2503 since the conversation has moved forward there

**Closed by travi** 2023-11-03 18:35 UTC
