### ISSUE TITLE
beta branch pre-release breaking change not updating major version

### ISSUE THREAD

**Issue by tay1orjones** [semantic-release/semantic-release#1214] opened 2019-06-21 14:55 UTC
## Current behavior

After creating `beta` branch, commits were added that did not contain the `BREAKING CHANGE` message. A new release was published - `1.62.0-beta.1`.

A new commit was added that contained the `BREAKING CHANGE` message. `commit-analyzer` determined the release should be a major/breaking version change. Despite this, the new version published was `1.62.0-beta.2`.

## Expected behavior

In the case of the scenario above, I'd expect the version published to be `2.0.0-beta.1`

## Further Details
Output from CI shows the commit was properly analyzed:

```sh
npx semantic-release@beta
npx: installed 808 in 22.903s
[semantic-release] â€º â„¹  Running semantic-release version 16.0.0-beta.22
[semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[semantic-release] â€º âœ”  Loaded plugin "verifyConditions" from "@semantic-release/github"
[semantic-release] â€º âœ”  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[semantic-release] â€º âœ”  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[semantic-release] â€º âœ”  Loaded plugin "prepare" from "@semantic-release/npm"
[semantic-release] â€º âœ”  Loaded plugin "publish" from "@semantic-release/npm"
[semantic-release] â€º âœ”  Loaded plugin "publish" from "@semantic-release/github"
[semantic-release] â€º âœ”  Loaded plugin "addChannel" from "@semantic-release/npm"
[semantic-release] â€º âœ”  Loaded plugin "success" from "@semantic-release/github"
[semantic-release] â€º âœ”  Loaded plugin "fail" from "@semantic-release/github"
[semantic-release] â€º âœ”  Run automated release from branch beta
[semantic-release] â€º âœ”  Allowed to push to the Git repository
[semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "@semantic-release/npm"
[semantic-release] [@semantic-release/npm] â€º â„¹  Verify authentication for registry https://registry.npmjs.org/
[semantic-release] [@semantic-release/npm] â€º â„¹  Wrote NPM_TOKEN to /home/travis/build/IBM/carbon-addons-iot-react/.npmrc
[semantic-release] â€º âœ”  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[semantic-release] â€º â„¹  Start step "verifyConditions" of plugin "@semantic-release/github"
[semantic-release] [@semantic-release/github] â€º â„¹  Verify GitHub authentication
[semantic-release] â€º âœ”  Completed step "verifyConditions" of plugin "@semantic-release/github"
[semantic-release] â€º â„¹  Found git tag v1.62.0-beta.1@beta associated with version 1.62.0-beta.1 on branch beta
[semantic-release] â€º â„¹  Found 2 commits since last release
[semantic-release] â€º â„¹  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[semantic-release] [@semantic-release/commit-analyzer] â€º â„¹  Analyzing commit: Merge pull request #340 from IBM/readme-update

docs(readme): update for beta, trigger breaking change
[semantic-release] [@semantic-release/commit-analyzer] â€º â„¹  The commit should not trigger a release
[semantic-release] [@semantic-release/commit-analyzer] â€º â„¹  Analyzing commit: docs(readme): update for beta

BREAKING CHANGE: trigger breaking change for beta release, updaded carbon deps too v10
[semantic-release] [@semantic-release/commit-analyzer] â€º â„¹  The release type for the commit is major
[semantic-release] [@semantic-release/commit-analyzer] â€º â„¹  Analysis of 2 commits complete: major release
[semantic-release] â€º âœ”  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[semantic-release] â€º â„¹  The next release version is 1.62.0-beta.2
[semantic-release] â€º â„¹  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[semantic-release] â€º âœ”  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[semantic-release] â€º â„¹  Start step "prepare" of plugin "@semantic-release/npm"
[semantic-release] [@semantic-release/npm] â€º â„¹  Write version 1.62.0-beta.2 to package.json in /home/travis/build/IBM/carbon-addons-iot-react
v1.62.0-beta.2
[semantic-release] â€º âœ”  Completed step "prepare" of plugin "@semantic-release/npm"
[semantic-release] â€º âœ”  Created tag v1.62.0-beta.2@beta
[semantic-release] â€º â„¹  Start step "publish" of plugin "@semantic-release/npm"
[semantic-release] [@semantic-release/npm] â€º â„¹  Publishing version 1.62.0-beta.2 to npm registry on dist-tag beta
...
[semantic-release] [@semantic-release/npm] â€º â„¹  Published carbon-addons-iot-react@1.62.0-beta.2 to https://registry.npmjs.org/
[semantic-release] â€º âœ”  Completed step "publish" of plugin "@semantic-release/npm"
[semantic-release] â€º â„¹  Start step "publish" of plugin "@semantic-release/github"
[semantic-release] [@semantic-release/github] â€º â„¹  Published GitHub release: https://github.com/IBM/carbon-addons-iot-react/releases/tag/v1.62.0-beta.2%40beta
[semantic-release] â€º âœ”  Completed step "publish" of plugin "@semantic-release/github"
[semantic-release] â€º â„¹  Start step "success" of plugin "@semantic-release/github"
[semantic-release] [@semantic-release/github] â€º â„¹  Added comment to issue #340: https://github.com/IBM/carbon-addons-iot-react/pull/340#issuecomment-504260201
[semantic-release] [@semantic-release/github] â€º â„¹  Added labels [ 'released' ] to issue #340
[semantic-release] â€º âœ”  Completed step "success" of plugin "@semantic-release/github"
[semantic-release] â€º âœ”  Published release 1.62.0-beta.2
```

## Environment

- **semantic-release** version: package.json `^16.0.0-beta.19`, CI env using `npx semantic-release@beta` above used `16.0.0-beta.22`
- CI environment: Travis CI
- Plugins used: (from CI output)
  - `verifyConditions` from `@semantic-release/npm`
  - `verifyConditions` from `@semantic-release/github`
  - `analyzeCommits` from `@semantic-release/commit-analyzer`
  - `generateNotes` from `@semantic-release/release-notes-generator`
  - `prepare` from `@semantic-release/npm`
  - `publish` from `@semantic-release/npm`
  - `publish` from `@semantic-release/github`
  - `addChannel` from `@semantic-release/npm`
  - `success` from `@semantic-release/github`
  - `fail` from `@semantic-release/github`

- **semantic-release** configuration: none. defaults from `npx semantic-release@beta`
- CI logs: [Travis CI specific build](https://travis-ci.org/IBM/carbon-addons-iot-react/builds/548479166), [Raw log](https://api.travis-ci.org/v3/job/548479167/log.txt)

**Comment by pvdlg** [comment] 2019-06-21 21:59
That seems to be the intended behavior.
You created your `beta` branch off of `master` when the last release was `v1.61.4`.
Then you push several commits to `beta`, the one associated with the highest release type being a `feat` (`feat(table): support passing selected ids from the outside for URL`) semantic-release determined the release type should `minor` and made the release `1.62.0-beta.1`.
Then as it's a prerelease branch each new release, no matter the type will increment the identifier (`1.62.0-beta.2`, then `1.62.0-beta.3`, then `1.62.0-beta.4`).

The way semantic-release handle prerelease versions is:
1. If the last version on the branch is not a prerelease (`1.61.4` is not a prerelease), then determine the release type (`minor` because of the `feat` commit), increment the last version number accordingly (`1.61.4` + `minor` = `1.62.0`) then add the prerelease identifier (`1.62.0` => `1.62.0-beta.1`) and make the release.
2. If the last release is a prerelease associated with the current prerelease identifier (`1.62.0-beta.1` is a prerelease associated with `beta`) then determine if a release should be done (commit with `BREAKING CHANGE` => yes), increment the identifier part of the last version (`1.62.0-beta.1` => `1.62.0-beta.2`) and make the release.

This behavior is what seems to create confusion.

Per the [documentation](https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/workflow-configuration.md#pre-release-branches):
> Using a pre-release version allow to publish multiple releases with the same version. Those release will be differentiated via their identifiers (in 1.0.0-alpha.1 the identifier is alpha.1). This is useful when you need to work on a future major release that will include many breaking changes but you do not want to increment the version number for each breaking change commit.

So prerelease allow to work on future version and make multiple changes without incrementing the version. This future version can be a major release or it can be a minor as well.

For example if your last release is `1.1.0`, you might want to work on a group of new features that you want to release under `1.2.0` (rather than `1.2.0` + `1.3.0` + `1.4.0`). Or you might want to release this group of feature as part of `2.0.0`.
In order for semantic-release to figure out in which of those case we are in, we use what I described above in `1.`. We look at the first push of commits on the branch since the last non prerelease release.
Because your first commit on `beta` since `1.61.4` was a `feat` semantic-release assume you want to work on version `1.62.0` and not `2.0.0`.

Then when you push a `BREAKING CHANGE` commit (or a `feat` or a `fix`) semantic-release increment only the identifier because this is the point of prerelease branches: `to work on a future major release that will include many breaking changes but you do not want to increment the version number for each breaking change commit`.

Hope that clarifies the situation.

**Comment by travi** [comment] 2019-06-23 02:38
> to work on a future major release that will include many breaking changes but you do not want to increment the version number for each breaking change commit

this is still the part that i think differs from what i would expect as well. 

i fully agree that you would not want a pre-release to increment the major version multiple times in the same pre-release, but i would expect it to increment it at least one (but at most once) if there is a `BREAKING CHANGE` anywhere in the series of commits in the pre-release branch. i think the same way when the first commit was only a patch-level change and there is a minor-level change introduced into the branch later.

however, currently if the first commit does not contain a `BREAKING CHANGE`, then the version number is only incremented as a minor or patch depending on the type of that first commit. if a more impactful change is committed to that branch later, i would expect the version number to be incremented to reflect the largest change in the branch and the pre-release identifier to be reset to zero. this then would align to the actual version that should be published once the branch is merged to master (outside of the case where master has changed, but merging master back into the branch should resolve this situation).

when not using semantic-release to manage the pre-release, you often have an idea of how impactful the pre-release is and set the version number portion to account for the maximum impact, even if the first commit isn't the most impactful change. i find myself sometimes trying to force my first commit of a pre-release to be a `BREAKING CHANGE` so that the pre-release versions better reflect the impact, but a huge part of the benefit of using semantic-release is to remove the need to put that much forward thought into the actual version incrementing. 

> Because your first commit on beta since 1.61.4 was a feat semantic-release assume you want to work on version 1.62.0 and not 2.0.0.

this is kind of the key piece to me. i don't want to think ahead about what i'm working on. i want semantic-release to figure that out for me based on the way ive described the commits i've made, just like i do with normal releases. ideally i should just describe the impact of each commit and let semantic-release handle the incrementing automatically. i've been absolutely loving the ability to manage pre-releases with semantic-release, but the current approach in this area still feels like it somewhat misses the mark of what seems natural to me.

**Comment by tay1orjones** [comment] 2019-06-24 16:35
>if a more impactful change is committed to that branch later, i would expect the version number to be incremented to reflect the largest change in the branch and the pre-release identifier to be reset to zero.

I very much agree here. Without this it feels quite unnatural to work on a prerelease (v1.62.0-beta.x) containing breaking changes, and then on merging of `beta` into `master` it bumps to version 2.0.0 due to the breaking change commit(s). This behavior is confusing for consumers as well testing prerelease versions of our package.

I couldn't find documentation explicitly stating that the first commit on a new branch determines the prerelease version identifier. That would've prevented me making this mistake. I can work on a PR for that documentation if desired.

In the meantime, is thereI can fix this on our package? A manual intervention to publish a 2.0.0-beta.1 release and tie future additions on our `beta` branch to increment the beta.x identifier forward via semantic-release?

**Comment by pvdlg** [comment] 2019-12-10 03:37
Would #1382 fix this issue?

The new behavior is as follow, assuming last release is `1.0.0`:
-  commit a `feat` => release `1.1.0-beta.1`
- commit a `fix` => release `1.1.0-beta.2`
- commit a `feat` => release `1.1.0-beta.3`
- commit a `BREAKING CHANGE` => release `2.0.0-beta.1` (that's what #1382 fixed)
- commit a `fix` => release `2.0.0-beta.2`
- commit a `fix` => release `2.0.0-beta.3`
- commit a `BREAKING CHANGE` => release `2.0.0-beta.4`

**Comment by travi** [comment] 2019-12-10 03:57
that aligns with my natural assumption. 

to clarify, i assume the list would be the same if preceded with a fix commit (except the beta increment, of course)

* commit a `fix` => release `1.0.1-beta.1`
* commit a `feat` => release `1.1.0-beta.2`
* commit a `fix` => release `1.1.0-beta.3`
* commit a `feat` => release `1.1.0-beta.4`
* commit a `BREAKING CHANGE` => release `2.0.0-beta.1` (that's what #1382 fixed)
* commit a `fix` => release `2.0.0-beta.2`
* commit a `fix` => release `2.0.0-beta.3`
* commit a `BREAKING CHANGE` => release `2.0.0-beta.4`

**Comment by pvdlg** [comment] 2019-12-10 05:18
It would be slightly different actually:
- commit a `fix` => release `1.0.1-beta.1`
- commit a `feat` => release `1.1.0-beta.1`  (and not `1.1.0-beta.2`)
- commit a `fix` => release `1.1.0-beta.2`  (and not `1.1.0-beta.3`)
- commit a `feat` => release `1.1.0-beta.3`  (and not `1.1.0-beta.4`)
- commit a `BREAKING CHANGE` => release `2.0.0-beta.1`
- commit a `fix` => release `2.0.0-beta.2`
- commit a `fix` => release `2.0.0-beta.3`
- commit a `BREAKING CHANGE` => release `2.0.0-beta.4`

I assumed it was a typo?

**Comment by travi** [comment] 2019-12-10 05:31
yep, that makes sense. wasn't a typo, but i wasnt thinking through it carefully enough. what you show would be correct :)

**Comment by pvdlg** [comment] 2019-12-10 05:36
Nice! I'll close the issue then!

**Closed by pvdlg** 2019-12-10 05:36 UTC

**Comment by ccrowley96** [comment] 2021-01-26 17:17
To achieve this behavior, do you need to merge the @latest release branch back into the beta branch after releasing?

**Comment by travi** [comment] 2021-01-26 17:49
yes. semantic-release is only able to analyze the commits that exist in the history of the branch

**Comment by ccrowley96** [comment] 2021-01-26 20:25
So is the best practice to merge back into beta after each release to ensure the tags are present in both branches?  Or is this only necessary if there's a difference in commit history between the branches?

**Comment by travi** [comment] 2021-01-26 21:53
it is up to you what strategy you wish to follow. the version numbers should communicate what changes are included in the release. if they do not include changes from releases that happened in another branch, the version number communicates that. 

the one thing that can be confusing about pre-releases is the version number before the pre-release segment. its a bit misleading that it states a specific version that it is a pre-release of, because you dont fully know, at the time of releasing the pre-release, what the latest version will be that you will bump from. therefore, it is better to think about the pre-release number in the other direction. this version includes the changes from the version before this, plus these pre-release features. if you merge the branch including changes from other releases, the version number then communicate effectively because the "changes from the version before this" has a different marker.

i understand that this doesnt make things super clear, but thats kind of the nature of semver in this scenario, and semantic-release does its best to align.

**Comment by ccrowley96** [comment] 2021-01-26 23:05
Thanks for the responses!  

I suppose I'm conflicted between setting up two release branches versus one release branch and one pre-release branch.

**Option A**
`release` - main channel `@latest`
`main` - pre-release branch `@beta`

- Allows for all changes in the pre-release branch to wrap up to a maximum of `MAJOR` version bump in `release`
- Requires back-merging `release` into `main` after each `@latest` release to reset the beta version.  ie. 2 PRs for each each release.
 
**Option B**
`release` - main channel `@latest`
`main` - release branch `@next`

- Multiple large / breaking changes in `main` will bump `@next` multiple major versions
- Does not require back merging `release` back into `main` as version number of `main` must always be greater than `release`

**Summary**
So if that made sense, and I'm understanding this correctly, those are the two options for setting up some sort of `@beta` / `@next` channel to release unstable code.

If that's the case, would it be possible to add a flag indicating that `pre-release` branch versions get reset once merging into the release branch?  It seems that strategy would be the best of both worlds.
