### ISSUE TITLE
Should we bump package.json version?

### ISSUE THREAD

**Issue by lirantal** [semantic-release/semantic-release#497] opened 2017-10-30 22:58 UTC
Great to see activity is back on this package ❤️ 
Much appreciated.

what would be the reason for semantic-release not bumping the version in `package.json` and commit & push it to the repo?
for projects which don't publish to an npm repository (like node.js frontend/backend frameworks), it is convenient to read the `package.json` file and extract the version from it in order to report or log it.

**Comment by gr2m** [comment] 2017-10-31 00:03
That is currently out of scope.

But good news is that @pvdlg is looking into making the publish step pluggable in semantic-release via https://github.com/semantic-release/semantic-release/issues/484. Once we have that, I could imagine that you could drop the npm publish step entirely and add a custom release step which writes the current version to package.json with an extra commit.

I'd suggest to watch #484 for now :)

**Comment by lirantal** [comment] 2017-10-31 06:33
yeah I saw that issue and the work discussed there, but is there really a connection between the npm publish and the saving the new version in package.json?

**Comment by gr2m** [comment] 2017-11-01 06:42
`semantic-release` calculates the version and writes it into the `package.json` file before running `npm publish`. So it is set on the package published to the npm registry, but the version is not part of your source code.

**Comment by lirantal** [comment] 2017-11-01 07:14
Sure, I understand that. Although what is the reason for not updating package.json and commiting the change?

**Comment by pvdlg** [comment] 2017-11-01 07:29
Would [this answer](https://github.com/semantic-release/semantic-release#why-is-the-packagejsons-version-not-updated-in-my-repository) in our FAQ address your question? 

If it's not clear let us know and we'll try to clarify as much as possible !

**Comment by pvdlg** [comment] 2017-11-01 07:37
To add a bit more information, this is mostly because it's unnecessary. There is just no particular reason to push the version in the repo. So it's not necessary to create a commit, that would not add any additional info in the commit history (we already have tags).

Doing this commit from the CI would also come with additional complexity:
- Permission
- Handling the CI job that would be triggered by this new commmit
- Having a cloned repo to be able to do the commit (some CI do not provide a clone but a detached head)

**Comment by lirantal** [comment] 2017-11-01 08:24
The FAQ doesn't convey the "why", it just states what is happening.

I agree with the use of tags, but I think the "complexity" part of the CI is a technical gap, not really a reason not do it. Thing is, maintaining a project's version in `package.json` is a common thing for the ecosystem (even for projects that don't ship to npmjs).

If you are somewhat leaning towards my idea here, then I can suggest that instead of commiting directly, instead we can create a PR with the relevant changes (i.e: update the package.json with the new version, update a changelog file for example), etc. It will require a manual step of approve and merge which will effectively tag a new version.
Or does it throw you off because it's not automatic anymore? :-)

**Comment by pvdlg** [comment] 2017-11-01 15:45
That would be a lot of modifications and code to maintain for something that is not necessary. It might be a common thing in the ecosystem, but if it's not necessary I'm not really sure it worth investing the resources. At least not for the maintainer team in the near future.

That said, once #484 is implemented, it will probably be possible to create a plugin to achieve that (and maybe even pushing a `CHANGELOG.md` to the repo).

**Comment by gr2m** [comment] 2017-11-01 16:06
@lirantal can you explain your use case a bit more? semantic-release has been around for over 2 years now, and so far the only problem with a missing version on github was that people couldn't install dependencies from their forks, which we fixed by adding a `0.0.0-development` placeholder

**Comment by lirantal** [comment] 2017-11-02 09:45
If the npm client is any model to look up to, then if you do `npm version patch` it will:
1. update `package.json` to a new patch version
2. commit the change on the repo
3. create the tag

Regardless though, updating the version in `package.json` is even more important for Node.js projects which aren't pushed to a repository. Consider the following - a project could be a framework, which doesn't get pushed to npm as a library, but rather maintain on github as a source. If you don't maintain versioning in `package.json` then if a user wants to report a bug, how does he find which version they're on? maybe they can specify the commit hash, or check the tag they fetched originally - but none of this is a straightforward solution.

My own personal use case is that I read the currently deployed version of a Node.js API service from the `packge.json` file.

Maybe this is out of scope for semantic-release.

**Comment by thezimmee** [comment] 2017-11-03 01:43
I am just starting to use semantic-release, but the use case that @lirantal explained pretty closely describes the issue I am running into. I am creating a framework and use the version field of `package.json` to put into my distributed files. I just added semantic-release to the workflow, and now all of the distributed files have `v0.0.0-development` in them.

I would certainly like my distributed files to show the version that a user is using. Does anybody have any suggestions for how to handle this? Using semantic-release, how do I get the version for a build to put into my distributed files?

**Comment by pvdlg** [comment] 2017-11-03 02:08
@thezimmee that's a different issue you are having.
The problem is that your build step (what put the version is in your distrib files) probably runs before `semantic-release`, so the version is not in the `package.json` yet.

The solution is to setup those script to be run in the npm `prepublishOnly` script like this:
```json
"scripts": {
  "prepublishOnly": "prepare-dist-files",
  ...
}
```

The script `prepare-dist-files` will runs after `sematic-release` update the version in `package.json` and before `npm publish` (so the updated dist files will be included in the package published on npm)

**Comment by thezimmee** [comment] 2017-11-03 03:41
@pvdlg Thank you for your help, much appreciated! You are correct that my build step (`npm run build`) currently runs before semantic-release. I have a `prepush` githook that runs the build locally in order to make sure tests pass and the build completes successfully before pushing anything to github.

Just trying to think this through, so I think what you're suggesting is something like this:

1. Only npm truly needs the dist files and not source control, which means I can...
2. ...add dist files to `.gitignore`,
3. and run the build in the `prepublishOnly` script (`"prepublishOnly": "npm run build"` in my case).
4. Doing so will publish the dist files to npm via semantic-release/travis ci.

Sound about right? My assumption is that if I `.gitignore` the dist files, they will still be published to npm, so long as they are not in `.npmignore`, is that correct?

Based on all this, it doesn't seem like there is a great way to get my dist files into github / source control (with the correct version), or am I wrong? Does/should this even matter? I can't think of a great reason why it does matter, though it makes me a little hesitant to have the dist files be so automated... I appreciate any thoughts you or anybody might have.

**Comment by thezimmee** [comment] 2017-11-03 04:20
> My assumption is that if I .gitignore the dist files, they will still be published to npm, so long as they are not in .npmignore, is that correct?

Per [npm docs](https://docs.npmjs.com/files/package.json):

> The .npmignore file works just like a .gitignore. If there is a .gitignore file, and .npmignore is missing, .gitignore's contents will be used instead.
>
> Files included with the "package.json#files" field cannot be excluded through .npmignore or .gitignore.

So it looks if I `.gitignore` the dist folder I would need to make sure to have either 1) an `.npmignore` file, or 2) a `files` property in `package.json` to ensure the dist files get published to npm.

Any suggestions on the rest of [my questions/comments](https://github.com/semantic-release/semantic-release/issues/497#issuecomment-341616641) are much appreciated.

**Comment by pvdlg** [comment] 2017-11-03 05:35
> Just trying to think this through, so I think what you're suggesting is something like this:
> 1. Only npm truly needs the dist files and not source control, which means I can...
> 2. ...add dist files to `.gitignore`,
> 3. and run the build in the `prepublishOnly` script (`"prepublishOnly": "npm run build"` in my case).
> 4. Doing so will publish the dist files to npm via semantic-release/travis ci.

Yes. You would also have to add the `files` property in your `package.json` to include your dist files in the npm package (just add the path of the folder that contains the dist files.). See [package.json#files](https://docs.npmjs.com/files/package.json#files).
Doing so has also other advantages:
- You can get rid of the `.npmignore` file
- You add new files in your repo you don't have to remember to add them to `.npmignore` as they will be excluded due to not being present in `files`.

> Sound about right? My assumption is that if I .gitignore the dist files, they will still be published to npm, so long as they are not in .npmignore, is that correct?

No, as npm also ignores what's in the `.gitignore`. Adding the `files` property to the `package.json` will solve that.

> Based on all this, it doesn't seem like there is a great way to get my dist files into github / source control (with the correct version), or am I wrong? Does/should this even matter?

No there is no easy way at the moment to push your dist files if they are built with the version number.
It probably doesn't matter, unless you want users to download them directly from Github instead of installing your package with npm. In order to solve this situation we plan in a future release to allow to push files to the github release (see #484). It's a much cleaner way to make your dist files available for download than pushing them to the repo as they are more easily identifiable as the final product and users can download any version they want.

> it makes me a little hesitant to have the dist files be so automated...

In your current workflow the dist file are built on your local machine by your build script. In the proposed scenario they are built on the CI by the same script. So in the end it's the same script that build your dist files, so it's really more automated than before, it just run at a different time.
You can keep your `prepush ` hook in order to check the build work locally before pushing. But if for some reason the build fail on the CI, the package won't be published on npm registry and the `semantic-release` will stop right there and report the error.

**Comment by thezimmee** [comment] 2017-11-03 05:56
@pvdlg Thank you for helping me think it through!

**Comment by destroyerofbuilds** [comment] 2017-11-09 22:40
Just noting a similar issue has been posted against `semantic-release-gitlab` - https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/26

I bring that up because I want to make sure I'm following the same best practices in `semantic-release-gitlab` as `semantic-release`.

**Comment by lirantal** [comment] 2017-11-12 18:50
right, so where do we stand on bumping the version in package.json? :-)

**Comment by gr2m** [comment] 2017-11-19 23:21
@lirantal still at https://github.com/semantic-release/semantic-release/issues/497#issuecomment-340620440, but @pvdlg is doing great progress, stay tuned. We will announce all relevant news in this issue: https://github.com/semantic-release/semantic-release/issues/411 if you haven’t yet I’d recommend you all to subscribe to this one

**Comment by lirantal** [comment] 2017-11-20 01:09
Cool, thanks!

**Comment by felixfbecker** [comment] 2017-11-22 07:48
One point I would like to comment on:

>  Thing is, maintaining a project's version in package.json is a common thing for the ecosystem (even for projects that don't ship to npmjs).

Composer is an example of a package manager that has a `version` field in composer.json, but it is optional and actively discouraged from being used, because git tags should be the source of truth for this, which I agree with.

> Optional if the package repository can infer the version from somewhere, such as the VCS tag name in the VCS repository. In that case it is also recommended to omit it.
>
> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

https://getcomposer.org/doc/04-schema.md#version

**Comment by lirantal** [comment] 2017-11-22 09:42
You keep citing examples of why to avoid versioning in package.json, but I didn't see even one recommended way of solving the use-case I'm referring to :-)

**Comment by felixfbecker** [comment] 2017-11-22 09:45
@lirantal maybe I'm missing something, but for what use case do git tags not work?

**Comment by fenduru** [comment] 2017-11-28 16:41
Ultimately the contents of `package.json` are used to describe the information that is needed for the package manager to deal with that package, and tooling around `package.json` should be able to safely rely on that.

@felixfbecker An example of this is [Yarn's workspaces feature](https://yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats), whose behavior differs based on the version listed in package.json.

This project is already manipulating SCM by adding/pushing a tag, so it seems like there shouldn't be an issue pushing a commit from CI.

Historically my release workflow (and I'm sure this is true for most other projects) has been to manually bump package.json, commit, tag, push, `npm publish`. I think creating tooling to automate processes like this is great for reducing efforts and human error, but I don't think doing so should require going against longstanding conventions.

**Comment by pvdlg** [comment] 2017-11-28 17:01
A `git` plugin is in the work with:
- Create a release commit (optionally gpg signed)
- Generate/update a `CHANGELOG.md`
- Commit `package.json` if it was updated by a previous plugin / script (like the `npm` plugin does)
- Commit a configurable list of files (like a `dist` directory etc..)
- Create the git tag

More to come in the following days/weeks

**Comment by pvdlg** [comment] 2017-12-04 20:37
This feature has been implemented via the  plugin https://github.com/semantic-release/git

**Closed by pvdlg** 2017-12-04 20:37 UTC

**Comment by felixfbecker** [comment] 2017-12-04 20:40
@pvdlg should semantic-release/last-release-git-tag be deprecated? Seems like the git plugin provides a superset of the functionality

**Comment by pvdlg** [comment] 2017-12-04 20:41
Yes it will be deprecated soon

**Comment by Robbie-Cook** [comment] 2021-01-08 01:34
I may have missed this in this convo, but there is a plugin to bump the package.json version now: https://github.com/semantic-release/npm .

thanks Semantic Release team!
