### ISSUE TITLE
A way to terminate to release step with an exit code

### ISSUE THREAD

**Issue by sybrendotinga** [semantic-release/semantic-release#1331] opened 2019-10-22 12:40 UTC
## Current behavior

Our Jenkins pipeline continues deployment when there is no new release. 

## Expected behavior

I would like to 'terminate' the process with an exit code when there is no new release. Or otherwise let the CI know that it should not continue with the next step. 

## Environment
- **semantic-release** version: "^16.0.0-beta.22" 
- CI environment: Jenkins
- Plugins used: 
```
{
    "@semantic-release/changelog": "^3.0.2",
    "@semantic-release/commit-analyzer": "^6.1.0",
    "@semantic-release/exec": "^3.4.0-beta.2",
    "@semantic-release/git": "^7.1.0-beta.3",
    "@semantic-release/release-notes-generator": "^7.1.4"
}
```

- **semantic-release** configuration:
```
{
  plugins: [
    '@semantic-release/commit-analyzer',
    [
      '@semantic-release/release-notes-generator',
      {
        linkCompare: false,
        linkReferences: false
      }
    ],
    [
      '@semantic-release/changelog',
      {
        changelogTitle: '# CHANGELOG',
        changelogFile: 'CHANGELOG.md'
      }
    ],
    [
      '@semantic-release/exec',
      {
        publishCmd: 'yarn publish --new-version=${nextRelease.version} --no-git-tag-version'
      }
    ],
    [
      '@semantic-release/git',
      {
        assets: ['README.md', 'CHANGELOG.md', 'package.json', 'yarn.lock']
      }
    ]
  ]
}
```

- CI logs: 
```
[11:51:45] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.22
[11:51:46] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[11:51:46] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:51:46] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:51:46] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[11:51:46] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[11:51:46] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[11:52:09] [semantic-release] › ✔  Run automated release from branch develop
[11:52:09] [semantic-release] › ✔  Allowed to push to the Git repository
[11:52:09] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[11:52:09] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[11:52:09] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[11:52:09] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[11:52:09] [semantic-release] › ℹ  Found git tag v1.0.0-develop.97@dev associated with version 1.0.0-develop.97 on branch develop
[11:52:09] [semantic-release] › ℹ  Found 2 commits since last release
[11:52:09] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:52:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: refactor(detail view): *****
[11:52:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:52:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: refactor(navigation path): *****
[11:52:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[11:52:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: no release
[11:52:09] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:52:09] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[11:52:09] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[11:52:09] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

**Comment by pvdlg** [comment] 2019-10-22 16:09
This is the intended behavior. If no release is needed we don't want to make the CI fail as it's not an error or an unexpected thing.
Sometimes the commits added since the last release do not warrant a release and that's normal. We don't that situation to trigger alarm, or block PRs by failing the CI process.

What are you trying to achieve? What next step are you trying to prevent?

**Comment by sybrendotinga** [comment] 2019-10-23 09:46
We use semantic release (in this case) to determine the next version for a project, not a package.

We would like to let a server know that a new release of the project is available, when there is a new release available, or otherwise skip the next step.

Steps:
- Install packages
- Test
- Build
- Deploy a package with a new version
- Let the server know what the new version is of the project 

We would like this step to be optional (skipped) when there is no new version.

**Comment by pvdlg** [comment] 2019-10-23 15:32
You could use the `success` plugin step. This will be called only after a release is made and you will have access to a lot of info regarding the release.

You can create a plugin that implement the `success` hook or you can use the `@seamtnic-release/exec` plugin to run a command.

**Comment by pvdlg** [comment] 2019-11-06 22:19
Closing as no answer was provided

**Closed by pvdlg** 2019-11-06 22:19 UTC
Labels: info requested
