### ISSUE TITLE
beta branch pre-release count isn't updating

### ISSUE THREAD

**Issue by bradbarrow** [semantic-release/semantic-release#1146] opened 2019-04-12 00:18 UTC
## Current behavior

I have the following dependencies

I am not providing any `.releaserc` or similar config - but am relying on the defaults. 

I pushed a `beta` branch with my commits from master that are currently released at `v9.0.0` and **one additional** `feat` commit to add the new semantic release versions.

This correctly pushed a tag to git (`v9.1.0-beta.1@beta`) and a release to npm (`9.1.0-beta.1`).

Then I pushed more `feat` commits to the beta branch. 

From my CI:

```
[23:42:56] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
--
  | [23:42:56] [semantic-release] › ℹ  Found git tag v9.0.0 associated with version 9.0.0 on branch beta
  | [23:42:56] [semantic-release] › ℹ  Found 3 commits since last release
  | [23:42:56] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: use beta plugins
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: try defaults and beta plugins
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: configure beta publishing
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
  | [23:42:56] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 3 commits complete: minor release
  | [23:42:56] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
  | [23:42:56] [semantic-release] › ℹ  The next release version is 9.1.0-beta.1
  | [23:42:56] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  | [23:42:56] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  | [23:42:56] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
  | [23:42:56] [semantic-release] [@semantic-release/npm] › ℹ  Write version 9.1.0-beta.1 to package.json in /app
  | v9.1.0-beta.1
  | [23:42:56] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
  | [23:42:56] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git tag v9.1.0-beta.1@beta 147f267185453984626a27126bf4c141b8f4f5c1
  | fatal: tag 'v9.1.0-beta.1@beta' already exists

```

## Expected behavior

I expected it to find the previous beta tag, and then release `v9.1.0-beta.2@beta`

## Environment

- **semantic-release** version: ^16.0.0-beta.18
- CI environment: Build Kite
- Plugins used: 

```
"@semantic-release/commit-analyzer": "7.0.0-beta.1"
"@semantic-release/error": "2.2.0"
"@semantic-release/github": "5.3.0-beta.6"
"@semantic-release/npm": "5.2.0-beta.5"
"@semantic-release/release-notes-generator": "7.1.2"
```

- **semantic-release** configuration: defaults only
- CI logs: Private

**Comment by travi** [comment] 2019-04-12 21:42
this line suggests that the tag for the previous beta version did not get added to your repository:
> | [23:42:56] [semantic-release] › ℹ  Found git tag v9.0.0 associated with version 9.0.0 on branch beta

i've been having this work properly on my projects, so i would try to investigate what could be preventing the tags from being pushed back to your repository

**Comment by JGiesen-JDI** [comment] 2019-05-14 20:38
Same result here, maybe these debug messages help.

get-tags found tags: [ { gitTag: 'v1.0.0', version: '1.0.0', channel: undefined }, { gitTag: 'v1.0.1-develop.1@develop', version: '1.0.1-develop.1', channel: 'develop' } ]
get-tags found tags for branch master: [ { version: '1.0.0', channel: undefined, gitTag: 'v1.0.0', gitHead: '6ee1a930c2dae74ed62354b114ba55f04fc5519e' } ]
get-tags found tags for branch develop: [ { version: '1.0.0', channel: undefined, gitTag: 'v1.0.0', gitHead: '6ee1a930c2dae74ed62354b114ba55f04fc5519e' } ]`
...

fatal: tag 'v1.0.1-develop.1@develop' already exists

trying to "fix" two commits one after the other on "develop" branch, the second time it fails

**Comment by germanattanasio** [comment] 2019-05-15 17:27
What happens in my case is that the commit is part of the tag but not part of `master` so semantic-release never finds the latest tag and I have to manually merge the tag to master in order to fix it.

I think this is some sort of problem in the way the plugins are order.

Here is my config
```json

{
  "branch": "master",
  "verifyConditions": [],
  "prepare": [
    {
      "path": "@semantic-release/exec",
      "cmd": "bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --allow-dirty patch"
    }
  ],
  "publish": [
    {
      "path": "@semantic-release/github",
    }
  ]
}
```
I use `bumpversion` to update the version in the README and other static assets and then I expect that commit to be part of `master` but it's not :(

**Comment by JGiesen-JDI** [comment] 2019-05-15 18:18
Got it working with a workaround:
- git checkout $GIT_BRANCH (jenkins)
- git fetch --tags
- git pull origin $GIT_BRANCH

- run semantic-release

I believe it has to do with Jenkins pulling the commit into headless state. Seems like it's working but I haven't checked all cases yet.

**Comment by travi** [comment] 2019-05-15 18:52
> the commit is part of the tag but not part of master so semantic-release never finds the latest tag and I have to manually merge the tag to master in order to fix it

i'm confused about this. the original problem, if i understand correctly, was about additional commits to an existing pre-release branch. when you mention things missing from `master` impacting your pre-release branch, do you mean that the things that are missing from `master` are from a previous branch that was merged to `master`? if so, did you merge in a way that would rewrite history, like rebasing or squashing? rewriting history before merging to `master` would prevent the tag from ending up in `master`, but a standard merge should put the tag into `master` because the referenced commit is then in `master`

> and then I expect that commit to be part of master but it's not 😢

if you are making commits as part of your release that you want to end up in your repository and not lost after the build completes, you need to configure the [git plugin](https://github.com/semantic-release/git)

**Comment by germanattanasio** [comment] 2019-05-15 21:03
Hi @travi I think the problem is that `bumpversion` commits a change but that commit ends up in a tag rather than in the `master` branch. I will add the `git` plugin to the `prepare` stage and see if that fixes it

**Comment by travi** [comment] 2019-05-15 21:09
> bumpversion commits a change but that commit ends up in a tag rather than in the `master` branch

i don't understand what you mean by that. git tags are pointers to specific git revisions, so there is no such thing as a tag that is not a commit. if a commit that is pointed to by a tag gets merged into `master`, that tag still points to the commit in `master`. however, if that commit is rewritten in a way that the hash is changed, the tag will no longer point to the (new) commit because it is no longer seen by git as the same commit.

**Comment by germanattanasio** [comment] 2019-05-16 17:52
I fixed the problem by adding the `git` plugin as part of `prepare. I think that maybe the commits from `bumpversion` were not being pushed back to the main repo and adding the `git` plugin fixed it.

After re-reading your comment @travi I spent some time trying to understand commits and tags and found that what I was saying didn't make sense 😛 

Thanks for your help.

**Comment by semoal** [comment] 2019-06-10 16:49
@germanattanasio i'm getting the same issue. The last number in the pre-release branch is not getting updated.
Do you have any hint mate?

```{
	"branches": [
		"master",
		{
			"name": "canary",
			"prerelease": true
		}
	],
	"plugins": [
		"@semantic-release/commit-analyzer",
		"@semantic-release/npm",
		"@semantic-release/release-notes-generator",
		"@semantic-release/changelog",
		{
			"path": "@semantic-release/git",
			"assets": [
				"package.json",
				"CHANGELOG.md"
			],
			"message": "chore(release): ${nextRelease.version} [skip ci]nn${nextRelease.notes}"
		},
		[
			"@semantic-release/npm",
			{
				"npmPublish": true
			}
		]
	]
}```

**Comment by pvdlg** [comment] 2019-09-24 21:01
Sorry for the late. It seems this problem is solved?
If not please open a new issue with all the necessary details, in particular logs of a run with the latest semantic-release version.

**Closed by pvdlg** 2019-09-24 21:01 UTC
