### ISSUE TITLE
`npm publish` works, but `semantic-release pre` fails with 401

### ISSUE THREAD

**Issue by ianrossi** [semantic-release/semantic-release#339] opened 2016-12-06 20:22 UTC
Thx for your efforts with semantic-release. I'm using version 6.3.2.

I am working on a CD pipeline with Jenkins, Docker, Nexus and npm. I'm currently having a problem with semantic-release. What I want to be able to do is:
- Establish the proper NPM configuration in my Github SCM
- Have Jenkins pull that configuration when a new release is merged to master
- Have Jenkins use the committed NPM configuration to interface with my private NPM repo in Nexus

It seems like semantic-release is modifying my project's working and tested .npmrc file when run by Jenkins, which causes a 401 error when connecting to Nexus.

I'm able to do a successful `npm publish` after modifying the project `.npmrc` to look like the following:
```
_auth="redactedXXXXXXXXXXXXXX"
email=Ian_Rossi@XXXX.com
always_auth=true
#//haproxy0-useast1a.lab4.XXXXX.io/repository/npm-internal/:_authToken=${NPM_TOKEN}
```
I am unsure why I need to comment out the last line. I believe that line was generated with `npm login --registry http://haproxy0-useast1a.lab4.XXXXX.io/repository/npm-internal/`. I believe it also placed the env var that I have at `$NPM_TOKEN`.

The problem occurs when, after successfully doing `npm publish` to the Nexus NPM private repo, I try `npm run semantic-release` and I get:
```
➜  devops-demo-app git:(master) ✗ npm run semantic-release

> @cc/devops-demo-app@0.0.0-development semantic-release /home/ianrossi/devops-demo-app
> semantic-release pre && npm publish && semantic-release post

semantic-release WARN pre semantic-release didn’t run on Jenkins CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre E401 401 Unauthorized Error: 401 Unauthorized
semantic-release ERR! pre     at makeError (/home/ianrossi/devops-demo-app/node_modules/npm-registry-client/lib/request.js:304:12)
semantic-release ERR! pre     at RegClient.<anonymous> (/home/ianrossi/devops-demo-app/node_modules/npm-registry-client/lib/request.js:255:9)
semantic-release ERR! pre     at Request._callback (/home/ianrossi/devops-demo-app/node_modules/npm-registry-client/lib/request.js:212:14)
semantic-release ERR! pre     at Request.self.callback (/home/ianrossi/devops-demo-app/node_modules/request/request.js:186:22)
semantic-release ERR! pre     at emitTwo (events.js:106:13)
semantic-release ERR! pre     at Request.emit (events.js:191:7)
semantic-release ERR! pre     at Request.<anonymous> (/home/ianrossi/devops-demo-app/node_modules/request/request.js:1081:10)
semantic-release ERR! pre     at emitOne (events.js:96:13)
semantic-release ERR! pre     at Request.emit (events.js:188:7)
semantic-release ERR! pre     at IncomingMessage.<anonymous> (/home/ianrossi/devops-demo-app/node_modules/request/request.js:1001:12)

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "semantic-release"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @cc/devops-demo-app@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cc/devops-demo-app@0.0.0-development semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @cc/devops-demo-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @cc/devops-demo-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @cc/devops-demo-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ianrossi/devops-demo-app/npm-debug.log
```
and then the project's `.npmrc` file has been changed to:
```
_auth="redactedXXXXXXXXXX="
email=Ian_Rossi@XXXX.com
always_auth=true
//haproxy0-useast1a.lab4.XXXXX.io/repository/npm-internal/:_authToken=${NPM_TOKEN}
```
where the last line is now uncommented, which breaks `npm publish`. Now any subsequent `npm publish` command will also break with a 401 error. I don't undertstand enough of SR's internals to know why it is modifying the project `.npmrc` when I have it working properly.  One time, after doing a `npm run semantic-release`, the following was in `.npmrc`:
```
_auth="redactedXXXXXXXXXX="
email=Ian_Rossi@XXXX.com
always_auth=true
//haproxy0-useast1a.lab4.XXXXX.io/repository/npm-internal/:_authToken=${NPM_TOKEN}
//haproxy0-useast1a.lab4.XXXXX.io/repository/:_authToken=redacted-XXXX-XXXX-XXXX-XXXX
```
adding an additional repo and token, but it's not even the right one--it cut off the last piece of the repo URL.

Here is `package.json`:
```
{
  "name": "@cc/devops-demo-app",
  "version": "0.0.0-development",
  "description": "",
  "main": "index.js",
  "release": {
    "branch": "master",
    "verifyConditions": {
      "path": "./node_modules/@krux/condition-jenkins"
    }
  },
  "scripts": {
    "start": "forever start app.js",
    "stop": "forever stopall",
    "test": "jenkins-mocha test/*",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "publishConfig": {
    "registry": "http://haproxy0-useast1a.lab4.XXXX.io/repository/npm-internal/",
    "access": "restricted"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0"
  },
  "devDependencies": {
    "@krux/condition-jenkins": "^1.0.1",
    "forever": "^0.15.3",
    "jenkins-mocha": "^3.0.4",
    "semantic-release": "^6.3.2",
    "semantic-release-cli": "^3.0.2",
    "should": "^8.3.0",
    "supertest": "^1.2.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/XXXXX/devops-demo-app.git"
  }
}

```
Here is also the Jenkins failed job output:
```
Started by GitHub push by Ian-Rossi-aimtheory
Building in workspace /var/jenkins_home/workspace/node-pipeline-feature-deploy
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@redacted/devops-demo-app.git # timeout=10
Fetching upstream changes from git@github.com:redacted/devops-demo-app.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress git@github.com:Bredacted/devops-demo-app.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 3aec2d5811a121ae87ba3fc312ca03aa24ecd5b0 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 3aec2d5811a121ae87ba3fc312ca03aa24ecd5b0
 > git rev-list 5b6e61e930c1813ea9efc7cda2d110b5b8a6cb90 # timeout=10
 > git describe --tags 3aec2d5811a121ae87ba3fc312ca03aa24ecd5b0 # timeout=10
Tag information could not be determined for this revision; no git tag info will be exported
[node-pipeline-feature-deploy] $ /bin/sh -xe /tmp/hudson5048218256664215289.sh
+ export CI=true
+ export NPM_NEXUS_AUTH=redacted=
+ export GH_TOKEN=redacted
+ export NPM_TOKEN=redacted
+ npm install
+ npm run semantic-release

> @cc/devops-demo-app@0.0.0-development semantic-release /var/jenkins_home/workspace/node-pipeline-feature-deploy
> semantic-release pre && npm publish && semantic-release post

semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre E401 401 Unauthorized Error: 401 Unauthorized
semantic-release ERR! pre     at makeError (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/lib/request.js:304:12)
semantic-release ERR! pre     at RegClient.<anonymous> (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/lib/request.js:255:9)
semantic-release ERR! pre     at Request._callback (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/lib/request.js:212:14)
semantic-release ERR! pre     at Request.self.callback (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/node_modules/request/request.js:186:22)
semantic-release ERR! pre     at Request.emit (events.js:98:17)
semantic-release ERR! pre     at Request.<anonymous> (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/node_modules/request/request.js:1081:10)
semantic-release ERR! pre     at Request.emit (events.js:95:17)
semantic-release ERR! pre     at IncomingMessage.<anonymous> (/var/jenkins_home/workspace/node-pipeline-feature-deploy/node_modules/semantic-release/node_modules/@semantic-release/last-release-npm/node_modules/npm-registry-client/node_modules/request/request.js:1001:12)
semantic-release ERR! pre     at IncomingMessage.g (events.js:180:16)
semantic-release ERR! pre     at IncomingMessage.emit (events.js:117:20)

npm ERR! Linux 3.13.0-101-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "semantic-release"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @cc/devops-demo-app@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cc/devops-demo-app@0.0.0-development semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! This is most likely a problem with the @cc/devops-demo-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @cc/devops-demo-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls @cc/devops-demo-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/jenkins_home/workspace/node-pipeline-feature-deploy/npm-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by ianrossi** [comment] 2016-12-07 17:39
I'm closing this, since I was able to get past the 401 error by just [just activating the NPM Bearer Token realm in Nexus](https://books.sonatype.com/nexus-book/3.0/reference/npm.html#_npm_security).

**Comment by sirJconny** [comment] 2017-04-26 14:38
Hey @ianrossi , I am running into some trouble setting up my deployment pipeline too. It seems like I am relatively close to your error. I do have n initial question: what do you do with the GH_TOKEN and NPM_TOKEN generated from the cli setup? Thanks.

**Comment by Ian-Rossi-aimtheory** [comment] 2017-04-26 14:50
@sirJconny Sorry I can't help with this, I abandoned semantic_version for https://github.com/fmahnke/shell-semver. Was much easier to work with and can be used across applications of different languages.

**Comment by pvdlg** [comment] 2017-12-04 20:38
Is it still happening with the last version of `semantic-release`?

**Comment by pvdlg** [comment] 2017-12-16 20:32
Closing for now. Please re-open if the problem is still happening.

**Closed by pvdlg** 2017-12-16 20:32 UTC
Labels: awaiting response
