### ISSUE TITLE
Pre-release discussion

### ISSUE THREAD

**Issue by ryan-kimber** [semantic-release/semantic-release#207] opened 2016-03-26 19:35 UTC
I'd like to be able to use semantic-release to automatically version and publish pre-releases when we merge to the develop branch, and to publish releases when we merge to master. 

It doesn't seem as though semantic-release has been built with this use case in mind, which makes me wonder if this a poor idea. 

I'm looking for some feedback on this idea, and would be happy to create a pull-request to add the feature if there's support for it.

**Comment by tusharmath** [comment] 2016-03-27 03:54
I would rather use npm dist tags, which semantic release has awesome
support for.

On Sun, Mar 27, 2016, 1:05 AM Ryan Kimber <notifications@github.com> wrote:

> I'd like to be able to use semantic-release to automatically version and
> publish pre-releases when we merge to the develop branch, and to publish
> releases when we merge to master.
>
> It doesn't seem as though semantic-release has been built with this use
> case in mind, which makes me wonder if this a poor idea.
>
> I'm looking for some feedback on this idea, and would be happy to create a
> pull-request to add the feature if there's support for it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/semantic-release/semantic-release/issues/207>
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by ryan-kimber** [comment] 2016-03-27 03:59
Is there a way to use dist tags without manually editing the package.json?
We'd like to have our versioning tied to the branch and not have developers
making manual changes to package.json.

**Comment by tusharmath** [comment] 2016-03-27 10:15
I would rather create a dist-tag `next` and whenever the code is merged into  master I would release it on that tag. So by default everything is released on `next`. Once you are comfortable with a particular release and find it stable you can add the `latest` dist tag on it.

The advantage I get from this setup is that I don't need to create a new release per say when something is marked as `latest`.

**Comment by ryan-kimber** [comment] 2016-03-27 18:12
So, how about a command-line option for the tag? That way our CI scripts
can easily change the tag without having to alter the package.json config
section.

**Comment by tusharmath** [comment] 2016-03-28 06:03
`dist-tags` are read by npm from package.json at the time of publishing so I highly doubt we can make it dynamic, unless we write a script like yours above.

Why does the `branch` option not work for you— https://github.com/semantic-release/semantic-release#options?

**Comment by ryan-kimber** [comment] 2016-03-28 17:35
The branch option is working well. 

Where I ended up wasting a lot of time is trying to figure out how to use pre-release tags, and I guess what we're saying is that pre-release tags aren't supported (at least as it currently stands) and aren't recommended practice.

How about working that into the landing README.md? (I'll be happy to do it)

**Comment by tusharmath** [comment] 2016-03-29 04:15
[0]: https://github.com/orgs/semantic-release/people
I too think these things should be documented as its not obvious to people who are just getting started with automating their releases, would love to know what the [owners][0] think about it.

**Comment by felixfbecker** [comment] 2017-10-31 07:33
What's the recommended approach if the package manager does not support dist tags / release channels but only prereleases?

**Comment by gr2m** [comment] 2017-11-01 06:35
@felixfbecker can you explain what you mean with "if the package manager does not support dist tags"? The current `semantic-release` is pretty much bound to npm right now

**Comment by felixfbecker** [comment] 2017-11-01 06:36
I am using it successfully with Composer, which does not support dist tags, but prereleases.

**Comment by gr2m** [comment] 2017-11-01 06:40
I guess that is out of scope for semantic-release at this point. I know that Pierre is looking into making the "publish" step pluggable so you can build a semantic-release publish plugin for Composer. I would imagine that could set any settings you want in package.json for your plugin, it will be passed through. 

But until that is done, I don't think other package managers are within the scope of semantic-release

**Comment by felixfbecker** [comment] 2017-11-01 06:52
Why is that out of scope? The current version works by running `semantic-release pre && npm publish && semantic-release post`. You can put any arbitrary command instead of `npm publish` in there, so that is already as pluggable as it can get really. Instead of `last-release-npm`, you can already configure to use a different plugin like `last-release-git`. `NPM_TOKEN` can be set to a dummy value. It works well - some rough edges shouldn't block us on brainstorming how semantic-release could support a prerelease workflow.

For example, one could imagine different branches like `alpha`, `beta`, `stable` that commits go through. I imagine it should already be possible with the plugin API to make the new release on the `beta` branch always the "next" beta release or the previous `beta` release + 1. Then a release could be first merged into the `beta` branch if desired before being merged into `stable`.

**Comment by pvdlg** [comment] 2017-11-01 07:26
Supporting other package manager will be possible when #484 will be implemented.
I'll have some time this weekend to work on that but probably not before.

With #484 you will be able to disable the NPM_TOKEN verification and the `npm publish` and run anything else instead.

But there will still be some restriction due to:
- `semantic-release` getting a lot of info from the `package.json` (config, module name, module scope, dist-tag, repo url etc...). So supporting a package manager that doesn't rely on `package.json` will not be possible in the near future.
- The next version is determined in `semantic-release` and follow `semver`. So package manager that doesn't support `server` won't be supported in the near future.

At that point the priority is #484 to support workflow that doesn't use `npm` and to give the possibility to create plugins for other repository type, and if possible other package manager.

We are also discussing how to support dist-tag in a better way with `npm`, in particular the scenario with a LTS/legacy/maintenance dist-tag. It's a problematic that is far from being easy as is has a lot of implications and there is almost as many workflow as there is developers.

Supporting other package managers with their own specificities in terms of version / branch / tag / release channel is not the top priority at the moment.
Once we have a 100% robust and simple solution that support a LTS/legacy/maintenance + latest + next dist-tag type scenario with npm we will consider other package manager.

That said, if a package manager works similarly to npm that should be easy to integrate via plugin.

**Comment by felixfbecker** [comment] 2017-11-01 07:33
@pvdlg what do you think about the idea I outlined above?

**Comment by pvdlg** [comment] 2017-11-01 07:55
For information, here is a thread with a discussion related to dis-tag vs pre-release scenario: https://github.com/semantic-release/semantic-release/pull/431

I don't know anything about composer. So I'm not sure what type of workflow it relies on.

As mentioned previously we still have a bit of work to completely support a dist-tag based workflow and that's the priority. There is a discussion around that in https://github.com/semantic-release/semantic-release/issues/371.

If you could formulate the changes necessary to be made in `semantic-release` to support the scenario you want to implement we will absolutely consider it. But at that point, I don't fully understand how this workflow would work and I don't know what modification would be required.

**Comment by pvdlg** [comment] 2017-12-15 17:43
Duplicate of #563

**Comment by pvdlg** [comment] 2017-12-15 17:43
Feedback welcome in #563. Thanks !

**Closed by pvdlg** 2017-12-15 17:43 UTC
