### ISSUE TITLE
website is spewing firebase errors

### ISSUE THREAD

**Issue by nksfrank** [semantic-release/semantic-release#2443] opened 2022-05-26 06:05 UTC
Had the website open in chrome (https://semantic-release.gitbook.io/semantic-release/usage/getting-started).
closed the computer for the day.
opened the computer the next day and the website is looping through massive amounts of errors.
 
![errors](https://user-images.githubusercontent.com/7352072/170426953-066f8534-8088-423d-a3eb-b1e0b4e629d1.gif)

**Comment by travi** [comment] 2022-05-26 20:29
thank you for the heads up, but closing since i'm not able to reproduce at this point. please feel free to re-open if you are still seeing issues, especially if you can provide steps to reproduce

**Closed by travi** 2022-05-26 20:29 UTC
