### ISSUE TITLE
Notification Plugins

### ISSUE THREAD

**Issue by apowers313** [semantic-release/semantic-release#89] opened 2015-09-21 15:44 UTC
With semantic-release potentially declining to release for any number of reasons, it may be inconvenient or difficult to read back through long Travis CI logs to decipher if / why a release wasn't published -- especially since Travis CI doesn't throw any errors if the release failed.

Rather than depending on Travis CI logs, it would be great to build a plugin API for notifications. These notifications would similar to what is already done for production servers, such as [Heroku's Deploy Hooks](https://devcenter.heroku.com/articles/deploy-hooks) or [Rollbar's Alerts](https://rollbar.com/features/alerts/); however, in this case the notifications wouldn't be for deploying software to a server, but for deploying a package to npm. 

Not only would this be great for sending an email to the developer that is pushing releases about whether or not a release went out (and if not, why it failed), but it would also be good for communities around packages that use services like [Gitter](https://gitter.im), [Slack](https://slack.com/), [HipChat](https://www.hipchat.com/), etc.

I'm imagining that the plugin could simply be a default handler for catching SBError events, so hopefully implementation wouldn't be too hard.

**Comment by boennemann** [comment] 2015-10-26 15:01
Adding an result/error hook is a very good idea. I think if we just add that people can develop their own small plugins that post the data somewhere in the right format.

I'm happy to assist contributors to implement this, or I hope to get to this out sometime soon. I'll leave this issue open so people can grab it.

**Comment by pvdlg** [comment] 2018-02-10 00:11
The feature is currently under work in #627. Let's follow up over there.

**Comment by pvdlg** [comment] 2018-02-10 00:11
Duplicate of #627

**Closed by pvdlg** 2018-02-10 00:11 UTC
Labels: feature, help wanted
