### ISSUE TITLE
References to github issue-comments in commits are incorrectly parsed as closing the issue

### ISSUE THREAD

**Issue by joelmukuthu** [semantic-release/semantic-release#1129] opened 2019-03-13 13:58 UTC
## Current behavior

In a commit message, if I reference a comment on an issue, semantic-release thinks that that commit closes that issue.

The commit https://github.com/knorm/postgres/commit/035c5b56cc7768ae42df72dbf21ba64affeb307f:

```
This is an attempt to fix "Client was closed and is not queryable"
errors. Ref: brianc/node-postgres#1745 (comment).
```

Release commit, generated by semantic-release https://github.com/knorm/postgres/commit/4943b6b366089bc21a60f03d19e3552f44fa4ec1:

```
pass query errors to client.release ([035c5b5](035c5b5)), closes [/github.com/brianc/node-postgres/issues/1745#issuecomment-469703239](https://github.com//github.com/brianc/node-postgres/issues/1745/issues/issuecomment-469703239)
```

NOTE that @semantic-release/changelog also generated an erroneous changelog https://github.com/knorm/postgres/blob/4943b6b366089bc21a60f03d19e3552f44fa4ec1/CHANGELOG.md#bug-fixes:

```
pass query errors to client.release (035c5b5), closes /github.com/brianc/node-postgres/issues/1745#issuecomment-469703239
```

## Expected behavior

That the reference to the comment would be ignored.

## Environment

- **semantic-release** version: 15.13.3
- CI environment: Travis CI
- Plugins used: 
  - "@semantic-release/changelog": "3.0.2"
  - "@semantic-release/git": "7.0.8",
  - "@semantic-release/github": "5.2.10",
  - "@semantic-release/npm": "5.1.4",
- **semantic-release** configuration: https://github.com/knorm/postgres/blob/master/.releaserc.json
- CI logs: https://travis-ci.org/knorm/postgres/builds/505765965

**Comment by pvdlg** [comment] 2019-03-13 15:19
Duplicate of #1107

**Closed by pvdlg** 2019-03-13 15:19 UTC

**Comment by pvdlg** [comment] 2019-03-13 15:20
This is an issue with `conventional-changelog` which is one of our dependency. It will have to be fixed there.
There is nothing we can do here other than replacing/rewriting `conventional-changelog` which we won't do at this point.
