### ISSUE TITLE
semantic-release-cli setup "Error: Could not get repo id" for Travis CI Pro

### ISSUE THREAD

**Issue by mattmazzola** [semantic-release/semantic-release#642] opened 2018-02-05 23:25 UTC
## Current behavior

I'm running `semantic-release-cli setup` and after I select: Travis CI Pro as my CI it says:

```
<removed>
...
WARN semantic-release keytar is not installed correctly, not saving password
? What CI are you using? Travis CI Pro
ERR! semantic-release Error: Could not get repo id
ERR! semantic-release     at setUpTravis (C:/Users/mattm/AppData/Roaming/npm/node_modules/semantic-release-cli/src/lib/travis.js:107:29)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release  { Error: Could not get repo id
ERR! semantic-release     at setUpTravis (C:/Users/mattm/AppData/Roaming/npm/node_modules/semantic-release-cli/src/lib/travis.js:107:29)
ERR! semantic-release     at <anonymous>
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR! semantic-release   stack: 'Error: Could not get repo id\n    at setUpTravis (C:/Users/mattm/AppData/Roaming/npm/node_modules/semantic-release-cli/src/lib/travis.js:107:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
```

## Expected behavior

I expect it to be able to connect to Travis and write the GH_TOKEN, NPM_USERNAME, and NPM_PASSWORD environment variables so it can push/publish automatically.

I have been able to setup without issue when using a non-private repository on Travis CI, but setup does not work now.

I can view my tests and CI logs on https://travis-ci.com so I'm not sure why it cannot also find the repo.

## Environment

- **semantic-release** version: "13.1.3"
(I'm using the @next version because I was told this uses git tags to find next version instead of querying npm registry which is unreliable on custom registries like the one I am using)
- CI environment: Travis CI Pro
- Plugins used: None
- **semantic-release** configuration: None (private repo, but configuration is standard)
- CI logs: N/A

**Comment by mattmazzola** [comment] 2018-02-05 23:56
Hmm, I re-ran with debugging: (`emantic-release-cli setup --debug`) but it did not output any extra information.

It seems like the error is coming from here:
```
  travis.repoid = _.get(
    await promisify(travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get.bind(travis))(),
    'repo.id'
  );


  if (!travis.repoid) throw new Error('Could not get repo id');
```
https://github.com/semantic-release/cli/blob/3955e0494a6645a8e22a09cfbac9ee1bdd0203b7/src/lib/travis.js#L102-L107

I turned on the node http proxy and it looks like the API call to Travis is incorrect.

Request to get the repository:
```
GET https://api.travis-ci.com/repos/Microsoft/blis-models HTTP/1.1
User-Agent: Travis
Accept: application/vnd.travis-ci.2+json, */*; q=0.01
Authorization: token <removed>
host: api.travis-ci.com
Connection: close
```

Response:
**Notice Content-Type is image/png** where as all the other responses are JSON.
```
HTTP/1.1 200 OK
Connection: close
Server: nginx
Date: Mon, 05 Feb 2018 23:46:31 GMT
Content-Type: image/png
Content-Length: 1261
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID
Strict-Transport-Security: max-age=31536000
X-Endpoint: Travis::Pro::Api::Endpoint::Repos
X-Pattern: /:owner_name/:name
X-Oauth-Scopes: public,private
X-Accepted-Oauth-Scopes: private
Vary: Accept,Authorization,Accept-Encoding
Cache-Control: no-cache
Pragma: no-cache
Expires: Mon, 05 Feb 2018 23:46:31 GMT
Content-Disposition: inline; filename="unknown.png"
Last-Modified: Mon, 05 Feb 2018 14:31:13 GMT
X-Request-Id: 4e7be806-0ce5-4006-87a4-fcd777eeac46
Via: 1.1 vegur

<body is png binary>
```
The image returned is the build uknonwn badge:

![image](https://user-images.githubusercontent.com/2856501/35834979-02b44848-0a8d-11e8-9e2f-d250208d8399.png)


It's strange because there are other requests to fetch users with same Accept header and they return JSON

```
GET https://api.travis-ci.com/users HTTP/1.1
User-Agent: Travis
Accept: application/vnd.travis-ci.2+json, */*; q=0.01
Authorization: token <removed>
host: api.travis-ci.com
Connection: close
```
Response:
```
{"user":{"id":173417,"name":" .... "}
```

**Comment by pvdlg** [comment] 2018-02-06 00:09
I'm not really familiar with the cli setup code. Is it the same issue as semantic-release/cli#147 ?

**Comment by mattmazzola** [comment] 2018-02-06 00:16
I feel like Travis.com has bug in their API.

From looking at their API docs:
https://docs.travis-ci.com/api/#repositories

They have other endpoints that still allow using the `{repository.slug}` to get data and when I try those with the same headers it does return JSON.

E.g.
```
GET /repos/x/y          -> **Incorrectly returns image/png**
GET /repos/x/y/branches -> application/json;charset=utf-8
Get /repos/x/y/builds   -> application/json;charset=utf-8
```

And yes, that looks like the same error.

**Comment by pvdlg** [comment] 2018-02-06 00:21
Yes it something weird with the Travis API. I think we workaround it in `travis-deploy-once` here:

https://github.com/semantic-release/travis-deploy-once/blob/5e29e9d1d5bf0ae5f77ed6fabfc7a9cd36c6928a/lib/get-jobs.js#L28-L32

**Comment by pvdlg** [comment] 2018-02-06 00:22
Duplicate of semantic-release/cli#147

**Closed by pvdlg** 2018-02-06 00:22 UTC

**Comment by mattmazzola** [comment] 2018-02-06 00:28
The other issue makes it sound like it can be fixed by manually going to travis.com and syncing repos.  The issue still occurs even after both of these steps

**Comment by pvdlg** [comment] 2018-02-06 00:33
> The other issue makes it sound like it can be fixed by manually going to travis.com and syncing repos. The issue still occurs even after both of these steps

Ok, maybe it's the same as semantic-release/cli/issues/123 or semantic-release/cli/issues/112 ?

**Comment by mattmazzola** [comment] 2018-02-06 00:40
It is similar to #112 however, that issue looks to be using Travis CI (Not Pro)

This means it's using:
api.travis-ci.org instead of api.travis-ci.com which does not appear to have the same bug.

**Comment by mattmazzola** [comment] 2018-02-06 17:03
I noticed Travis CI has a v3 api available although I'm not quite sure how to use it at the moment.  I thought I could just update the Accept header to use 3 instead of 2 such as:

`Accept: application/vnd.travis-ci.3+json, */*; q=0.01`

However, it seems the V3 api still has problems.
I wonder if there is some other API we can use to get the repository ID that doesn't have this error, and then continue on. 

For now my work around is to try to manually put the environment variables into Travis and see if the script will run successfully.
