### ISSUE TITLE
Not respecting custom registry

### ISSUE THREAD

**Issue by mattmazzola** [semantic-release/semantic-release#630] opened 2018-01-31 20:19 UTC
## Current behavior

I ran `semantic-release setup` and provided custom registry url with authentication; however, when it builds in Travis it still was attempting to authenticate with the default npm registry.

```
D:\repos\library-starter-test [master ≡ +1 ~0 -0 !]> semantic-release-cli setup
? What is your npm registry? http://bbnpm.azurewebsites.net
? Which authentication method is this npm registry using? Legacy (username, password, email)
...
```
Travis build logs for `npm run semantic-release` script:

```
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_USERNAME, NPM_PASSWORD and NPM_EMAIL to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Call plugin get-last-release
info attempt registry request try #1 at 20:04:48
...<removed>...
[Semantic release]: Publishing version 1.0.0 to npm registry
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: npm publish ./. --registry https://registry.npmjs.org/
```

## Expected behavior

Since it entered authentication information that would only work on the custom registry and yet it is trying to authenticate against the official NPM registry I would expect it to fail.  I would expect the url it's using for the registry to be the one I entered during the setup process.

I checked Travis.ci repo settings and it has the GH_TOKEN, NPM_EMAIL, NPM_PASSWORD, and NPM_USERNAME environment variables set, but I would think there should also be something like REGISTRY_URL

## Environment
I'm using the setup described in https://github.com/alexjoverm/typescript-library-starter and want to be able to release a custom registry.

I'm suspicious of the url, but I will try publishing manually locally to verify username / password.

- **semantic-release**
"semantic-release": "^12.4.1",

- CI environment: Travis  CI
- Plugins used: None
- **semantic-release** configuration: https://github.com/mattmazzola/library-starter-test
- CI logs: https://travis-ci.org/mattmazzola/library-starter-test/builds/335798058

**Comment by pvdlg** [comment] 2018-01-31 20:33
In your `package.json` you set `semantic-release pre && npm publish && semantic-release post` which is the old way of running `semantic-release`. As mention in the doc you have to just run `semantic-release`.

If you want to use a custom registry, you can configure it in a `.npmrc` file at the root of your project or in under `publishConfig` property in your package.json.

The `semantic-release-cli setup` should save the custom registry URL. There is an issue opened for that: semantic-release/cli#177

**Comment by mattmazzola** [comment] 2018-01-31 20:58
The `semantic-release setup` fixed the package.json and corrected the script to be:
`"semantic-release": "semantic-release",`  I thought I had those changed pushed when I submitted the issue, but maybe not.
https://github.com/mattmazzola/library-starter-test/blob/master/package.json#L32

The typescript-library-starter repo does have the old script though. They could update their default.

I will try using the .npmrc file to control registry. Thanks!

**Comment by mattmazzola** [comment] 2018-01-31 21:31
Adding the .npmrc works although now i'm facing other issue:
https://github.com/semantic-release/semantic-release/issues/632

I suppose this can be closed as duplicate of the other issue you referenced.

**Comment by pvdlg** [comment] 2018-01-31 22:02
Duplicate of semantic-release/cli#177

**Closed by pvdlg** 2018-01-31 22:02 UTC
