### ISSUE TITLE
ERELEASEBRANCHES error when the main branch is used for pre-release

### ISSUE THREAD

**Issue by jcornaz** [semantic-release/semantic-release#2503] opened 2022-07-11 07:46 UTC
### Current behavior

Given a repository with a single `main` branch, and the following configuration: 

```json
{
    "branches": [
        "+([0-9]).x",
        {
            "name": "main",
            "prerelease": "alpha"
        }
    ]
}
```

Semantic release crashes with: 

```
ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/workspace/node_modules/semantic-release/lib/get-error.js:6:10)
        at /workspace/node_modules/semantic-release/lib/branches/index.js:45:19
        at Array.reduce (<anonymous>)
        at module.exports (/workspace/node_modules/semantic-release/lib/branches/index.js:35:46)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/workspace/node_modules/semantic-release/index.js:65:22)
        at async module.exports (/workspace/node_modules/semantic-release/index.js:269:22)
        at async module.exports (/workspace/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/workspace/node_modules/semantic-release/lib/branches/index.js:67:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/workspace/node_modules/semantic-release/index.js:65:22)
    at async module.exports (/workspace/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/workspace/node_modules/semantic-release/cli.js:55:5)
```

### Expected behavior

It should not crash, and release alpha versions from the main branch.

### `semantic-release` version

19.0.3

### CI environment

not relevant

### `semantic-release` configuration

Already posted above

### CI logs

```
[9:16:37 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.3
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[9:16:37 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:16:42 AM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/exec" in dry-run mode
[9:16:42 AM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[9:16:42 AM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/workspace/node_modules/semantic-release/lib/get-error.js:6:10)
        at /workspace/node_modules/semantic-release/lib/branches/index.js:45:19
        at Array.reduce (<anonymous>)
        at module.exports (/workspace/node_modules/semantic-release/lib/branches/index.js:35:46)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/workspace/node_modules/semantic-release/index.js:65:22)
        at async module.exports (/workspace/node_modules/semantic-release/index.js:269:22)
        at async module.exports (/workspace/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/workspace/node_modules/semantic-release/lib/branches/index.js:67:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/workspace/node_modules/semantic-release/index.js:65:22)
    at async module.exports (/workspace/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/workspace/node_modules/semantic-release/cli.js:55:5)
```

**Comment by jcornaz** [comment] 2022-09-13 09:10
Any idea of what we can do to work around this? Or even better how to solve it?

**Comment by StudioLE** [comment] 2022-09-13 11:50
> Any idea of what we can do to work around this? Or even better how to solve it?

The quick workaround is to create a separate "release" branch, even if you don't have intention to use it.

**Comment by jcornaz** [comment] 2022-09-13 12:36
> The quick workaround is to create a separate "release" branch, even if you don't have intention to use it.

Thanks for the tip. It didn't work at first, but I eventually managed to get it working by pushing the "release" branch to the remote clone.

That is a quite ugly work-around though. Now I have to find a nice way to communicate that this branch should not be used, and is in fact certainly not for releasing....

How can we fix the bug? I tried to look at the code source, but it is very confusing to me.

**Comment by dominykas** [comment] 2023-10-31 16:04
@travi would you accept a PR for this?

I'm thinking that if configuration does not configure any release branches (i.e. it only has pre-release branches), then it should bypass the release branch checks?

Our use case: we want to build pre-releases from `main` branch, but with some dependency overrides for testing (e.g. "compile this UI with a beta version of react", "publish a pre-release of this package, but reference WIP from git") - we _could_ create temporary branches for these pre-releases, but that creates too many moving parts (need to push them to remote, need to clean them up afterwards in case we want to use them again, etc).

**Comment by travi** [comment] 2023-11-01 05:24
the described behavior is currently the intended behavior. i am an advocate of trunk based development, so i'm interested to better understand the desire with this use case, but the [prerelease workflow](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/pre-releases) was designed around git branches because it is such a natural fit. 

even with a trunk based mindset, i'm not grasping why avoiding branches for a pre-release would be desireable. the goal is to release to a separate channel to avoid advertising to all consumers. prerelease changes are normally for experimentation, so there is a reasonable chance they wont work out and you decide to abandon the changes. reverting the changes from the main branch can be more complex than clearning up an abandoned branch.

> @travi would you accept a PR for this?

i'm not saying no, but want to be clear that i'm quite hesitant. i would need a very strong sales pitch, but i am open to hearing enough to better understand the goal.

**Comment by dominykas** [comment] 2023-11-01 07:37
> even with a trunk based mindset, i'm not grasping why avoiding branches for a pre-release would be desireable. the goal is to release to a separate channel to avoid advertising to all consumers. prerelease changes are normally for experimentation, so there is a reasonable chance they wont work out and you decide to abandon the changes. reverting the changes from the main branch can be more complex than clearning up an abandoned branch.

The goal here is to release without pushing a commit at all - sort of like CITGM. This is completely automated.

As a user, I want to see "Does my App work with my work-in-progress Lib?". To achieve this, you have to install the WIP Lib into the App - there are multiple ways of doing it, but all of them at the end of the day involve a change in the `package.json` of the App. In case of breaking changes in the Lib, the App might need changes - in which case there would be a PR on the App side and it would make perfect sense. But a lot of the time, for the App/Lib of sufficient complexity, the developer does not not if there are breaking changes, so they need to run tests for the App.

We already have tooling which achieves most of that (e.g. unit tests), but we'd also like to do a pre-release of the App (so that we can actually deploy it for end-to-end integration testing, etc). The goal here is that the end-user (the developer) does not have to care about anything that happens in the App repository - all they want is a pre-release of the app with their Lib, and the tooling has to do all of that automatically.

It is possible to achieve this by automatically creating a temporary branch in CI, pushing into github, and then deleting after the build completes, however it does add to complexity of the build tooling and there's also potential race conditions, depending on the duration of the release process (it can be a couple of minutes, if you're pushing large docker containers).

**Comment by obs-gh-colinhutchinson** [comment] 2023-11-01 16:21
My team is currently in the process of transitioning towards trunk-based development, but our organizational processes and practices are still evolving to fully support this paradigm. In our interim state, we have found it beneficial to conduct pre-releases for every commit to the trunk (main) branch, using the `release` branch workaround as a temporary solution.

We understand that this approach deviates from the canonical semantic-release pre-release workflow. However, we believe it provides a pragmatic and incremental step towards full trunk-based development, particularly for teams in transitional phases like ours. It allows us to start reaping some of the benefits of continuous delivery and integration, while maintaining a certain level of manual oversight and control over our release process. A human is required to trigger the GitHub Action workflow for a proper release, which uses a separate releaserc.json configuration to manage this process.

The `release` branch workaround serves its purpose, but it introduces an additional layer of complexity and potential confusion for our developers. We are concerned that this could hinder our progress towards adopting trunk-based development practices fully.

Given these considerations, we believe that allowing configurations without release branches would streamline our workflow and reduce the cognitive load on our developers. It would also provide a more flexible and inclusive solution for teams in similar transitional phases, who are navigating the complexities of shifting towards trunk-based development while still needing to maintain certain levels of control and oversight over their release processes.

We appreciate your consideration of this request and are open to further discussion or collaboration to explore how this functionality could be implemented in a way that aligns with the semantic-release project’s goals and standards.

**Comment by hutchic** [comment] 2023-11-01 16:23
My team is currently in the process of transitioning towards trunk-based development, but our organizational processes and practices are still evolving to fully support this paradigm. In our interim state, we have found it beneficial to conduct pre-releases for every commit to the trunk (main) branch, using the `release` branch workaround as a temporary solution.

We understand that this approach deviates from the canonical semantic-release pre-release workflow. However, we believe it provides a pragmatic and incremental step towards full trunk-based development, particularly for teams in transitional phases like ours. It allows us to start reaping some of the benefits of continuous delivery and integration, while maintaining a certain level of manual oversight and control over our release process. A human is required to trigger the GitHub Action workflow for a proper release, which uses a separate releaserc.json configuration to manage this process.

The `release` branch workaround serves its purpose, but it introduces an additional layer of complexity and potential confusion for our developers. We are concerned that this could hinder our progress towards adopting trunk-based development practices fully.

Given these considerations, we believe that allowing configurations without release branches would streamline our workflow and reduce the cognitive load on our developers. It would also provide a more flexible and inclusive solution for teams in similar transitional phases, who are navigating the complexities of shifting towards trunk-based development while still needing to maintain certain levels of control and oversight over their release processes.

We appreciate your consideration of this request and are open to further discussion or collaboration to explore how this functionality could be implemented in a way that aligns with the semantic-release project’s goals and standards.

**Comment by travi** [comment] 2023-11-03 18:43
thanks for the extra context @hutchic and @dominykas. that information helps to highlight that this is more a matter of requesting support for a workflow that isnt officially supported today. we certainly hear requests for a workflow that would support releasing a version that could be tested with consumers out-of-band and later promoting the version to be a stable release. 

because of that, lets move this conversation to a feature request issue. i dont think the way forward is to change the handling to allow a lack of a release branch and the reported error is at least accurate according to the current supported workflows (wording could potentially be improved to be more clear or link to more documentation. open to suggestions/PRs on that part). i'll migrate some of the conversation from here to a new issue so that we can talk about this more from the perspective of potentially supporting the goal as a different workflow type.

**Comment by travi** [comment] 2023-11-03 21:27
closing in favor of #3046

**Closed by travi** 2023-11-03 21:27 UTC

**Comment by lmbeauplet** [comment] 2024-01-04 18:44
Hi all ! 

i found a quick workaround for this thread if anyone is interested. I have a config file like .releaserc.yaml. Inside this file i declared somes branches like `branches: ['master', 'currentbranch']` (don't change 'currentbranch', you will see).

In my github action semantic.yaml, i will edit this fill to replace 'currentbranch' by the real current branch of CI execution and it woks fine.

.releaserc.yaml (at repo base):
`
---
branches: ['master', 'currentbranch']
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"

verifyConditions:
  - '@semantic-release/git'
  - "@semantic-release/github"
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
    - type: "feat"
      release: "patch"
    - type: "hotfix"
      release: "patch"
    - type: "patch"
      release: "patch"
    - type: "minor"
      release: "minor"
    - type: "breaking"
      release: "major"
generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
    types:
    - type: "feat"
    - section: ":rocket: Features"
    # Tracked bug fix with a hotfix branch
    - type: "hotfix"
    - section: ":rotating_light: Bug Fixes"
    # Uninmportent fix (CI testing, etc)
    - type: "fix"
    - section: ":bug: Bug Fixes"
    - hidden: true
    - type: "chore"
    - section: ":package: Chore"
    - hidden: true
    - type: "docs"
    - section: ":books: Docs"
    - type: "doc"
    - section: ":books: Docs"
    - hidden: true
    - type: "style"
    - section: ":lipstick: Style"
    - hidden: true
    - type: "refactor"
    - hidden: true
    - type: "perf"
    - hidden: true
    - type: "test"
    - hidden: true
    presetConfig: true
prepare:
  - path: "@semantic-release/git"
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
publish:
  - path: "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"
`

semantic.yaml (in .github/workflows/)v:
`
name: semantic-release

on: [push]

jobs:
  semantic-release:

    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: latest

      - name: Replace branch name in branches array
        run: sed -i 's|'currentbranch'|'${{ github.ref_name }}'|' .releaserc.yaml

      - name: Install dependencies
        run: npm -g install @semantic-release/git @semantic-release/github -D

      - name: Launch semantic
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
`


On push, pre-release is created with release note following commit analyzer. You can just replace the trigger method of this CI and get the good ref_name
