### ISSUE TITLE
Getting Error while installing semantic-release-cli

### ISSUE THREAD

**Issue by cakarci** [semantic-release/semantic-release#92] opened 2015-09-22 14:31 UTC
![semantic](https://cloud.githubusercontent.com/assets/4185569/10021235/c5bc1990-614f-11e5-827d-95c1b9d981f3.PNG)

**Comment by shairez** [comment] 2015-09-22 19:28
+1

**Comment by gr2m** [comment] 2015-09-22 22:48
Can you try to update npm to latest version, then try again? If that's not working, try `npm uninstall -g semantic-release-cli`, then try again

**Comment by shairez** [comment] 2015-09-23 00:01
Thanks for the quick reply @gr2m !

Here is my experience:

tried uninstalling and reinstalling - didn't work
tried upgrading to latest npm - didn't work

I'm on Windows and I get the same error for `node-gyp`

First it complained about missing "python", I installed it, now it is complaining about .NET 2.0 SDK

I see this error with other projects, but usually it doesn't stop the install.

Is there a way to maybe `npm install` the pre-release version (0.6.x) of this project? just to test it out to see if it solves it?

**Comment by cakarci** [comment] 2015-09-23 06:30
+1

**Comment by shairez** [comment] 2015-09-23 10:13
Well, after reading [here[(https://github.com/nodejs/node-gyp), I installed [the express version of .net tools](http://www.microsoft.com/en-gb/download/details.aspx?id=44914) and it solved the install issue.

**Comment by cakarci** [comment] 2015-09-23 11:05
finally, this solved the problem. Thanks

**Comment by boennemann** [comment] 2015-09-27 10:28
Thanks for reporting this, a fix landed here: https://github.com/semantic-release/cli/releases/tag/v1.1.5

Best,
Stephan

**Closed by boennemann** 2015-09-27 10:28 UTC

**Comment by Flame2057** [comment] 2016-08-20 17:56
I still have this issue

**Comment by gr2m** [comment] 2016-08-20 19:19
@Flame2057 what versions of node, npm, semantic-release are you using?

```
node -v && npm -v && semantic-release-cli -v
```

Make sure it’s all updated to the latest.

What operating system are you using?

**Comment by Flame2057** [comment] 2016-08-20 21:57
@gr2m Node version 4.5.0, npm version 3.10.6, and no semantic-release version because I can't get it to install (that's the issue here).

My OS is the latest version Windows 10 Home Edition, and I'm using the Git Bash terminal.

**Comment by gr2m** [comment] 2016-08-20 22:31
The problem is with the install of [node-gyp](https://github.com/nodejs/node-gyp). There are lots of instructions for Windows. Once you get it installed on your machine, the install of semantic-release-cli and many others that rely on node-gyp should work fine

**Comment by Flame2057** [comment] 2016-08-20 22:37
@gr2m I installed that, but I'm still getting a bunch of error messages. The messages I'm getting are a little different than the OP, so I will post screenshots of them here:
![bug 1](https://cloud.githubusercontent.com/assets/21113764/17834241/207fc28a-6705-11e6-8206-0aaa3b209189.png)
![bug 2](https://cloud.githubusercontent.com/assets/21113764/17834242/22723c8a-6705-11e6-8293-2782d8c3ca7d.png)

**Comment by gr2m** [comment] 2016-08-20 22:45
you need python (`Error: Couldn’t find executable python`), please see https://github.com/nodejs/node-gyp#installation for windows.

**Comment by Flame2057** [comment] 2016-08-20 23:42
@gr2m Thanks so much, I got it working with that.  :)

**Comment by Flame2057** [comment] 2016-08-21 00:14
@gr2m I spoke too soon - now I get a bunch of ambiguous errors when I run `semantic-release-cli setup` in my github project directory

![bug 3](https://cloud.githubusercontent.com/assets/21113764/17834538/c201e568-6712-11e6-9a5e-4fc3f90b27b7.png)

**Comment by gr2m** [comment] 2016-08-21 03:51
Oh my, I've no idea :(

Can you check http://www.jamessturtevant.com/posts/5-Ways-to-install-git-on-Windows/ for an alternative to the git bash? I've heard Cmder is great for older Windows versions. Sorry I can't help better than this, I don't have Windows myself.

**Comment by Flame2057** [comment] 2016-08-21 16:01
@gr2m I am using Windows 10 though. I just tried it on the ordinary CMD, though, and it worked. I guess Git Bash is only good for Linux machines? Anyway thanks for your help, I will use the Windows CMD from now on.

**Comment by gr2m** [comment] 2016-08-21 17:45
glad you got it working 👍

**Comment by oneezy** [comment] 2016-12-16 19:36
My related issue #344 , just seeing this..
