### ISSUE TITLE
Release fails with ERR! pre undefined after update to v8

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/semantic-release#452] opened 2017-09-30 10:30 UTC
After updating to v8 the release failed with this error:
https://travis-ci.org/sourcegraph/javascript-typescript-langserver/jobs/281476705#L1943

No idea how to debug this

**Comment by vanduynslagerp** [comment] 2017-09-30 17:29
Can you clarify which error you are referring to ?
In the Travis logs of the build you linked I see the release of version 2.5.0 happened without errors and the version is on npm and in the Github release.

**Comment by felixfbecker** [comment] 2017-09-30 18:46
I re-ran `semantic-release-cli setup` and restartet the build, which suceeded. Seems like a token issue maybe? I would propose to improve the error message, seems similar to https://github.com/semantic-release/semantic-release/issues/337

**Comment by vanduynslagerp** [comment] 2017-09-30 18:49
Thanks !
I'll close as duplicate of #337 then.
Feel free to re-open if it's not the case.

**Closed by vanduynslagerp** 2017-09-30 18:49 UTC
