### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by luftywiranda13** [semantic-release/semantic-release#389] opened 2017-05-15 06:19 UTC
I got these errors when installing semantic-release. any resolutions?

* **warning** semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
* **warning** semantic-release > @semantic-release/commit-analyzer > conventional-changelog@0.0.17: Please update conventional-changelog to >1.0.0. If you are running the cli, use conventional-changelog-cli
* **warning** semantic-release > @semantic-release/condition-travis > travis-deploy-once > travis-ci > request > node-uuid@1.4.8: Use uuid module instead

**Comment by jhabdas** [comment] 2017-05-29 07:51
Dupe of #176. Please close this and be sure to search through closed issues in repos before opening new ones. Thanks!

**Comment by jhabdas** [comment] 2017-05-29 07:51
If you have a separate issue, please open a separate issue.

**Comment by luftywiranda13** [comment] 2017-05-29 07:55
@jhabdas hmmm do you mean an issue posted more than 1 year ago?
closed issue? has it been closed?

**Comment by jhabdas** [comment] 2017-05-29 07:56
I mean it's a duplicate. It's noise. I've linked to the partial dupe and provided guidance. What value is there to leaving this open?

**Comment by jhabdas** [comment] 2017-05-29 07:59
Pardon. It's a partial dupe. Please consider removing the duplicate part. Then it's not a partial dupe. Does that make sense?

**Comment by rarkins** [comment] 2017-07-08 06:28
So `npmconf` is mentioned in #176 but the other two are not.

**Closed** 2017-08-17 16:37 UTC
