### ISSUE TITLE
semantic-release mistakes a job on circleci branch as a PR and exits early

### ISSUE THREAD

**Issue by dannyrb** [semantic-release/semantic-release#1166] opened 2019-04-26 19:52 UTC
## Current behavior

My `origin` is a fork of `upstream`.
I create a branch on `origin`
I PR that branch against `upstream:react`
I merge that PR
CircleCI runs against merged changes on `upstream:react`

`semantic-release` exits early with:

> This test run was triggered on the branch undefined

Removing the `--no-ci` option produces the following result:

> This run was triggered by a pull request and therefore a new version won't be published.

## Expected behavior

`semantic-release` sees that it was run against a merge, not a PR, and creates a release.

## Environment

- **semantic-release** version: `15.13.x`
- CI environment: `circleci`
- Plugins used: default plugins
- **semantic-release** configuration:

```
  semantic-release:config load config from: /home/circleci/repo/.releaserc +0ms
  semantic-release:config options values: { branch: 'react',
  semantic-release:config   repositoryUrl: 'OHIF/Viewers',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins:
  semantic-release:config    [ '@semantic-release/commit-analyzer',
  semantic-release:config      '@semantic-release/release-notes-generator',
  semantic-release:config      '@semantic-release/npm',
  semantic-release:config      '@semantic-release/github' ],
  semantic-release:config   _: [],
  semantic-release:config   debug: true,
  semantic-release:config   ci: false,
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release',
  semantic-release:config   noCi: true }
```

- CI logs: https://circleci.com/gh/OHIF/Viewers/32

### Relevant Links:

CircleCI Config: https://github.com/OHIF/Viewers/blob/react/.circleci/config.yml
Pull Request: https://github.com/OHIF/Viewers/pull/405
Workflow: https://circleci.com/workflow-run/b9e4f670-55e1-4876-a5f4-e4594d525f0c
Example w/ --no-ci flag: https://circleci.com/gh/OHIF/Viewers/32
Example w/o --no-ci flag: https://circleci.com/gh/OHIF/Viewers/38

Potentially related to: https://github.com/semantic-release/semantic-release/issues/1074

**Comment by travi** [comment] 2019-04-26 20:02
this sounds similar to https://github.com/semantic-release/semantic-release/issues/1074. any details there that help in your situation?

**Comment by dannyrb** [comment] 2019-04-26 20:07
The OP's issue appeared to stem from an earlier job in his workflow:

> The problem was / is that my circleci workflow creates a new pr in the first job. This then messes up subsequent jobs.

Which is not something that takes place in any of my jobs. My workflow if actually _very_ vanilla, and similar to the workflow's I've setup for our other repositories + _semantic-release_.

The only difference is that I've changed the default release branch to `react`

**Comment by dannyrb** [comment] 2019-04-26 20:26
The first step is pretty telling:

```
  ...
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=react
  ...
  CIRCLE_JOB=npm_publish
  ...
  CIRCLE_PROJECT_REPONAME=Viewers
  CIRCLE_PROJECT_USERNAME=OHIF
  CIRCLE_PULL_REQUEST=https://github.com/OHIF/Viewers/pull/321
  CIRCLE_PULL_REQUESTS=https://github.com/OHIF/Viewers/pull/321
  ...
  CI_PULL_REQUEST=https://github.com/OHIF/Viewers/pull/321
  CI_PULL_REQUESTS=https://github.com/OHIF/Viewers/pull/321

Using environment variables from project settings and/or contexts
  CIRCLE_JOB=**REDACTED**
  CODECOV_TOKEN=**REDACTED**
  GITHUB_TOKEN=**REDACTED**
  NPM_TOKEN=**REDACTED**
```

If @pvdlg's comment is accurate today, then the presence of the `CIRCLE_PULL_REQUEST` may be the issue. However, the values also indicate that this job/build is taking place on the `react` branch, and the `circleci` config is set to only run on the `react` branch.

**Comment by dannyrb** [comment] 2019-04-26 20:47
This appears to be a bug in `semantic-release`'s dependency `env-ci`.

https://github.com/pvdlg/env-ci/blob/master/services/circleci.js#L10-L11

From CircleCI Docs:

> `CIRCLE_PR_NUMBER`: The number of the associated GitHub or Bitbucket pull request. Only available on forked PRs.
> `CIRCLE_PULL_REQUEST`: The URL of the associated pull request. If there are multiple associated pull requests, one URL is randomly chosen.

So while `CIRCLE_PR_NUMBER` will only appear on forked PRs, that is not the case for `CIRCLE_PULL_REQUEST`. The excerpt "If there are multiple associated pull requests..." also seems to indicate that this value may be set for jobs run when a branch has merged changes.

I'm mostly guessing and trying to dig in to find more helpful information. It's very possible I'm missing something obvious.

**Comment by pvdlg** [comment] 2019-06-05 22:13
Fixed in #87

**Closed by pvdlg** 2019-06-05 22:13 UTC

**Comment by krohrsb** [comment] 2019-06-08 04:45
Note: I replied in https://github.com/pvdlg/env-ci/issues/82

>My origin is a fork of upstream.
I create a branch on origin
I PR that branch against upstream:react
I merge that PR
CircleCI runs against merged changes on upstream:react

So far as I can tell by looking at your jobs, you had an open PR from `upstream:react` -> `upstream:master` therefore CircleCI considered it a "pull request" and subsequently env-ci did as well. I would argue this is correct.

**Comment by dannyrb** [comment] 2019-06-08 17:39
@krohrsb , my PR was from

`origin:some-branch` -> `upstream:react`

Where react is my configured build branch for semantic-release. I expected the same behavior all of my other repositories exhibit when I merge a PR into `upstream:master`

**Comment by dannyrb** [comment] 2019-06-08 17:43
Reading your comment closer, are you saying this issue was caused by an open, unrelated PR, from `upstream:react` to `upstream:master`? I could see how that setup could cause this issue. Does one just need to be extra deliberate when using a branch other than `master` to cut releases? I feel like my setup is valid and not too terribly uncommon.

**Comment by krohrsb** [comment] 2019-06-08 17:44
You also seemed to have an open pr from upstream:react to upstream:master right?  Just pushing to master worked since there wasn't a pr originating from it.

If the pr was closed for react->master and a push was made to react, you should see the behavior you are wanting.

**Comment by krohrsb** [comment] 2019-06-08 17:51
The above was meant for the previous comment :) but yes that's what I am saying. Otherwise how does a system know If not for the existence of an associated pull request? What is a PR branch vs non PR branch?

**Comment by sirtimbly** [comment] 2019-09-04 02:13
The problem is that the branch is not a PR branch. In my case the branch is `master` but the env var `CIRCLE_PULL_REQUEST` and `CI_PULL_REQUEST` are still present. I want the fact that this running on branch master to override the fact that there's an associated PR. If the commit is on master it should publish no matter what, right?
