### ISSUE TITLE
Unable to push to unqualified destination

### ISSUE THREAD

**Issue by alavaros** [semantic-release/semantic-release#1181] opened 2019-05-14 10:12 UTC
## Current behavior

**semantic-release** throws an error from the Jenkins job.

## Expected behavior

The release process runs correctly and the tag is created in the repository (Bitbucket).

## Environment

- **semantic-release** version: `^15.13.12`
- CI environment: **Jenkins**
- Plugins used:
```json
"@semantic-release/commit-analyzer",
"@semantic-release/release-notes-generator",
"@semantic-release/changelog",
"@semantic-release/npm",
"@semantic-release/git"
```
- **semantic-release** configuration:
```json
"release": {
  "pkgRoot": "dist/@company/ngx-library",
  "branch": "origin/semantic-release-config-test",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    "@semantic-release/git"
  ]
}
```
- CI logs:
```
2019-05-14T09:41:14.543Z semantic-release:git Error: Command failed: git push --dry-run ssh://git@bitbucket.company/path/to/my/repo.git HEAD:origin/semantic-release-config-test
error: unable to push to unqualified destination: origin/semantic-release-config-test
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'ssh://git@bitbucket.company/path/to/my/repo.git'


    at makeError (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-05-14T09:41:14.631Z semantic-release:git Error: Command failed: git push --dry-run ssh://git@bitbucket.company/path/to/my/repo.git HEAD:origin/semantic-release-config-test
error: unable to push to unqualified destination: origin/semantic-release-config-test
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'ssh://git@bitbucket.company/path/to/my/repo.git'


    at makeError (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-05-14T09:41:14.730Z semantic-release:git Error: Command failed: git merge-base --is-ancestor  HEAD
fatal: Not a valid object name undefined


    at makeError (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2019-05-14T09:41:14.730Z semantic-release:git Error: Command failed: git merge-base --is-ancestor  HEAD
fatal: Not a valid object name undefined


    at makeError (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[09:41:14] [semantic-release] › ℹ  The local branch origin/semantic-release-config-test is behind the remote one, therefore a new version won't be published.
```

**Comment by pvdlg** [comment] 2019-06-07 17:59
What does the command `git remote -v` returns when ran on your CI?

**Comment by alavaros** [comment] 2019-06-10 12:57
> What does the command `git remote -v` returns when ran on your CI?

+ git remote -v
origin	ssh://git@bitbucket.company/path/to/my/repo.git (fetch)
origin	ssh://git@bitbucket.company/path/to/my/repo.git (push)

**Comment by pvdlg** [comment] 2019-06-11 15:59
You configured your branch as `origin/semantic-release-config-test`. However I'm guessing the actual name of the branch you want to release from is `semantic-release-config-test`.

You can see that from the error logs `git push --dry-run ssh://git@bitbucket.company/path/to/my/repo.git HEAD:origin/semantic-release-config-test` indicating that the test to see if we can push on the branch you configured fails.

**Comment by alavaros** [comment] 2019-06-12 11:04
> You configured your branch as `origin/semantic-release-config-test`. However I'm guessing the actual name of the branch you want to release from is `semantic-release-config-test`.
> 
> You can see that from the error logs `git push --dry-run ssh://git@bitbucket.company/path/to/my/repo.git HEAD:origin/semantic-release-config-test` indicating that the test to see if we can push on the branch you configured fails.

I have tested the different possible configurations to execute the command:

```
"branch": "semantic-release-publish",
Branch Specifier (blank for 'any'): semantic-release-publish
[10:43:18] [semantic-release] › ℹ  This test run was triggered on the branch origin/semantic-release-publish, while semantic-release is configured to only publish from semantic-release-publish, therefore a new version won’t be published.

"branch": "semantic-release-publish",
Branch Specifier (blank for 'any'): origin/semantic-release-publish
[10:43:18] [semantic-release] › ℹ  This test run was triggered on the branch origin/semantic-release-publish, while semantic-release is configured to only publish from semantic-release-publish, therefore a new version won’t be published.

"branch": "origin/semantic-release-publish",
Branch Specifier (blank for 'any'): semantic-release-publish
[10:50:52] [semantic-release] › ✔  Run automated release from branch origin/semantic-release-publish
2019-06-12T10:50:52.184Z semantic-release:git Error: Command failed: git push --dry-run ssh://git@bitbucket.devops.onyxcentersource.com:7999/an/onyx-design-system.git HEAD:origin/semantic-release-publish
error: unable to push to unqualified destination: origin/semantic-release-publish

"branch": "origin/semantic-release-publish",
Branch Specifier (blank for 'any'): origin/semantic-release-publish
[10:52:23] [semantic-release] › ✔  Run automated release from branch origin/semantic-release-publish
2019-06-12T10:52:23.836Z semantic-release:git Error: Command failed: git push --dry-run ssh://git@bitbucket.devops.onyxcentersource.com:7999/an/onyx-design-system.git HEAD:origin/semantic-release-publish
error: unable to push to unqualified destination: origin/semantic-release-publish
```

@pvdlg please re-open this issue

**Comment by pvdlg** [comment] 2019-06-12 15:22
So the problem is in the local branch detection.
Do you have any of the following environment variable set and what are their values: `GIT_LOCAL_BRANCH`, `GIT_BRANCH`, `gitlabBranch`, `BRANCH_NAME`.
What's the result of the command `git rev-parse --abbrev-ref HEAD` when ran in your CI?

**Comment by alavaros** [comment] 2019-06-13 07:32
> So the problem is in the local branch detection.
> Do you have any of the following environment variable set and what are their values: `GIT_LOCAL_BRANCH`, `GIT_BRANCH`, `gitlabBranch`, `BRANCH_NAME`.

No, I don't have any of those environment variables set.

> What's the result of the command `git rev-parse --abbrev-ref HEAD` when ran in your CI?

\+ git rev-parse --abbrev-ref HEAD
HEAD

**Comment by pvdlg** [comment] 2019-06-13 15:09
According to the documentation, Jenkins is supposed to set at least one of those variables: https://wiki.jenkins.io/display/JENKINS/Building+a+software+project

Those are the variables we use to determine on which branch the build is running.

You should check why your Jenkins doesn't set them.

**Comment by pvdlg** [comment] 2019-06-13 15:11
For info in case those variables are not set we use `git rev-parse --abbrev-ref HEAD` as a fallback solution. If it returns `HEAD` it means your local branch is in a detached head state.
To workaround that problem we try `git show -s --pretty=%d HEAD` and parse the result.
Can you also provide the output of that last command?

**Comment by alavaros** [comment] 2019-06-14 09:44
> For info in case those variables are not set we use `git rev-parse --abbrev-ref HEAD` as a fallback solution. If it returns `HEAD` it means your local branch is in a detached head state.
> To workaround that problem we try `git show -s --pretty=%d HEAD` and parse the result.
> Can you also provide the output of that last command?

Sorry, one of the environment variables is defined. Also I copy the results of the commands:
```
echo GIT_BRANCH
origin/semantic-release-config-test
+ git rev-parse --abbrev-ref HEAD
HEAD
+ git show -s --pretty=%d HEAD
 (HEAD, origin/semantic-release-config-test)
```

**Comment by pvdlg** [comment] 2019-06-14 16:11
So the problem is that `GIT_BRANCH` is set to `origin/semantic-release-config-test` instead of `semantic-release-config-test`. I don't know Jenkins enough to know why.
We have several other people using Jenkins and I suppose they don't experience this problem.

Maybe https://stackoverflow.com/questions/20541609/how-to-receive-local-git-branch-name-with-jenkins-git-plugin can help.

**Comment by AlexandreCassagne** [comment] 2019-06-25 19:56
I'm getting a similar issue on GitLab CI

**Comment by ttretau** [comment] 2019-06-28 15:12
@AlexandreCassagne I set GIT_BRANCH and used the 7.1.0beta of @semantic-release/git, now it works for me. Before not..

**Comment by alavaros** [comment] 2019-07-01 07:08
> @AlexandreCassagne I set GIT_BRANCH and used the 7.1.0beta of @semantic-release/git, now it works for me. Before not..

Just tested and I'm still getting the same error.
### package.json
```json
"devDependencies": {
  ...
  "@semantic-release/git": "7.1.0-beta.3",
  ...
}
```
### Jenkins console
```
echo GIT_BRANCH
origin/semantic-release-config-test
...
[06:57:46] [semantic-release] › ✔  Run automated release from branch origin/semantic-release-config-test
2019-07-01T06:57:46.332Z semantic-release:git Error: Command failed: git push --dry-run ssh://git@bitbucket.company/path/to/my/repo.git HEAD:origin/semantic-release-config-test
error: unable to push to unqualified destination: origin/semantic-release-config-test
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'ssh://git@bitbucket.company/path/to/my/repo.git'


    at makeError (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/var/lib/jenkins/jobs/AppDesign/jobs/semantic-release POC/workspace/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
...
```

**Comment by pvdlg** [comment] 2019-07-01 16:59
`GIT_BRANCH` should be `semantic-release-config-test` not `origin/semantic-release-config-test`

**Comment by aakrem** [comment] 2019-07-05 08:50
Same issue is occurring with gitlabCI, with:
```
"@semantic-release/git": "^7.0.16"
"@semantic-release/exec": "^3.3.5"
```

**Comment by aakrem** [comment] 2019-07-09 13:24
@AlexandreCassagne Have you found a way to solve it ?

**Comment by IsmaelMartinez** [comment] 2019-08-07 15:25
Hi,

I had the same issue and was not related to semantic-release but to how Jenkins checks out the branches (detached as `origin/semantic-release-config-test`)

You just need to check it out to "Check out to specific local branch" and give it your desired branch name (`semantic-release-config-test`). 

That works fine with:
```
"semantic-release": "^15.13.19",
"@semantic-release/changelog": "^3.0.4",
"@semantic-release/commit-analyzer": "^6.2.0",
"@semantic-release/error": "^2.2.0",
"@semantic-release/git": "^7.0.16",
"@semantic-release/release-notes-generator": "^7.2.1",
```

and config (in package.json)
```
"release": {
    "branch": "testing",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/git"
    ]
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
```

I have spend most of the day banging my head with this issue... just as I remember the "detached" Jenkins "feature".

**Comment by alavaros** [comment] 2019-08-08 12:45
> Hi,
> 
> I had the same issue and was not related to semantic-release but to how Jenkins checks out the branches (detached as `origin/semantic-release-config-test`)
> 
> You just need to check it out to "Check out to specific local branch" and give it your desired branch name (`semantic-release-config-test`).
> 
> That works fine with:
> 
> ```
> "semantic-release": "^15.13.19",
> "@semantic-release/changelog": "^3.0.4",
> "@semantic-release/commit-analyzer": "^6.2.0",
> "@semantic-release/error": "^2.2.0",
> "@semantic-release/git": "^7.0.16",
> "@semantic-release/release-notes-generator": "^7.2.1",
> ```
> 
> and config (in package.json)
> 
> ```
> "release": {
>     "branch": "semantic-release-config-test",
>     "plugins": [
>       "@semantic-release/commit-analyzer",
>       "@semantic-release/release-notes-generator",
>       "@semantic-release/changelog",
>       "@semantic-release/git"
>     ]
>   },
>   "config": {
>     "commitizen": {
>       "path": "./node_modules/cz-conventional-changelog"
>     }
>   }
> ```
> 
> I have spend most of the day banging my head with this issue... just as I remember the "detached" Jenkins "feature".

Woowww thank you!!! I finally managed to run the semantic-release command from the Jenkins job with this configuration:

- Source Code Management:
  - Git
    - Branches to build: **refs/heads/semantic-release-config-test**
    - Additional Behaviours:
      - Check out to specific local branch: **semantic-release-config-test**

That's it!

**Comment by pvdlg** [comment] 2019-08-13 18:26
Closing as the issue seems to be resolved

**Closed by pvdlg** 2019-08-13 18:26 UTC
Labels: info requested

**Comment by qlonik** [comment] 2019-08-21 16:00
I'm getting the same issue with gitlab-ci this time. It seems that gitlab works in detached mode and there does not seem an option to checkout specific local version (similar to jenkins option). Is it possible to add `CI_COMMIT_REF_NAME` variable to the list of checked variables, since it seems to give name of current branch, as mentioned here: https://docs.gitlab.com/ce/ci/variables/predefined_variables.html 

However, as a workaround, it seems to be possible to add command `git checkout $CI_COMMIT_REF_NAME` in the gitlab-ci build script before running semantic-release
