### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by kbrandwijk** [semantic-release/semantic-release#579] opened 2017-12-31 03:49 UTC
On the releases tab, I see 11.2.0 as latest version. However, on npmjs, I see 11.0.3 as latest version. Especially for a library to support automatic release management, it seems weird to me that there is a version mismatch going on...

**Comment by pvdlg** [comment] 2017-12-31 05:01
Duplicate of #577

**Comment by pvdlg** [comment] 2017-12-31 05:01
See https://github.com/semantic-release/semantic-release/issues/577#issuecomment-354334044

**Comment by kbrandwijk** [comment] 2017-12-31 05:01
Sorry... missed that one...

**Closed by pvdlg** 2017-12-31 05:01 UTC
