### ISSUE TITLE
Failed to release and publish to gitlab

### ISSUE THREAD

**Issue by naerion89** [semantic-release/semantic-release#641] opened 2018-02-05 09:31 UTC
I have an ionic project hosted on gitlab.com. 

I want to release  a version with the semantic-release gitlab plugin but the plugin failed with http error 400 Bad request.

My demo project is hosted at https://gitlab.com/naerion/release-test.git with public visibility.

[release.log](https://github.com/semantic-release/semantic-release/files/1694517/release.log)

Can you help me for this problem ?

Regards,
Gaetan BOGAERT

**Comment by naerion89** [comment] 2018-02-05 09:50
i use node v8.9.4 and yarn

**Comment by pvdlg** [comment] 2018-02-05 16:23
This is because you using the version [2.0.0](https://github.com/semantic-release/gitlab/releases/tag/v2.0.0) of the GitLab plugin which is only compatible with semantic-release 13.0.0.

You can either continue to use semantic-release 12.x.x with the GitLab plugin 1.x.x or you can upgrade to semantic-release 13.x.x

Feel free to re-open if that doesn't solve your issue

**Comment by naerion89** [comment] 2018-02-05 18:48
Thanks for the answer.
I manage to create git tag but i always have a error 400 Bad request with gitlab

**Comment by naerion89** [comment] 2018-02-05 19:00
gitlab plugin  try a put request for creating release
the gitlab API require a post request (https://docs.gitlab.com/ce/api/tags.html#create-a-new-release)

In [history](https://github.com/semantic-release/gitlab/commit/111e8947bdc6c9b02226ede150b7dca406f11f2a#diff-162be319be481edf95e15a28cb4981f5), the post request has been replaced with put request.

gitlab.com is only compatible with semantic-release/gitlab 1.02

**Comment by pvdlg** [comment] 2018-02-05 21:49
I changed it to a `PUT` as I though it would be considered an update of the tag as GitLab doesn't really have to notion of release but only "tag comment".
Test more it seems it's wrong and it should be a `POST`.

Would like to make a PR to fix it?

**Comment by pvdlg** [comment] 2018-02-06 18:56
Following up in semantic-release/gitlab#11

**Comment by pvdlg** [comment] 2018-02-06 18:56
Duplicate of semantic-release/gitlab#11

**Closed by pvdlg** 2018-02-06 18:56 UTC
Labels: bug, config:gitlab
