### ISSUE TITLE
💡 comment on PRs when new version released

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#79] opened 2015-09-05 19:26 UTC
as a contributor who sent a PR with a fix/feature to a project on GitHub, I'd like to be notified when the new version of the project is released that includes my fix/feature.

Would be nice if there would be a way to check to automatically comment pull-requests with commits that have been part of the current release. Would something like that be possible?

**Comment by kentcdodds** [comment] 2015-09-07 12:46
:+1: from me. Based on my limited experience, this sounds like this would totally be possible as a semantic-release plugin

**Comment by ariporad** [comment] 2015-09-07 15:02
I think that the trouble would be mapping commits to PRs. We could
defiantly map it to contributors, but PRs would be tricky.


Ari

**Comment by kentcdodds** [comment] 2015-09-07 15:15
Hmmm... What if I commented on the commit(s) instead of the PR?

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by ariporad** [comment] 2015-09-07 15:17
You can only comment on a specific line of the commit though...


Ari

**Comment by kentcdodds** [comment] 2015-09-07 15:41
![screenshot_2015-09-07-09-39-55](https://cloud.githubusercontent.com/assets/1500684/9719722/77b0c8a2-5544-11e5-9553-57fd64114310.png)

I'm pretty sure you can comment on whole commits. :point_up_2:

**Comment by ariporad** [comment] 2015-09-07 16:05
Oops... Yeah, you're right.

I think thought that this might get annoying for contributors (like
@boennemann).


Ari

**Comment by relekang** [comment] 2015-09-07 16:10
Commenting on issues would also be pretty nice.

**Comment by kentcdodds** [comment] 2015-09-07 17:03
If it's annoying, then the project maintained doesn't have to use the
plugin.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by hbetts** [comment] 2015-10-30 04:45
:+1:

Informing users, and contributors, when a merged change is consumable would save a considerable amount of time for those users, and as a package developer, my own time as well.

**Comment by hbetts** [comment] 2015-11-22 04:09
@ariporad @kentcdodds `semantic-release` uses the `release-notes-generator` plugin, which uses `conventional-changelog`, to generate releases notes with links to issues that are referenced in commits. We should be able to extract those same issue references from commits. Furthermore, once we have the issues, based on my understanding of the GitHub API, we should be able to get the list of Pull Requests.

There doesn't seem to be a plugin phase that is triggered after the release. Any ideas?

**Comment by hbetts** [comment] 2015-11-24 04:43
Just a note here, we could leverage work related to #89 to write notification plugins that will be called after a release is made.

**Comment by pvdlg** [comment] 2018-02-10 00:13
Currently under work as part of #627 and semantic-release/github#32

**Comment by pvdlg** [comment] 2018-02-10 00:13
Duplicate of #627

**Closed by pvdlg** 2018-02-10 00:13 UTC
Labels: feature, plugin:github
